# Generated by Django 5.2.5 on 2026-08-17 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0006_delete_tracks'),
        ('submissions', '0002_seed_components'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_1_name', models.CharField(blank=True, max_length=255)),
                ('director_1_signature', models.FileField(blank=True, null=True, upload_to='grading/signatures/')),
                ('director_2_name', models.CharField(blank=True, max_length=255)),
                ('director_2_signature', models.FileField(blank=True, null=True, upload_to='grading/signatures/')),
                ('marks_summary_template', models.FileField(blank=True, null=True, upload_to='grading/templates/')),
                ('certificate_template', models.FileField(blank=True, null=True, upload_to='grading/templates/')),
                ('component_weights', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'grading_settings',
            },
        ),
        migrations.CreateModel(
            name='MarksRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marks_releases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'marks_release',
            },
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rubrics', to='submissions.submissioncomponent')),
            ],
            options={
                'db_table': 'rubric',
            },
        ),
        migrations.CreateModel(
            name='RubricCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('max_mark', models.DecimalField(decimal_places=2, max_digits=6)),
                ('order', models.PositiveIntegerField(default=0)),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='grading.rubric')),
            ],
            options={
                'db_table': 'rubric_criterion',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('comment', models.TextField(blank=True)),
                ('graded_at', models.DateTimeField(auto_now=True)),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='submissions.submission')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='grading.rubriccriterion')),
            ],
            options={
                'db_table': 'grade',
            },
        ),
        migrations.CreateModel(
            name='FinalistFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flagged_at', models.DateTimeField(auto_now_add=True)),
                ('notified', models.BooleanField(default=False)),
                ('flagged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalist_flags', to=settings.AUTH_USER_MODEL)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finalist_flag', to='groups.groups')),
            ],
            options={
                'db_table': 'finalist_flag',
                'indexes': [models.Index(fields=['notified'], name='finalist_fl_notifie_f4bf42_idx')],
            },
        ),
        migrations.CreateModel(
            name='GradingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('bulk_zip', 'Bulk zip'), ('marks_release', 'Marks release')], max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('result_url', models.URLField(blank=True, max_length=1024)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grading_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'grading_job',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='grading_job_status_8ab56f_idx'), models.Index(fields=['kind', 'status'], name='grading_job_kind_bd26b1_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='rubric',
            index=models.Index(fields=['component', 'year'], name='rubric_compone_b1e57f_idx'),
        ),
        migrations.AddIndex(
            model_name='rubric',
            index=models.Index(fields=['active'], name='rubric_active_7008d1_idx'),
        ),
        migrations.AddConstraint(
            model_name='rubric',
            constraint=models.UniqueConstraint(fields=('component', 'year'), name='unique_rubric_per_component_year'),
        ),
        migrations.AddIndex(
            model_name='rubriccriterion',
            index=models.Index(fields=['rubric', 'order'], name='rubric_crit_rubric__c6bdad_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['submission', 'criterion'], name='grade_submiss_beb5e7_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['graded_at'], name='grade_graded__b3e115_idx'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('submission', 'criterion'), name='unique_grade_per_submission_criterion'),
        ),
    ]
