# Generated by Django 5.2.5 on 2026-09-04 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0003_certificatesrelease'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatesrelease',
            name='exclude_finalists',
            field=models.BooleanField(default=False),
        ),
    ]
