# Generated by Django 5.2.5 on 2026-09-07 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0006_seed_marking_key_rubrics'),
        ('groups', '0006_delete_tracks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMarkingCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_categories', models.JSONField(blank=True, default=list)),
                ('product_category_other', models.CharField(blank=True, max_length=255)),
                ('solution_category', models.CharField(blank=True, max_length=64)),
                ('solution_category_other', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marking_categories', to='groups.groups')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marking_categories_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'grading_group_categories',
            },
        ),
    ]
