# Generated by Django 5.2.5 on 2026-09-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0007_groupmarkingcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingsettings',
            name='director_1_position',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='gradingsettings',
            name='director_2_position',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
