# Generated by Django 5.2.5 on 2026-09-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0008_gradingsettings_director_positions'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalistEmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symposium_date', models.DateField(blank=True, null=True)),
                ('confirm_by', models.DateField(blank=True, null=True)),
                ('slides_due', models.DateField(blank=True, null=True)),
                ('registration_url', models.URLField(blank=True, default='https://events.humanitix.com/biotech-futures-symposium', max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'finalist_email_settings',
            },
        ),
    ]
