# Generated by Django 5.2.5 on 2026-09-28 14:01

import apps.management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0012_nonsubmission_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradingsettings',
            name='certificate_template',
            field=models.FileField(blank=True, null=True, upload_to=apps.management.models.template_upload_to),
        ),
        migrations.AlterField(
            model_name='gradingsettings',
            name='marks_summary_template',
            field=models.FileField(blank=True, null=True, upload_to=apps.management.models.template_upload_to),
        ),
    ]
