# Generated by Django 5.2.5 on 2026-09-28 14:23

import apps.management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0013_template_keeps_uploaded_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingsettings',
            name='mentor_certificate_template',
            field=models.FileField(blank=True, null=True, upload_to=apps.management.models.template_upload_to),
        ),
    ]
