# Generated by Django 5.2.5 on 2026-09-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0015_email_links_start_empty'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentationSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('starts_at', models.TimeField()),
                ('ends_at', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'presentation_slot',
                'ordering': ['year', 'starts_at', 'ends_at'],
                'constraints': [models.UniqueConstraint(fields=('year', 'starts_at', 'ends_at'), name='uniq_presentation_slot_per_year'), models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='presentation_slot_ends_after_it_starts')],
            },
        ),
    ]
