# Generated by Django 5.2.5 on 2026-09-29 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0016_presentation_slots'),
        ('groups', '0011_presentation_availability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentationAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentation_availability', to='groups.groups')),
                ('slots', models.ManyToManyField(blank=True, related_name='available', to='grading.presentationslot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentation_availability', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'presentation_availability',
                'constraints': [models.UniqueConstraint(fields=('group', 'user'), name='uniq_presentation_availability')],
            },
        ),
    ]
