# Generated by Django 5.2.5 on 2026-09-29 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0017_presentation_availability'),
        ('groups', '0011_presentation_availability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalistSlides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.JSONField()),
                ('submitted_at', models.DateTimeField()),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finalist_slides', to='groups.groups')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalist_slides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'finalist_slides',
            },
        ),
    ]
