# Generated by Django 5.2.5 on 2026-09-29 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0018_finalist_slides'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalistflag',
            name='presentation_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_flags', to='grading.presentationslot'),
        ),
    ]
