# Generated by Django 5.2.5 on 2025-09-12 02:47

import django.db.models.deletion
import django.db.models.functions.datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sessions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "access_datetime",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("isloggedin", models.BooleanField(db_column="isLoggedin")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.users"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sessions",
                "db_table": "sessions",
                "ordering": ["-access_datetime"],
            },
        ),
        migrations.CreateModel(
            name="Alerts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_timestamp",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("error_reason", models.CharField(max_length=255)),
                ("resolved", models.BooleanField(default=False)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="user_sessions.sessions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerts",
                "db_table": "alerts",
                "ordering": ["-alert_timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="sessions",
            index=models.Index(fields=["user"], name="sessions_user_id_7acd24_idx"),
        ),
        migrations.AddIndex(
            model_name="sessions",
            index=models.Index(
                fields=["access_datetime"], name="sessions_access__0097e9_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="sessions",
            constraint=models.UniqueConstraint(
                fields=("user", "access_datetime"), name="unique_user_session"
            ),
        ),
        migrations.AddConstraint(
            model_name="sessions",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("access_datetime__lte", django.db.models.functions.datetime.Now())
                ),
                name="access_not_in_future",
            ),
        ),
        migrations.AddIndex(
            model_name="alerts",
            index=models.Index(fields=["session"], name="alerts_session_6b4a0a_idx"),
        ),
        migrations.AddIndex(
            model_name="alerts",
            index=models.Index(fields=["resolved"], name="alerts_resolve_915a53_idx"),
        ),
        migrations.AddIndex(
            model_name="alerts",
            index=models.Index(
                fields=["alert_timestamp"], name="alerts_alert_t_e3b260_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="alerts",
            constraint=models.UniqueConstraint(
                fields=("session", "alert_timestamp", "error_reason"),
                name="unique_alert_user_session",
            ),
        ),
        migrations.AddConstraint(
            model_name="alerts",
            constraint=models.CheckConstraint(
                condition=models.Q(("error_reason", ""), _negated=True),
                name="alert_reason_not_empty",
            ),
        ),
    ]
