# Generated by Django 5.2.5 on 2026-04-20 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alert',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='user_sessions.usersession'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user'], name='user_sessio_user_id_c6fc39_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['sid'], name='user_sessio_sid_1a73c0_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['expires_at'], name='user_sessio_expires_85bda6_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['last_activity_at'], name='user_sessio_last_ac_a7b43b_idx'),
        ),
        migrations.AddConstraint(
            model_name='usersession',
            constraint=models.CheckConstraint(condition=models.Q(('last_activity_at__gte', models.F('created_at'))), name='user_session_activity_after_created'),
        ),
        migrations.AddConstraint(
            model_name='usersession',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__gte', models.F('created_at'))), name='user_session_expires_after_created'),
        ),
        migrations.AddConstraint(
            model_name='usersession',
            constraint=models.CheckConstraint(condition=models.Q(('ended_at__gte', models.F('created_at')), ('ended_at__isnull', True), _connector='OR'), name='user_session_ended_after_created'),
        ),
        migrations.AddConstraint(
            model_name='usersession',
            constraint=models.CheckConstraint(condition=models.Q(('revoked_at__gte', models.F('created_at')), ('revoked_at__isnull', True), _connector='OR'), name='user_session_revoked_after_created'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['session'], name='alert_session_0863a0_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['resolved'], name='alert_resolve_79070e_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['created_at'], name='alert_created_417cb1_idx'),
        ),
        migrations.AddConstraint(
            model_name='alert',
            constraint=models.CheckConstraint(condition=models.Q(('error_reason', ''), _negated=True), name='alert_reason_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='alert',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('resolved', False), ('resolved_at__isnull', True)), models.Q(('resolved', True), ('resolved_at__isnull', False)), _connector='OR'), name='alert_resolved_matches_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='alert',
            constraint=models.CheckConstraint(condition=models.Q(('resolved_at__gte', models.F('created_at')), ('resolved_at__isnull', True), _connector='OR'), name='alert_resolved_after_created'),
        ),
    ]
