# Generated by Django 5.2.5 on 2026-04-20 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0002_initial'),
        ('matching_runtime', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='matchrecommendation',
            name='mentor_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matchrun',
            name='initiated_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matchrun',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.tracks'),
        ),
        migrations.AddField(
            model_name='matchrecommendation',
            name='match_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='matching_runtime.matchrun'),
        ),
        migrations.AddIndex(
            model_name='matchrun',
            index=models.Index(fields=['initiated_by_user'], name='match_run_initiat_12e56d_idx'),
        ),
        migrations.AddIndex(
            model_name='matchrun',
            index=models.Index(fields=['track'], name='match_run_track_i_060ec1_idx'),
        ),
        migrations.AddIndex(
            model_name='matchrun',
            index=models.Index(fields=['run_type'], name='match_run_run_typ_e4c0d2_idx'),
        ),
        migrations.AddIndex(
            model_name='matchrun',
            index=models.Index(fields=['created_at'], name='match_run_created_ea68ea_idx'),
        ),
        migrations.AddIndex(
            model_name='matchrecommendation',
            index=models.Index(fields=['match_run'], name='match_recom_match_r_e5666c_idx'),
        ),
        migrations.AddIndex(
            model_name='matchrecommendation',
            index=models.Index(fields=['group'], name='match_recom_group_i_56802c_idx'),
        ),
        migrations.AddIndex(
            model_name='matchrecommendation',
            index=models.Index(fields=['mentor_user'], name='match_recom_mentor__d96f14_idx'),
        ),
        migrations.AddIndex(
            model_name='matchrecommendation',
            index=models.Index(fields=['accepted'], name='match_recom_accepte_50fa36_idx'),
        ),
        migrations.AddConstraint(
            model_name='matchrecommendation',
            constraint=models.UniqueConstraint(fields=('match_run', 'group', 'mentor_user'), name='unique_match_recommendation_per_run_group_mentor'),
        ),
    ]
