# Generated by Django 5.2.5 on 2026-07-07 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching_runtime', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='matchrun',
            name='match_run_track_i_060ec1_idx',
        ),
        migrations.RemoveField(
            model_name='matchrun',
            name='track',
        ),
    ]
