# Generated by Django 5.2.5 on 2026-10-06 00:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching_runtime', '0003_remove_matchrun_match_run_track_i_060ec1_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('year_weight', models.DecimalField(decimal_places=2, help_text='Percentage of the base score charged per year of year-level gap.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('country_mismatch_weight', models.DecimalField(decimal_places=2, help_text='Reported weight for a cross-country pair; ranks ties only.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('timezone_weight', models.DecimalField(decimal_places=2, help_text='Percentage of the base score charged per hour of timezone gap.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('timezone_max_weight', models.DecimalField(decimal_places=2, help_text='Cap on the timezone penalty, as a percentage of the base score.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('size_bonus_weight', models.DecimalField(decimal_places=2, help_text='Bonus for a full-sized group, as a percentage of the base score.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matching_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'matching_config',
                'ordering': ['-updated_at', '-id'],
            },
        ),
    ]
