# Generated by Django 5.2.5 on 2026-10-08 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching_runtime', '0004_matchingconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchingconfig',
            name='country_mismatch_weight',
        ),
    ]
