# Generated by Django 5.2.5 on 2026-10-09 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching_runtime', '0005_remove_matchingconfig_country_mismatch_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchingconfig',
            name='name',
        ),
    ]
