# Generated by Django 5.2.5 on 2026-10-09 06:28

from django.db import migrations


def keep_only_the_stored_config(apps, schema_editor):
    MatchingConfig = apps.get_model("matching_runtime", "MatchingConfig")
    # A config is now a singleton: keep the row that was in force (falling back
    # to the most recent was it not marked active) and drop the rest. The column
    # is still present here, so the historical model can read ``is_active``.
    rows = list(MatchingConfig.objects.order_by("-is_active", "-updated_at", "-id"))
    for stale in rows[1:]:
        stale.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('matching_runtime', '0006_remove_matchingconfig_name'),
    ]

    operations = [
        migrations.RunPython(keep_only_the_stored_config, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='matchingconfig',
            name='is_active',
        ),
    ]