# Generated by Django 5.2.5 on 2026-04-18 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='logintoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='logintoken',
            index=models.Index(fields=['user', 'token'], name='login_token_user_id_e66ea4_idx'),
        ),
        migrations.AddIndex(
            model_name='logintoken',
            index=models.Index(fields=['expires_at'], name='login_token_expires_133cb3_idx'),
        ),
        migrations.AddIndex(
            model_name='logintoken',
            index=models.Index(fields=['created_at'], name='login_token_created_7a566c_idx'),
        ),
    ]
