# Generated by Django 5.2.5 on 2026-10-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_system_email_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='systememailtemplate',
            name='sender',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
