# Generated by Django 5.2.5 on 2026-10-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_system_email_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='systememailsettings',
            name='failures_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
