# Generated by Django 6.0.4 on 2026-04-28 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshops',
            old_name='deleted_datetime',
            new_name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='workshops',
            name='deleted_flag',
        ),
    ]
