# Generated by Django 5.2.5 on 2026-04-19 01:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('email_verified', models.BooleanField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admin User',
                'verbose_name_plural': 'Admin Users',
                'db_table': 'admin_user',
                'indexes': [models.Index(fields=['email'], name='admin_user_email_6dce57_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdminSession',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField()),
                ('token', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.TextField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='admin_sessions', to='admin_auth.adminuser')),
            ],
            options={
                'verbose_name': 'Admin Session',
                'verbose_name_plural': 'Admin Sessions',
                'db_table': 'session',
                'indexes': [models.Index(fields=['user'], name='session_user_id_165a07_idx'), models.Index(fields=['token'], name='session_token_9105e5_idx'), models.Index(fields=['expires_at'], name='session_expires_3ca8aa_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdminMatchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_type', models.CharField(max_length=100)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('result', models.JSONField(blank=True, null=True)),
                ('admin_user', models.ForeignKey(db_column='admin_user_id', on_delete=django.db.models.deletion.RESTRICT, related_name='match_runs', to='admin_auth.adminuser')),
            ],
            options={
                'verbose_name': 'Admin Match Run',
                'verbose_name_plural': 'Admin Match Runs',
                'db_table': 'admin_match_run',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['admin_user'], name='admin_match_admin_u_d3f9c3_idx'), models.Index(fields=['run_type'], name='admin_match_run_typ_f99505_idx'), models.Index(fields=['created_at'], name='admin_match_created_e26c04_idx')],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('account_id', models.TextField()),
                ('provider_id', models.TextField()),
                ('access_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('access_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('refresh_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('scope', models.TextField(blank=True, null=True)),
                ('password', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='admin_auth.adminuser')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'db_table': 'account',
                'indexes': [models.Index(fields=['user'], name='account_user_id_5ee0be_idx'), models.Index(fields=['provider_id', 'account_id'], name='account_provide_b44e3e_idx')],
            },
        ),
    ]
