# Generated by Django 5.2.5 on 2026-04-12 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('groups', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminscope',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.tracks'),
        ),
        migrations.AddField(
            model_name='user',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='groups.tracks'),
        ),
        migrations.AddIndex(
            model_name='adminscope',
            index=models.Index(fields=['track'], name='admin_scope_track_i_594c81_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['track'], name='users_track_i_1a6677_idx'),
        ),
        migrations.AddConstraint(
            model_name='adminscope',
            constraint=models.UniqueConstraint(condition=models.Q(('is_global', False)), fields=('user', 'track'), name='unique_admin_scope_per_track'),
        ),
        migrations.AddConstraint(
            model_name='adminscope',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_global', True), ('track__isnull', True)), models.Q(('is_global', False), ('track__isnull', False)), _connector='OR'), name='admin_scope_global_or_track'),
        ),
    ]
