# Generated by Django 5.2.5 on 2026-04-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_sync_model_state'),
        ('users', '0002_target_ddl_schema'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studentprofile',
            name='permission_requires_parent_guardian',
        ),
        migrations.RenameIndex(
            model_name='mentoravailability',
            new_name='mentor_avai_mentor__83178e_idx',
            old_name='mentor_avai_mentor_prof_idx',
        ),
        migrations.RenameIndex(
            model_name='mentorinterest',
            new_name='mentor_inte_mentor__6390ed_idx',
            old_name='mentor_inte_mentor_prof_idx',
        ),
        migrations.RenameIndex(
            model_name='studentinterest',
            new_name='student_int_student_787240_idx',
            old_name='student_int_student_idx',
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='join_permission_response_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='studentprofile',
            constraint=models.CheckConstraint(condition=models.Q(('join_permission_received', False), ('parent_guardian_flag', True), _connector='OR'), name='permission_requires_parent_guardian'),
        ),
    ]
