# Generated by Django 5.2.5 on 2026-05-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='ban_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='ban_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='tracks',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
