# Generated by Django 5.2.5 on 2026-04-03 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_user_schema(apps, schema_editor):
    MentorProfile = apps.get_model("users", "MentorProfile")
    User = apps.get_model("users", "User")

    for mentor in MentorProfile.objects.all().only("pk", "max_grp_cnt").iterator():
        MentorProfile.objects.filter(pk=mentor.pk).update(max_group_count=mentor.max_grp_cnt)

    for user in User.objects.all().only("pk", "status", "date_joined", "activated_at").iterator():
        if user.status:
            User.objects.filter(pk=user.pk).update(
                account_status="active",
                activated_at=user.activated_at or user.date_joined,
            )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("groups", "0002_initial"),
        ("users", "0003_studentprofile_joinperm_responseid"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminScope",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_global", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Admin Scope",
                "verbose_name_plural": "Admin Scopes",
                "db_table": "admin_scope",
            },
        ),
        migrations.CreateModel(
            name="MentorAvailability",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("weekday", models.PositiveSmallIntegerField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
            ],
            options={
                "verbose_name": "Mentor Availability",
                "verbose_name_plural": "Mentor Availability",
                "db_table": "mentor_availability",
            },
        ),
        migrations.CreateModel(
            name="MentorInterest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
            options={
                "verbose_name": "Mentor Interest",
                "verbose_name_plural": "Mentor Interests",
                "db_table": "mentor_interest",
            },
        ),
        migrations.AddField(
            model_name="mentorprofile",
            name="max_group_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="account_status",
            field=models.CharField(
                choices=[
                    ("invited", "Invited"),
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("suspended", "Suspended"),
                    ("deactivated", "Deactivated"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="activated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="invited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mentorprofile",
            name="background",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="users.background"),
        ),
        migrations.RunPython(backfill_user_schema, noop),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["account_status"], name="users_account_33da0c_idx"),
        ),
        migrations.AddConstraint(
            model_name="mentorprofile",
            constraint=models.CheckConstraint(condition=models.Q(("max_group_count__gte", 0)), name="mentor_max_group_count_non_negative"),
        ),
        migrations.AddField(
            model_name="adminscope",
            name="track",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="groups.tracks"),
        ),
        migrations.AddField(
            model_name="adminscope",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="mentoravailability",
            name="mentor_user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="mentorinterest",
            name="interest",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="users.areasofinterest"),
        ),
        migrations.AddField(
            model_name="mentorinterest",
            name="mentor_user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name="adminscope",
            index=models.Index(fields=["user"], name="admin_scope_user_id_4ad1f0_idx"),
        ),
        migrations.AddIndex(
            model_name="adminscope",
            index=models.Index(fields=["track"], name="admin_scope_track_i_594c81_idx"),
        ),
        migrations.AddConstraint(
            model_name="adminscope",
            constraint=models.UniqueConstraint(condition=models.Q(("is_global", False)), fields=("user", "track"), name="unique_admin_scope_per_track"),
        ),
        migrations.AddConstraint(
            model_name="adminscope",
            constraint=models.UniqueConstraint(condition=models.Q(("is_global", True)), fields=("user",), name="unique_global_admin_scope"),
        ),
        migrations.AddConstraint(
            model_name="adminscope",
            constraint=models.CheckConstraint(
                condition=models.Q(models.Q(("is_global", True), ("track__isnull", True)), models.Q(("is_global", False), ("track__isnull", False)), _connector="OR"),
                name="admin_scope_global_or_track",
            ),
        ),
        migrations.AddIndex(
            model_name="mentoravailability",
            index=models.Index(fields=["mentor_user"], name="mentor_avai_mentor__83178e_idx"),
        ),
        migrations.AddIndex(
            model_name="mentoravailability",
            index=models.Index(fields=["weekday"], name="mentor_avai_weekday_25332b_idx"),
        ),
        migrations.AddConstraint(
            model_name="mentoravailability",
            constraint=models.UniqueConstraint(fields=("mentor_user", "weekday", "start_time", "end_time"), name="unique_mentor_availability_slot"),
        ),
        migrations.AddConstraint(
            model_name="mentoravailability",
            constraint=models.CheckConstraint(condition=models.Q(("weekday__gte", 0), ("weekday__lte", 6)), name="mentor_availability_weekday_valid"),
        ),
        migrations.AddConstraint(
            model_name="mentoravailability",
            constraint=models.CheckConstraint(condition=models.Q(("end_time__gt", models.F("start_time"))), name="mentor_availability_end_after_start"),
        ),
        migrations.AddIndex(
            model_name="mentorinterest",
            index=models.Index(fields=["mentor_user"], name="mentor_inte_mentor__6390ed_idx"),
        ),
        migrations.AddIndex(
            model_name="mentorinterest",
            index=models.Index(fields=["interest"], name="mentor_inte_interes_88f17e_idx"),
        ),
        migrations.AddConstraint(
            model_name="mentorinterest",
            constraint=models.UniqueConstraint(fields=("mentor_user", "interest"), name="unique_mentor_interest"),
        ),
    ]
