# Generated by Django 5.2.5 on 2026-07-04 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisorprofile',
            name='school_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
