# Generated by Django 5.2.5 on 2026-04-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_adminscope_mentoravailability_mentorinterest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mentorprofile",
            name="background",
        ),
        migrations.RemoveConstraint(
            model_name="mentorprofile",
            name="mentor_max_grp_non_negative",
        ),
        migrations.RemoveIndex(
            model_name="studentprofile",
            name="student_pro_interes_58353d_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="users_state_i_69ebd8_idx",
        ),
        migrations.RemoveField(
            model_name="mentorprofile",
            name="max_grp_cnt",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="interest",
        ),
        migrations.RemoveField(
            model_name="user",
            name="state",
        ),
        migrations.RemoveField(
            model_name="user",
            name="status",
        ),
        migrations.AlterField(
            model_name="mentorprofile",
            name="max_group_count",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name="Background",
        ),
    ]
