# Generated by Django 5.2.5 on 2026-04-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_mentorprofile_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorprofile',
            name='max_group_count',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
