# Generated by Django 5.2.5 on 2026-04-03 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_mentorprofile_max_group_count_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name="studentsupervisor",
                    name="relationship_type_not_null",
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="studentsupervisor",
            name="relationship_type",
        ),
        migrations.DeleteModel(
            name="RelationshipType",
        ),
    ]
