# Generated by Django 5.2.5 on 2026-04-11 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_refined_schema_step1'),
        ('users', '0007_remove_studentsupervisor_relationship_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='background',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_profiles', to='groups.countries'),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='region',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_profiles', to='groups.countrystates'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profiles', to='groups.countries'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='preassigned_group',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profiles', to='groups.countrystates'),
        ),
        migrations.AddIndex(
            model_name='mentorprofile',
            index=models.Index(fields=['country'], name='mentor_prof_country_3b9d6a_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorprofile',
            index=models.Index(fields=['state'], name='mentor_prof_state_i_c2446b_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['country'], name='student_pro_country_98bca0_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['state'], name='student_pro_state_i_828ff6_idx'),
        ),
    ]
