# Generated by Django 5.2.5 on 2026-07-14 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_user_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorprofile',
            name='mentor_reason',
            field=models.TextField(),
        ),
    ]
