# Generated by Django 5.2.5 on 2026-10-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_studentprofile_joinperm_granted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="pending_pg_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="pending_pg_first_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="pending_pg_last_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="pending_pg_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
