# Generated by Django 5.2.5 on 2026-09-25 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_studentprofile_joinperm_granted_at"),
        ("users", "0012_user_profile_image"),
    ]

    operations = []
