# Generated by Django 5.2.5 on 2026-10-08 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_studentprofile_pending_guardian"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="media_consent",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="GuardianConsentRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                (
                    "guardian_first_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "guardian_last_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("guardian_email", models.EmailField(max_length=254)),
                ("for_pending_guardian", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consent_requests",
                        to="users.studentprofile",
                    ),
                ),
            ],
            options={
                "db_table": "guardian_consent_request",
            },
        ),
        migrations.CreateModel(
            name="GuardianConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guardian_full_name", models.CharField(max_length=255)),
                ("guardian_email", models.EmailField(max_length=254)),
                ("media_consent", models.BooleanField()),
                ("signature_png", models.BinaryField()),
                ("consent_version", models.CharField(max_length=32)),
                ("signed_at", models.DateTimeField(auto_now_add=True)),
                ("signed_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "signed_user_agent",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
                ("media_withdrawn_at", models.DateTimeField(blank=True, null=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consents",
                        to="users.studentprofile",
                    ),
                ),
                (
                    "request",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consent",
                        to="users.guardianconsentrequest",
                    ),
                ),
            ],
            options={
                "db_table": "guardian_consent",
            },
        ),
        migrations.AddIndex(
            model_name="guardianconsentrequest",
            index=models.Index(
                fields=["student", "-created_at"], name="guardian_co_student_b6e93e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="guardianconsent",
            index=models.Index(
                fields=["student", "-signed_at"], name="guardian_co_student_843e3a_idx"
            ),
        ),
    ]
