# Generated by Django 5.2.5 on 2026-10-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_studentprofile_pending_guardian"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="guardian_request_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
