# Generated by Django 5.2.5 on 2026-10-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_guardian_consent"),
    ]

    operations = [
        migrations.AddField(
            model_name="guardianconsent",
            name="record_pdf_key",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
