# Generated by Django 5.2.5 on 2026-10-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_guardian_consent_record_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='guardian_details_reminded_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
