# Generated by Django 5.2.5 on 2026-10-09 08:47

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_studentprofile_registered_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnownUniversity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Known University',
                'verbose_name_plural': 'Known Universities',
                'db_table': 'known_university',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='known_university_name_unique')],
            },
        ),
    ]
