# Generated by Django 5.2.5 on 2026-10-09 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_studentprofile_registered_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardianconsent',
            name='record_pdf_key',
        ),
    ]
