# Generated by Django 5.2.5 on 2026-10-09 15:11

from django.db import migrations, models


def name_signed_consents(apps, schema_editor):
    """Consents signed before the name was kept get the student's name as it
    is now, the closest there is to the name they signed under."""
    GuardianConsent = apps.get_model("users", "GuardianConsent")
    for consent in GuardianConsent.objects.filter(student_full_name="").select_related("student__user"):
        user = consent.student.user
        name = f"{user.first_name or ''} {user.last_name or ''}".strip() or user.email
        GuardianConsent.objects.filter(pk=consent.pk).update(student_full_name=name[:255])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_guardianconsent_record_pdf_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardianconsent',
            name='student_full_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.RunPython(name_signed_consents, migrations.RunPython.noop),
    ]
