# Generated by Django 5.2.5 on 2026-10-09 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_known_university'),
        ('users', '0020_guardianconsent_student_full_name'),
    ]

    operations = [
    ]
