/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SetupPasswordRouteImport } from './routes/setup-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthUserRouteImport } from './routes/_auth/user'
import { Route as AuthTaskRouteImport } from './routes/_auth/task'
import { Route as AuthStudentRouteImport } from './routes/_auth/student'
import { Route as AuthResourceRouteImport } from './routes/_auth/resource'
import { Route as AuthMentorMatchingRouteImport } from './routes/_auth/mentorMatching'
import { Route as AuthMentorRouteImport } from './routes/_auth/mentor'
import { Route as AuthMatchingRouteImport } from './routes/_auth/matching'
import { Route as AuthGroupRouteImport } from './routes/_auth/group'
import { Route as AuthEventRouteImport } from './routes/_auth/event'
import { Route as AuthAnnouncementRouteImport } from './routes/_auth/announcement'
import { Route as AuthPeopleRouteRouteImport } from './routes/_auth/people/route'
import { Route as AuthGroupsRouteRouteImport } from './routes/_auth/groups/route'
import { Route as AuthPeopleIndexRouteImport } from './routes/_auth/people/index'
import { Route as AuthGroupsIndexRouteImport } from './routes/_auth/groups/index'
import { Route as AuthPeopleSupervisorsRouteImport } from './routes/_auth/people/supervisors'
import { Route as AuthPeopleStudentsRouteImport } from './routes/_auth/people/students'
import { Route as AuthPeopleMentorsRouteImport } from './routes/_auth/people/mentors'
import { Route as AuthGroupsStudentMatchingRouteImport } from './routes/_auth/groups/student-matching'
import { Route as AuthGroupsMentorMatchingRouteImport } from './routes/_auth/groups/mentor-matching'
import { Route as AuthGroupsMatchedGroupsRouteImport } from './routes/_auth/groups/matched-groups'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupPasswordRoute = SetupPasswordRouteImport.update({
  id: '/setup-password',
  path: '/setup-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUserRoute = AuthUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthTaskRoute = AuthTaskRouteImport.update({
  id: '/task',
  path: '/task',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthStudentRoute = AuthStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResourceRoute = AuthResourceRouteImport.update({
  id: '/resource',
  path: '/resource',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthMentorMatchingRoute = AuthMentorMatchingRouteImport.update({
  id: '/mentorMatching',
  path: '/mentorMatching',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthMentorRoute = AuthMentorRouteImport.update({
  id: '/mentor',
  path: '/mentor',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthMatchingRoute = AuthMatchingRouteImport.update({
  id: '/matching',
  path: '/matching',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthGroupRoute = AuthGroupRouteImport.update({
  id: '/group',
  path: '/group',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthEventRoute = AuthEventRouteImport.update({
  id: '/event',
  path: '/event',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAnnouncementRoute = AuthAnnouncementRouteImport.update({
  id: '/announcement',
  path: '/announcement',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthPeopleRouteRoute = AuthPeopleRouteRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthGroupsRouteRoute = AuthGroupsRouteRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthPeopleIndexRoute = AuthPeopleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthPeopleRouteRoute,
} as any)
const AuthGroupsIndexRoute = AuthGroupsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthGroupsRouteRoute,
} as any)
const AuthPeopleSupervisorsRoute = AuthPeopleSupervisorsRouteImport.update({
  id: '/supervisors',
  path: '/supervisors',
  getParentRoute: () => AuthPeopleRouteRoute,
} as any)
const AuthPeopleStudentsRoute = AuthPeopleStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AuthPeopleRouteRoute,
} as any)
const AuthPeopleMentorsRoute = AuthPeopleMentorsRouteImport.update({
  id: '/mentors',
  path: '/mentors',
  getParentRoute: () => AuthPeopleRouteRoute,
} as any)
const AuthGroupsStudentMatchingRoute =
  AuthGroupsStudentMatchingRouteImport.update({
    id: '/student-matching',
    path: '/student-matching',
    getParentRoute: () => AuthGroupsRouteRoute,
  } as any)
const AuthGroupsMentorMatchingRoute =
  AuthGroupsMentorMatchingRouteImport.update({
    id: '/mentor-matching',
    path: '/mentor-matching',
    getParentRoute: () => AuthGroupsRouteRoute,
  } as any)
const AuthGroupsMatchedGroupsRoute = AuthGroupsMatchedGroupsRouteImport.update({
  id: '/matched-groups',
  path: '/matched-groups',
  getParentRoute: () => AuthGroupsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup-password': typeof SetupPasswordRoute
  '/signin': typeof SigninRoute
  '/groups': typeof AuthGroupsRouteRouteWithChildren
  '/people': typeof AuthPeopleRouteRouteWithChildren
  '/announcement': typeof AuthAnnouncementRoute
  '/event': typeof AuthEventRoute
  '/group': typeof AuthGroupRoute
  '/matching': typeof AuthMatchingRoute
  '/mentor': typeof AuthMentorRoute
  '/mentorMatching': typeof AuthMentorMatchingRoute
  '/resource': typeof AuthResourceRoute
  '/student': typeof AuthStudentRoute
  '/task': typeof AuthTaskRoute
  '/user': typeof AuthUserRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/groups/matched-groups': typeof AuthGroupsMatchedGroupsRoute
  '/groups/mentor-matching': typeof AuthGroupsMentorMatchingRoute
  '/groups/student-matching': typeof AuthGroupsStudentMatchingRoute
  '/people/mentors': typeof AuthPeopleMentorsRoute
  '/people/students': typeof AuthPeopleStudentsRoute
  '/people/supervisors': typeof AuthPeopleSupervisorsRoute
  '/groups/': typeof AuthGroupsIndexRoute
  '/people/': typeof AuthPeopleIndexRoute
}
export interface FileRoutesByTo {
  '/reset-password': typeof ResetPasswordRoute
  '/setup-password': typeof SetupPasswordRoute
  '/signin': typeof SigninRoute
  '/announcement': typeof AuthAnnouncementRoute
  '/event': typeof AuthEventRoute
  '/group': typeof AuthGroupRoute
  '/matching': typeof AuthMatchingRoute
  '/mentor': typeof AuthMentorRoute
  '/mentorMatching': typeof AuthMentorMatchingRoute
  '/resource': typeof AuthResourceRoute
  '/student': typeof AuthStudentRoute
  '/task': typeof AuthTaskRoute
  '/user': typeof AuthUserRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/': typeof AuthIndexRoute
  '/groups/matched-groups': typeof AuthGroupsMatchedGroupsRoute
  '/groups/mentor-matching': typeof AuthGroupsMentorMatchingRoute
  '/groups/student-matching': typeof AuthGroupsStudentMatchingRoute
  '/people/mentors': typeof AuthPeopleMentorsRoute
  '/people/students': typeof AuthPeopleStudentsRoute
  '/people/supervisors': typeof AuthPeopleSupervisorsRoute
  '/groups': typeof AuthGroupsIndexRoute
  '/people': typeof AuthPeopleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/setup-password': typeof SetupPasswordRoute
  '/signin': typeof SigninRoute
  '/_auth/groups': typeof AuthGroupsRouteRouteWithChildren
  '/_auth/people': typeof AuthPeopleRouteRouteWithChildren
  '/_auth/announcement': typeof AuthAnnouncementRoute
  '/_auth/event': typeof AuthEventRoute
  '/_auth/group': typeof AuthGroupRoute
  '/_auth/matching': typeof AuthMatchingRoute
  '/_auth/mentor': typeof AuthMentorRoute
  '/_auth/mentorMatching': typeof AuthMentorMatchingRoute
  '/_auth/resource': typeof AuthResourceRoute
  '/_auth/student': typeof AuthStudentRoute
  '/_auth/task': typeof AuthTaskRoute
  '/_auth/user': typeof AuthUserRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/groups/matched-groups': typeof AuthGroupsMatchedGroupsRoute
  '/_auth/groups/mentor-matching': typeof AuthGroupsMentorMatchingRoute
  '/_auth/groups/student-matching': typeof AuthGroupsStudentMatchingRoute
  '/_auth/people/mentors': typeof AuthPeopleMentorsRoute
  '/_auth/people/students': typeof AuthPeopleStudentsRoute
  '/_auth/people/supervisors': typeof AuthPeopleSupervisorsRoute
  '/_auth/groups/': typeof AuthGroupsIndexRoute
  '/_auth/people/': typeof AuthPeopleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reset-password'
    | '/setup-password'
    | '/signin'
    | '/groups'
    | '/people'
    | '/announcement'
    | '/event'
    | '/group'
    | '/matching'
    | '/mentor'
    | '/mentorMatching'
    | '/resource'
    | '/student'
    | '/task'
    | '/user'
    | '/auth/callback'
    | '/groups/matched-groups'
    | '/groups/mentor-matching'
    | '/groups/student-matching'
    | '/people/mentors'
    | '/people/students'
    | '/people/supervisors'
    | '/groups/'
    | '/people/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/reset-password'
    | '/setup-password'
    | '/signin'
    | '/announcement'
    | '/event'
    | '/group'
    | '/matching'
    | '/mentor'
    | '/mentorMatching'
    | '/resource'
    | '/student'
    | '/task'
    | '/user'
    | '/auth/callback'
    | '/'
    | '/groups/matched-groups'
    | '/groups/mentor-matching'
    | '/groups/student-matching'
    | '/people/mentors'
    | '/people/students'
    | '/people/supervisors'
    | '/groups'
    | '/people'
  id:
    | '__root__'
    | '/_auth'
    | '/reset-password'
    | '/setup-password'
    | '/signin'
    | '/_auth/groups'
    | '/_auth/people'
    | '/_auth/announcement'
    | '/_auth/event'
    | '/_auth/group'
    | '/_auth/matching'
    | '/_auth/mentor'
    | '/_auth/mentorMatching'
    | '/_auth/resource'
    | '/_auth/student'
    | '/_auth/task'
    | '/_auth/user'
    | '/auth/callback'
    | '/_auth/'
    | '/_auth/groups/matched-groups'
    | '/_auth/groups/mentor-matching'
    | '/_auth/groups/student-matching'
    | '/_auth/people/mentors'
    | '/_auth/people/students'
    | '/_auth/people/supervisors'
    | '/_auth/groups/'
    | '/_auth/people/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetupPasswordRoute: typeof SetupPasswordRoute
  SigninRoute: typeof SigninRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup-password': {
      id: '/setup-password'
      path: '/setup-password'
      fullPath: '/setup-password'
      preLoaderRoute: typeof SetupPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/user': {
      id: '/_auth/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof AuthUserRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/task': {
      id: '/_auth/task'
      path: '/task'
      fullPath: '/task'
      preLoaderRoute: typeof AuthTaskRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/student': {
      id: '/_auth/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof AuthStudentRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/resource': {
      id: '/_auth/resource'
      path: '/resource'
      fullPath: '/resource'
      preLoaderRoute: typeof AuthResourceRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/mentorMatching': {
      id: '/_auth/mentorMatching'
      path: '/mentorMatching'
      fullPath: '/mentorMatching'
      preLoaderRoute: typeof AuthMentorMatchingRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/mentor': {
      id: '/_auth/mentor'
      path: '/mentor'
      fullPath: '/mentor'
      preLoaderRoute: typeof AuthMentorRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/matching': {
      id: '/_auth/matching'
      path: '/matching'
      fullPath: '/matching'
      preLoaderRoute: typeof AuthMatchingRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/group': {
      id: '/_auth/group'
      path: '/group'
      fullPath: '/group'
      preLoaderRoute: typeof AuthGroupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/event': {
      id: '/_auth/event'
      path: '/event'
      fullPath: '/event'
      preLoaderRoute: typeof AuthEventRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/announcement': {
      id: '/_auth/announcement'
      path: '/announcement'
      fullPath: '/announcement'
      preLoaderRoute: typeof AuthAnnouncementRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/people': {
      id: '/_auth/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof AuthPeopleRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/groups': {
      id: '/_auth/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AuthGroupsRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/people/': {
      id: '/_auth/people/'
      path: '/'
      fullPath: '/people/'
      preLoaderRoute: typeof AuthPeopleIndexRouteImport
      parentRoute: typeof AuthPeopleRouteRoute
    }
    '/_auth/groups/': {
      id: '/_auth/groups/'
      path: '/'
      fullPath: '/groups/'
      preLoaderRoute: typeof AuthGroupsIndexRouteImport
      parentRoute: typeof AuthGroupsRouteRoute
    }
    '/_auth/people/supervisors': {
      id: '/_auth/people/supervisors'
      path: '/supervisors'
      fullPath: '/people/supervisors'
      preLoaderRoute: typeof AuthPeopleSupervisorsRouteImport
      parentRoute: typeof AuthPeopleRouteRoute
    }
    '/_auth/people/students': {
      id: '/_auth/people/students'
      path: '/students'
      fullPath: '/people/students'
      preLoaderRoute: typeof AuthPeopleStudentsRouteImport
      parentRoute: typeof AuthPeopleRouteRoute
    }
    '/_auth/people/mentors': {
      id: '/_auth/people/mentors'
      path: '/mentors'
      fullPath: '/people/mentors'
      preLoaderRoute: typeof AuthPeopleMentorsRouteImport
      parentRoute: typeof AuthPeopleRouteRoute
    }
    '/_auth/groups/student-matching': {
      id: '/_auth/groups/student-matching'
      path: '/student-matching'
      fullPath: '/groups/student-matching'
      preLoaderRoute: typeof AuthGroupsStudentMatchingRouteImport
      parentRoute: typeof AuthGroupsRouteRoute
    }
    '/_auth/groups/mentor-matching': {
      id: '/_auth/groups/mentor-matching'
      path: '/mentor-matching'
      fullPath: '/groups/mentor-matching'
      preLoaderRoute: typeof AuthGroupsMentorMatchingRouteImport
      parentRoute: typeof AuthGroupsRouteRoute
    }
    '/_auth/groups/matched-groups': {
      id: '/_auth/groups/matched-groups'
      path: '/matched-groups'
      fullPath: '/groups/matched-groups'
      preLoaderRoute: typeof AuthGroupsMatchedGroupsRouteImport
      parentRoute: typeof AuthGroupsRouteRoute
    }
  }
}

interface AuthGroupsRouteRouteChildren {
  AuthGroupsMatchedGroupsRoute: typeof AuthGroupsMatchedGroupsRoute
  AuthGroupsMentorMatchingRoute: typeof AuthGroupsMentorMatchingRoute
  AuthGroupsStudentMatchingRoute: typeof AuthGroupsStudentMatchingRoute
  AuthGroupsIndexRoute: typeof AuthGroupsIndexRoute
}

const AuthGroupsRouteRouteChildren: AuthGroupsRouteRouteChildren = {
  AuthGroupsMatchedGroupsRoute: AuthGroupsMatchedGroupsRoute,
  AuthGroupsMentorMatchingRoute: AuthGroupsMentorMatchingRoute,
  AuthGroupsStudentMatchingRoute: AuthGroupsStudentMatchingRoute,
  AuthGroupsIndexRoute: AuthGroupsIndexRoute,
}

const AuthGroupsRouteRouteWithChildren = AuthGroupsRouteRoute._addFileChildren(
  AuthGroupsRouteRouteChildren,
)

interface AuthPeopleRouteRouteChildren {
  AuthPeopleMentorsRoute: typeof AuthPeopleMentorsRoute
  AuthPeopleStudentsRoute: typeof AuthPeopleStudentsRoute
  AuthPeopleSupervisorsRoute: typeof AuthPeopleSupervisorsRoute
  AuthPeopleIndexRoute: typeof AuthPeopleIndexRoute
}

const AuthPeopleRouteRouteChildren: AuthPeopleRouteRouteChildren = {
  AuthPeopleMentorsRoute: AuthPeopleMentorsRoute,
  AuthPeopleStudentsRoute: AuthPeopleStudentsRoute,
  AuthPeopleSupervisorsRoute: AuthPeopleSupervisorsRoute,
  AuthPeopleIndexRoute: AuthPeopleIndexRoute,
}

const AuthPeopleRouteRouteWithChildren = AuthPeopleRouteRoute._addFileChildren(
  AuthPeopleRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthGroupsRouteRoute: typeof AuthGroupsRouteRouteWithChildren
  AuthPeopleRouteRoute: typeof AuthPeopleRouteRouteWithChildren
  AuthAnnouncementRoute: typeof AuthAnnouncementRoute
  AuthEventRoute: typeof AuthEventRoute
  AuthGroupRoute: typeof AuthGroupRoute
  AuthMatchingRoute: typeof AuthMatchingRoute
  AuthMentorRoute: typeof AuthMentorRoute
  AuthMentorMatchingRoute: typeof AuthMentorMatchingRoute
  AuthResourceRoute: typeof AuthResourceRoute
  AuthStudentRoute: typeof AuthStudentRoute
  AuthTaskRoute: typeof AuthTaskRoute
  AuthUserRoute: typeof AuthUserRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthGroupsRouteRoute: AuthGroupsRouteRouteWithChildren,
  AuthPeopleRouteRoute: AuthPeopleRouteRouteWithChildren,
  AuthAnnouncementRoute: AuthAnnouncementRoute,
  AuthEventRoute: AuthEventRoute,
  AuthGroupRoute: AuthGroupRoute,
  AuthMatchingRoute: AuthMatchingRoute,
  AuthMentorRoute: AuthMentorRoute,
  AuthMentorMatchingRoute: AuthMentorMatchingRoute,
  AuthResourceRoute: AuthResourceRoute,
  AuthStudentRoute: AuthStudentRoute,
  AuthTaskRoute: AuthTaskRoute,
  AuthUserRoute: AuthUserRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SetupPasswordRoute: SetupPasswordRoute,
  SigninRoute: SigninRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
