# Generated by Django 5.2.5 on 2026-04-19 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("groups", "0002_initial"),
        ("resources", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Events",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("event_type", models.CharField(blank=True, max_length=100, null=True)),
                ("start_datetime", models.DateTimeField()),
                ("ends_datetime", models.DateTimeField()),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("humanitix_link", models.URLField(blank=True, max_length=255, null=True)),
                ("deleted_flag", models.BooleanField(default=False)),
                ("deleted_datetime", models.DateTimeField(blank=True, default=None, null=True)),
                ("event_image", models.CharField(blank=True, max_length=255, null=True)),
                ("is_virtual", models.BooleanField(default=False)),
                ("host_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ("track", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="groups.tracks")),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "db_table": "events",
                "ordering": ["start_datetime"],
            },
        ),
        migrations.CreateModel(
            name="EventRsvp",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("rsvp_status", models.CharField(choices=[("pending", "Pending"), ("going", "Going"), ("maybe", "Maybe"), ("declined", "Declined")], default="pending", max_length=50)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("event", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="rsvps", to="events.events")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Event RSVP",
                "verbose_name_plural": "Event RSVPs",
                "db_table": "event_rsvp",
            },
        ),
        migrations.CreateModel(
            name="EventTargetGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="events.events")),
                ("group", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="groups.groups")),
            ],
            options={
                "verbose_name": "Event Target Group",
                "verbose_name_plural": "Event Target Groups",
                "db_table": "event_target_group",
            },
        ),
        migrations.CreateModel(
            name="EventTargetRole",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="events.events")),
                ("role", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="resources.roles")),
            ],
            options={
                "verbose_name": "Event Target Role",
                "verbose_name_plural": "Event Target Roles",
                "db_table": "event_target_role",
            },
        ),
        migrations.CreateModel(
            name="EventTargetTrack",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="events.events")),
                ("track", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="groups.tracks")),
            ],
            options={
                "verbose_name": "Event Target Track",
                "verbose_name_plural": "Event Target Tracks",
                "db_table": "event_target_track",
            },
        ),
        migrations.AddIndex(
            model_name="events",
            index=models.Index(fields=["start_datetime"], name="events_start_d_2ddaa0_idx"),
        ),
        migrations.AddIndex(
            model_name="events",
            index=models.Index(fields=["host_user"], name="events_host_us_34c951_idx"),
        ),
        migrations.AddIndex(
            model_name="events",
            index=models.Index(fields=["track"], name="events_track_i_d7b306_idx"),
        ),
        migrations.AddConstraint(
            model_name="events",
            constraint=models.CheckConstraint(condition=models.Q(("ends_datetime__gt", models.F("start_datetime"))), name="check_event_end_after_start"),
        ),
        migrations.AddConstraint(
            model_name="events",
            constraint=models.CheckConstraint(condition=models.Q(("deleted_flag", False), models.Q(("deleted_flag", True), ("deleted_datetime__isnull", False)), _connector="OR"), name="check_deleted_flag_and_datetime"),
        ),
        migrations.AddConstraint(
            model_name="events",
            constraint=models.CheckConstraint(condition=models.Q(("is_virtual", False), ("location__isnull", True), _connector="OR"), name="check_virtual_location_null"),
        ),
        migrations.AddIndex(
            model_name="eventrsvp",
            index=models.Index(fields=["event"], name="event_rsvp_event_i_393d63_idx"),
        ),
        migrations.AddIndex(
            model_name="eventrsvp",
            index=models.Index(fields=["user"], name="event_rsvp_user_id_59b81e_idx"),
        ),
        migrations.AddIndex(
            model_name="eventrsvp",
            index=models.Index(fields=["rsvp_status"], name="event_rsvp_rsvp_st_80e8a8_idx"),
        ),
        migrations.AddConstraint(
            model_name="eventrsvp",
            constraint=models.UniqueConstraint(fields=("event", "user"), name="unique_event_rsvp_user"),
        ),
        migrations.AddConstraint(
            model_name="eventrsvp",
            constraint=models.CheckConstraint(condition=models.Q(("responded_at__isnull", True), ("rsvp_status__in", ["going", "maybe", "declined"]), _connector="OR"), name="event_rsvp_response_state_valid"),
        ),
        migrations.AddIndex(
            model_name="eventtargetgroup",
            index=models.Index(fields=["event"], name="event_targe_event_i_d53a84_idx"),
        ),
        migrations.AddIndex(
            model_name="eventtargetgroup",
            index=models.Index(fields=["group"], name="event_targe_group_i_29198c_idx"),
        ),
        migrations.AddConstraint(
            model_name="eventtargetgroup",
            constraint=models.UniqueConstraint(fields=("event", "group"), name="unique_event_group"),
        ),
        migrations.AddIndex(
            model_name="eventtargetrole",
            index=models.Index(fields=["event"], name="event_targe_event_i_bcd600_idx"),
        ),
        migrations.AddIndex(
            model_name="eventtargetrole",
            index=models.Index(fields=["role"], name="event_targe_role_id_6f7b73_idx"),
        ),
        migrations.AddConstraint(
            model_name="eventtargetrole",
            constraint=models.UniqueConstraint(fields=("event", "role"), name="unique_event_role"),
        ),
        migrations.AddIndex(
            model_name="eventtargettrack",
            index=models.Index(fields=["event"], name="event_targe_event_i_2f7445_idx"),
        ),
        migrations.AddIndex(
            model_name="eventtargettrack",
            index=models.Index(fields=["track"], name="event_targe_track_i_96c57e_idx"),
        ),
        migrations.AddConstraint(
            model_name="eventtargettrack",
            constraint=models.UniqueConstraint(fields=("event", "track"), name="unique_event_track"),
        ),
    ]
