# Generated by Django 5.2.5 on 2026-04-17 04:17

import django.db.models.deletion
import django.db.models.functions.datetime
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0002_initial'),
        ('resources', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_datetime', models.DateTimeField()),
                ('ends_datetime', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('humanitix_link', models.URLField(blank=True, max_length=255, null=True)),
                ('deleted_flag', models.BooleanField(default=False)),
                ('deleted_datetime', models.DateTimeField(blank=True, default=None, null=True)),
                ('event_image', models.CharField(blank=True, max_length=255, null=True)),
                ('is_virtual', models.BooleanField(default=False)),
                ('host_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'db_table': 'events',
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='EventInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('attendance_status', models.BooleanField(default=False)),
                ('rsvp_status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.events')),
            ],
            options={
                'verbose_name': 'Event Invite',
                'verbose_name_plural': 'Event Invites',
                'db_table': 'event_invite',
            },
        ),
        migrations.CreateModel(
            name='EventTargetGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.events')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.groups')),
            ],
            options={
                'verbose_name': 'Event Target Group',
                'verbose_name_plural': 'Event Target Groups',
                'db_table': 'event_target_group',
            },
        ),
        migrations.CreateModel(
            name='EventTargetRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.events')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.roles')),
            ],
            options={
                'verbose_name': 'Event Target Role',
                'verbose_name_plural': 'Event Target Roles',
                'db_table': 'event_target_role',
            },
        ),
        migrations.CreateModel(
            name='EventTargetTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.events')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.tracks')),
            ],
            options={
                'verbose_name': 'Event Target Track',
                'verbose_name_plural': 'Event Target Tracks',
                'db_table': 'event_target_track',
            },
        ),
        migrations.AddIndex(
            model_name='events',
            index=models.Index(fields=['start_datetime'], name='events_start_d_2ddaa0_idx'),
        ),
        migrations.AddIndex(
            model_name='events',
            index=models.Index(fields=['host_user'], name='events_host_us_34c951_idx'),
        ),
        migrations.AddConstraint(
            model_name='events',
            constraint=models.CheckConstraint(condition=models.Q(('ends_datetime__gt', models.F('start_datetime'))), name='check_event_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='events',
            constraint=models.CheckConstraint(condition=models.Q(('deleted_flag', False), models.Q(('deleted_flag', True), ('deleted_datetime__isnull', False)), _connector='OR'), name='check_deleted_flag_and_datetime'),
        ),
        migrations.AddConstraint(
            model_name='events',
            constraint=models.CheckConstraint(condition=models.Q(('is_virtual', False), ('location__isnull', True), _connector='OR'), name='check_virtual_location_null'),
        ),
        migrations.AddIndex(
            model_name='eventinvite',
            index=models.Index(fields=['event'], name='event_invit_event_i_c093b3_idx'),
        ),
        migrations.AddIndex(
            model_name='eventinvite',
            index=models.Index(fields=['user'], name='event_invit_user_id_db0358_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventinvite',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='unique_event_user'),
        ),
        migrations.AddConstraint(
            model_name='eventinvite',
            constraint=models.CheckConstraint(condition=models.Q(('attendance_status', False), ('rsvp_status', True), _connector='OR'), name='check_attendance_requires_rsvp'),
        ),
        migrations.AddConstraint(
            model_name='eventinvite',
            constraint=models.CheckConstraint(condition=models.Q(('sent_datetime__lte', django.db.models.functions.datetime.Now())), name='check_invite_sent_datetime_not_future'),
        ),
        migrations.AddIndex(
            model_name='eventtargetgroup',
            index=models.Index(fields=['event'], name='event_targe_event_i_d53a84_idx'),
        ),
        migrations.AddIndex(
            model_name='eventtargetgroup',
            index=models.Index(fields=['group'], name='event_targe_group_i_29198c_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventtargetgroup',
            constraint=models.UniqueConstraint(fields=('event', 'group'), name='unique_event_group'),
        ),
        migrations.AddIndex(
            model_name='eventtargetrole',
            index=models.Index(fields=['event'], name='event_targe_event_i_bcd600_idx'),
        ),
        migrations.AddIndex(
            model_name='eventtargetrole',
            index=models.Index(fields=['role'], name='event_targe_role_id_6f7b73_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventtargetrole',
            constraint=models.UniqueConstraint(fields=('event', 'role'), name='unique_event_role'),
        ),
        migrations.AddIndex(
            model_name='eventtargettrack',
            index=models.Index(fields=['event'], name='event_targe_event_i_2f7445_idx'),
        ),
        migrations.AddIndex(
            model_name='eventtargettrack',
            index=models.Index(fields=['track'], name='event_targe_track_i_96c57e_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventtargettrack',
            constraint=models.UniqueConstraint(fields=('event', 'track'), name='unique_event_track'),
        ),
    ]
