# Generated by Django 5.2.5 on 2026-04-20 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventRsvp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rsvp_status', models.CharField(choices=[('pending', 'Pending'), ('going', 'Going'), ('maybe', 'Maybe'), ('declined', 'Declined')], default='pending', max_length=50)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Event RSVP',
                'verbose_name_plural': 'Event RSVPs',
                'db_table': 'event_rsvp',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('event_type', models.CharField(blank=True, choices=[('workshop', 'Workshop'), ('webinar', 'Webinar'), ('symposium', 'Symposium'), ('networking', 'Networking'), ('social', 'Social'), ('other', 'Other')], max_length=100, null=True)),
                ('start_datetime', models.DateTimeField()),
                ('ends_datetime', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('humanitix_link', models.URLField(blank=True, max_length=255, null=True)),
                ('deleted_flag', models.BooleanField(default=False)),
                ('deleted_datetime', models.DateTimeField(blank=True, default=None, null=True)),
                ('event_image', models.CharField(blank=True, max_length=255, null=True)),
                ('is_virtual', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'db_table': 'events',
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='EventTargetGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Event Target Group',
                'verbose_name_plural': 'Event Target Groups',
                'db_table': 'event_target_group',
            },
        ),
        migrations.CreateModel(
            name='EventTargetRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Event Target Role',
                'verbose_name_plural': 'Event Target Roles',
                'db_table': 'event_target_role',
            },
        ),
        migrations.CreateModel(
            name='EventTargetTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Event Target Track',
                'verbose_name_plural': 'Event Target Tracks',
                'db_table': 'event_target_track',
            },
        ),
    ]
