# Generated by Django 5.2.5 on 2026-04-20 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('groups', '0001_initial'),
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrsvp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='events',
            name='host_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='events',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.tracks'),
        ),
        migrations.AddField(
            model_name='eventrsvp',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='events.events'),
        ),
        migrations.AddField(
            model_name='eventtargetgroup',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.events'),
        ),
        migrations.AddField(
            model_name='eventtargetgroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.groups'),
        ),
        migrations.AddField(
            model_name='eventtargetrole',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.events'),
        ),
        migrations.AddField(
            model_name='eventtargetrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.roles'),
        ),
        migrations.AddField(
            model_name='eventtargettrack',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.events'),
        ),
        migrations.AddField(
            model_name='eventtargettrack',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.tracks'),
        ),
        migrations.AddIndex(
            model_name='events',
            index=models.Index(fields=['start_datetime'], name='events_start_d_2ddaa0_idx'),
        ),
        migrations.AddIndex(
            model_name='events',
            index=models.Index(fields=['host_user'], name='events_host_us_34c951_idx'),
        ),
        migrations.AddIndex(
            model_name='events',
            index=models.Index(fields=['track'], name='events_track_i_d7b306_idx'),
        ),
        migrations.AddConstraint(
            model_name='events',
            constraint=models.CheckConstraint(condition=models.Q(('ends_datetime__gt', models.F('start_datetime'))), name='check_event_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='events',
            constraint=models.CheckConstraint(condition=models.Q(('deleted_flag', False), models.Q(('deleted_flag', True), ('deleted_datetime__isnull', False)), _connector='OR'), name='check_deleted_flag_and_datetime'),
        ),
        migrations.AddConstraint(
            model_name='events',
            constraint=models.CheckConstraint(condition=models.Q(('is_virtual', False), ('location__isnull', True), _connector='OR'), name='check_virtual_location_null'),
        ),
        migrations.AddIndex(
            model_name='eventrsvp',
            index=models.Index(fields=['event'], name='event_rsvp_event_i_393d63_idx'),
        ),
        migrations.AddIndex(
            model_name='eventrsvp',
            index=models.Index(fields=['user'], name='event_rsvp_user_id_59b81e_idx'),
        ),
        migrations.AddIndex(
            model_name='eventrsvp',
            index=models.Index(fields=['rsvp_status'], name='event_rsvp_rsvp_st_80e8a8_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventrsvp',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='unique_event_rsvp_user'),
        ),
        migrations.AddConstraint(
            model_name='eventrsvp',
            constraint=models.CheckConstraint(condition=models.Q(('responded_at__isnull', True), ('rsvp_status__in', ['going', 'maybe', 'declined']), _connector='OR'), name='event_rsvp_response_state_valid'),
        ),
        migrations.AddIndex(
            model_name='eventtargetgroup',
            index=models.Index(fields=['event'], name='event_targe_event_i_d53a84_idx'),
        ),
        migrations.AddIndex(
            model_name='eventtargetgroup',
            index=models.Index(fields=['group'], name='event_targe_group_i_29198c_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventtargetgroup',
            constraint=models.UniqueConstraint(fields=('event', 'group'), name='unique_event_group'),
        ),
        migrations.AddIndex(
            model_name='eventtargetrole',
            index=models.Index(fields=['event'], name='event_targe_event_i_bcd600_idx'),
        ),
        migrations.AddIndex(
            model_name='eventtargetrole',
            index=models.Index(fields=['role'], name='event_targe_role_id_6f7b73_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventtargetrole',
            constraint=models.UniqueConstraint(fields=('event', 'role'), name='unique_event_role'),
        ),
        migrations.AddIndex(
            model_name='eventtargettrack',
            index=models.Index(fields=['event'], name='event_targe_event_i_2f7445_idx'),
        ),
        migrations.AddIndex(
            model_name='eventtargettrack',
            index=models.Index(fields=['track'], name='event_targe_track_i_96c57e_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventtargettrack',
            constraint=models.UniqueConstraint(fields=('event', 'track'), name='unique_event_track'),
        ),
    ]
