# Generated by Django 6.0.4 on 2026-04-28 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='events',
            name='check_deleted_flag_and_datetime',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='deleted_datetime',
            new_name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='events',
            name='deleted_flag',
        ),
    ]
