# Generated by Django 6.0.4 on 2026-05-03 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_events_check_deleted_flag_and_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='humanitix_link',
        ),
    ]
