# Generated by Django 5.2.5 on 2026-05-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_events_humanitix_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='location_link',
            field=models.URLField(blank=True, help_text='Zoom URL when is_virtual=True, Google Maps URL otherwise.', max_length=255, null=True),
        ),
    ]
