# Generated by Django 5.2.5 on 2026-05-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_events_location_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
