# Generated by Django 5.2.5 on 2026-05-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_rsvp_standard_wording"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="rsvp_reminder_sent_for_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]

