# Generated by Django 5.2.5 on 2026-05-12 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_events_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='reminder_1h_sent',
            field=models.BooleanField(default=False),
        ),
    ]
