# Generated by Django 5.2.5 on 2026-05-12 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_events_reminder_sent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='reminder_sent',
            new_name='reminder_1h_sent',
        ),
    ]
