# Generated by Django 5.2.5 on 2026-05-14 07:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_rsvp_reminder_kind_split'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='eventrsvp',
            name='event_rsvp_response_state_valid',
        ),
        migrations.AddField(
            model_name='events',
            name='max_attendees',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventrsvp',
            name='rsvp_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('tentative', 'Tentative'), ('declined', 'Declined'), ('waitlisted', 'Waitlisted')], default='pending', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='eventrsvp',
            constraint=models.CheckConstraint(condition=models.Q(('responded_at__isnull', True), ('rsvp_status__in', ['accepted', 'tentative', 'declined', 'waitlisted']), _connector='OR'), name='event_rsvp_response_state_valid'),
        ),
    ]
