# Generated by Django 5.2.5 on 2026-05-14 10:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_remove_eventrsvp_event_rsvp_response_state_valid_and_more'),
        ('groups', '0003_alter_groupmembership_membership_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='eventrsvp',
            index=models.Index(fields=['event', 'rsvp_status', 'responded_at'], name='evrsvp_evt_stat_resp_idx'),
        ),
        migrations.AddIndex(
            model_name='events',
            index=models.Index(fields=['ends_datetime'], name='events_ends_da_e8ed47_idx'),
        ),
    ]
