# Generated by Django 5.2.5 on 2026-05-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_events_timezone_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='location_link',
            field=models.URLField(blank=True, help_text='Zoom URL for virtual/hybrid events, Google Maps URL for in-person events.', max_length=255, null=True),
        ),
    ]
