# Generated by Django 5.2.5 on 2026-07-07 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_event_format_location_check'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='events',
            name='events_track_i_d7b306_idx',
        ),
        migrations.RemoveField(
            model_name='events',
            name='track',
        ),
        # Drop the join table wholesale. Removing its FK fields individually
        # trips SQLite's table-remake over the stale unique_event_track
        # constraint, so delete the model directly.
        migrations.DeleteModel(
            name='EventTargetTrack',
        ),
    ]
