# Generated by Django 5.2.5 on 2026-08-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_normalize_event_image_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_type',
            field=models.CharField(blank=True, choices=[('workshop', 'Workshop'), ('webinar', 'Webinar'), ('symposium', 'Symposium'), ('networking', 'Networking'), ('social', 'Social'), ('group_meeting', 'Group Meeting'), ('other', 'Other')], max_length=100, null=True),
        ),
    ]
