CREATE SCHEMA "admin";
--> statement-breakpoint
CREATE TABLE "admin"."account" (
	"id" text PRIMARY KEY NOT NULL,
	"account_id" text NOT NULL,
	"provider_id" text NOT NULL,
	"user_id" text NOT NULL,
	"access_token" text,
	"refresh_token" text,
	"id_token" text,
	"access_token_expires_at" timestamp,
	"refresh_token_expires_at" timestamp,
	"scope" text,
	"password" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "admin"."session" (
	"id" text PRIMARY KEY NOT NULL,
	"expires_at" timestamp NOT NULL,
	"token" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp NOT NULL,
	"ip_address" text,
	"user_agent" text,
	"user_id" text NOT NULL,
	"impersonated_by" text,
	CONSTRAINT "session_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE "admin"."user" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"email" text NOT NULL,
	"email_verified" boolean DEFAULT false NOT NULL,
	"image" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"role" text,
	"banned" boolean DEFAULT false,
	"ban_reason" text,
	"ban_expires" timestamp,
	"user_id" bigint NOT NULL,
	CONSTRAINT "user_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "admin"."verification" (
	"id" text PRIMARY KEY NOT NULL,
	"identifier" text NOT NULL,
	"value" text NOT NULL,
	"expires_at" timestamp NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "admin"."match_run" (
	"id" serial PRIMARY KEY NOT NULL,
	"admin_user_id" text NOT NULL,
	"run_type" varchar(100) NOT NULL,
	"payload" jsonb NOT NULL,
	"created_at" timestamp(6) NOT NULL,
	"result" jsonb NOT NULL
);
--> statement-breakpoint
CREATE TABLE "admin_profile" (
	"admin_id" bigint PRIMARY KEY NOT NULL
);
--> statement-breakpoint
CREATE TABLE "alerts" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "alerts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"alert_timestamp" timestamp with time zone NOT NULL,
	"error_reason" varchar(255) NOT NULL,
	"resolved" boolean NOT NULL,
	"session_id" bigint NOT NULL,
	CONSTRAINT "unique_alert_user_session" UNIQUE("alert_timestamp","error_reason","session_id"),
	CONSTRAINT "alert_reason_not_empty" CHECK (NOT ((error_reason)::text = ''::text))
);
--> statement-breakpoint
CREATE TABLE "areas_of_interest" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "areas_of_interest_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"interest_desc" varchar(255) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "auth_group" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "auth_group_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(150) NOT NULL,
	CONSTRAINT "auth_group_name_key" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "auth_group_permissions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "auth_group_permissions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"group_id" integer NOT NULL,
	"permission_id" integer NOT NULL,
	CONSTRAINT "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" UNIQUE("group_id","permission_id")
);
--> statement-breakpoint
CREATE TABLE "auth_permission" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "auth_permission_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"content_type_id" integer NOT NULL,
	"codename" varchar(100) NOT NULL,
	CONSTRAINT "auth_permission_content_type_id_codename_01ab375a_uniq" UNIQUE("content_type_id","codename")
);
--> statement-breakpoint
CREATE TABLE "background" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "background_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"background_desc_unique_field" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "certificate_type" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "certificate_type_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"certificate_type" varchar(255) NOT NULL,
	"requires_number" boolean NOT NULL,
	"requires_expiry" boolean NOT NULL,
	CONSTRAINT "certificate_type_certificate_type_key" UNIQUE("certificate_type")
);
--> statement-breakpoint
CREATE TABLE "countries" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "countries_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"country_name" varchar(255) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "country_states" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "country_states_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"state_name" varchar(255) NOT NULL,
	"country_id" bigint NOT NULL,
	CONSTRAINT "unique_state_per_country" UNIQUE("state_name","country_id")
);
--> statement-breakpoint
CREATE TABLE "django_admin_log" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "django_admin_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"action_time" timestamp with time zone NOT NULL,
	"object_id" text,
	"object_repr" varchar(200) NOT NULL,
	"action_flag" smallint NOT NULL,
	"change_message" text NOT NULL,
	"content_type_id" integer,
	"user_id" bigint NOT NULL,
	CONSTRAINT "django_admin_log_action_flag_check" CHECK (action_flag >= 0)
);
--> statement-breakpoint
CREATE TABLE "django_content_type" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "django_content_type_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"app_label" varchar(100) NOT NULL,
	"model" varchar(100) NOT NULL,
	CONSTRAINT "django_content_type_app_label_model_76bd3d3b_uniq" UNIQUE("app_label","model")
);
--> statement-breakpoint
CREATE TABLE "django_migrations" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "django_migrations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"app" varchar(255) NOT NULL,
	"name" varchar(255) NOT NULL,
	"applied" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "django_session" (
	"session_key" varchar(40) PRIMARY KEY NOT NULL,
	"session_data" text NOT NULL,
	"expire_date" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "event_invite" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "event_invite_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"sent_datetime" timestamp with time zone NOT NULL,
	"attendance_status" boolean NOT NULL,
	"rsvp_status" boolean NOT NULL,
	"user_id" bigint NOT NULL,
	"event_id" bigint NOT NULL,
	CONSTRAINT "unique_event_user" UNIQUE("user_id","event_id"),
	CONSTRAINT "check_attendance_requires_rsvp" CHECK ((NOT attendance_status) OR rsvp_status),
	CONSTRAINT "check_invite_sent_datetime_not_future" CHECK (sent_datetime <= statement_timestamp())
);
--> statement-breakpoint
CREATE TABLE "event_target_group" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "event_target_group_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"event_id" bigint NOT NULL,
	"group_id" bigint NOT NULL,
	CONSTRAINT "unique_event_group" UNIQUE("event_id","group_id")
);
--> statement-breakpoint
CREATE TABLE "event_target_role" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "event_target_role_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"event_id" bigint NOT NULL,
	"role_id" bigint NOT NULL,
	CONSTRAINT "unique_event_role" UNIQUE("event_id","role_id")
);
--> statement-breakpoint
CREATE TABLE "event_target_track" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "event_target_track_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"event_id" bigint NOT NULL,
	"track_id" bigint NOT NULL,
	CONSTRAINT "unique_event_track" UNIQUE("event_id","track_id")
);
--> statement-breakpoint
CREATE TABLE "events" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "events_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"event_name" varchar(255) NOT NULL,
	"description" varchar(255),
	"start_datetime" timestamp with time zone NOT NULL,
	"ends_datetime" timestamp with time zone NOT NULL,
	"location" varchar(255),
	"humanitix_link" varchar(255) NOT NULL,
	"deleted_flag" boolean NOT NULL,
	"deleted_datetime" timestamp with time zone,
	"event_image(IMG)" varchar(255),
	"is_virtual" boolean NOT NULL,
	"host_user_id" bigint,
	CONSTRAINT "check_deleted_flag_and_datetime" CHECK ((NOT deleted_flag) OR (deleted_flag AND (deleted_datetime IS NOT NULL))),
	CONSTRAINT "check_event_end_after_start" CHECK (ends_datetime > start_datetime),
	CONSTRAINT "check_virtual_location_null" CHECK ((NOT is_virtual) OR (location IS NULL))
);
--> statement-breakpoint
CREATE TABLE "group_members" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "group_members_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" bigint NOT NULL,
	"group_id" bigint NOT NULL,
	CONSTRAINT "unique_group_user" UNIQUE("user_id","group_id")
);
--> statement-breakpoint
CREATE TABLE "groups" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "groups_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"group_name" varchar(255) NOT NULL,
	"creation_datetime" timestamp with time zone NOT NULL,
	"deleted_flag" boolean NOT NULL,
	"deleted_datetime" timestamp with time zone,
	"track_id" bigint NOT NULL,
	CONSTRAINT "unique_group_name_per_track" UNIQUE("group_name","track_id"),
	CONSTRAINT "deleted_after_creation" CHECK ((deleted_datetime >= creation_datetime) OR (deleted_datetime IS NULL)),
	CONSTRAINT "group_creation_not_future" CHECK (creation_datetime <= statement_timestamp()),
	CONSTRAINT "group_deleted_flag_datetime_consistent" CHECK ((deleted_flag AND (deleted_datetime IS NOT NULL)) OR ((NOT deleted_flag) AND (deleted_datetime IS NULL))),
	CONSTRAINT "group_name_not_empty" CHECK (NOT ((group_name)::text ~ '^s*$'::text))
);
--> statement-breakpoint
CREATE TABLE "login_tokens" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "login_tokens_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"token" varchar(6) NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"used" boolean NOT NULL,
	"user_id" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "mentor_certificate" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "mentor_certificate_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"certificate_number" varchar(255),
	"issued_by" varchar(255) NOT NULL,
	"issued_at" date NOT NULL,
	"expires_at" date,
	"file_url" varchar(500),
	"verified" boolean NOT NULL,
	"certificate_type_id" bigint NOT NULL,
	"mentor_profile_id" bigint NOT NULL,
	CONSTRAINT "unique_certificate_per_mentor" UNIQUE("certificate_number","certificate_type_id","mentor_profile_id"),
	CONSTRAINT "cannot_verify_expired_certificate" CHECK ((expires_at IS NULL) OR (expires_at >= statement_timestamp()) OR (NOT verified))
);
--> statement-breakpoint
CREATE TABLE "mentor_profile" (
	"user_id" bigint PRIMARY KEY NOT NULL,
	"Institution" varchar(255) NOT NULL,
	"mentor_reason" varchar(255) NOT NULL,
	"max_grp_cnt" integer NOT NULL,
	"background_id" bigint NOT NULL,
	CONSTRAINT "mentor_max_grp_non_negative" CHECK (max_grp_cnt >= 0)
);
--> statement-breakpoint
CREATE TABLE "message_attachments" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "message_attachments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"attachment_id" varchar(255) NOT NULL,
	"attachment_filename" varchar(255) NOT NULL,
	"message_id" bigint NOT NULL,
	CONSTRAINT "message_attachments_attachment_id_key" UNIQUE("attachment_id"),
	CONSTRAINT "unique_filename_per_message" UNIQUE("attachment_filename","message_id")
);
--> statement-breakpoint
CREATE TABLE "message_resources" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "message_resources_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"message_id" bigint NOT NULL,
	"resource_id" bigint NOT NULL,
	CONSTRAINT "message_resources_message_id_resource_id_9a04fab7_uniq" UNIQUE("message_id","resource_id")
);
--> statement-breakpoint
CREATE TABLE "message_status" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "message_status_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"status" varchar(20) NOT NULL,
	"delivered_at" timestamp with time zone,
	"read_at" timestamp with time zone,
	"message_id" bigint NOT NULL,
	"user_id" bigint NOT NULL,
	CONSTRAINT "message_status_message_id_user_id_e0eb32f9_uniq" UNIQUE("message_id","user_id")
);
--> statement-breakpoint
CREATE TABLE "messages" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "messages_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"message_text" text NOT NULL,
	"sent_at" timestamp with time zone NOT NULL,
	"group_id" bigint NOT NULL,
	"sender_user_id" bigint NOT NULL,
	"edited_at" timestamp with time zone,
	"deleted_at" timestamp with time zone,
	"message_type" varchar(20) NOT NULL,
	CONSTRAINT "message_deleted_after_sent" CHECK ((deleted_at IS NULL) OR (deleted_at >= sent_at)),
	CONSTRAINT "message_edited_after_sent" CHECK ((edited_at IS NULL) OR (edited_at >= sent_at))
);
--> statement-breakpoint
CREATE TABLE "milestone" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "milestone_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"milestone_name" varchar(255) NOT NULL,
	"completed" boolean NOT NULL,
	"deleted_flag" boolean NOT NULL,
	"group_id" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "relationship_type" (
	"relationship_type_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "relationship_type_relationship_type_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"relationship_type" varchar(255) NOT NULL,
	CONSTRAINT "relationship_type_relationship_type_key" UNIQUE("relationship_type")
);
--> statement-breakpoint
CREATE TABLE "resource_roles" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "resource_roles_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"resource_id" bigint NOT NULL,
	"role_id" bigint NOT NULL,
	CONSTRAINT "pk_resource_role" UNIQUE("resource_id","role_id")
);
--> statement-breakpoint
CREATE TABLE "resource_types" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "resource_types_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"type_name" varchar(50) NOT NULL,
	"type_description" varchar(255),
	CONSTRAINT "resource_types_type_name_key" UNIQUE("type_name")
);
--> statement-breakpoint
CREATE TABLE "resources" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "resources_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"resource_name" varchar(255) NOT NULL,
	"resource_description" varchar(255) NOT NULL,
	"upload_datetime" timestamp with time zone NOT NULL,
	"deleted_flag" boolean NOT NULL,
	"deleted_datetime" timestamp with time zone,
	"uploader_user_id_id" bigint NOT NULL,
	"resource_type_id" bigint,
	CONSTRAINT "deleted_after_upload" CHECK ((deleted_datetime >= upload_datetime) OR (deleted_datetime IS NULL)),
	CONSTRAINT "deleted_flag_true_if_deleted_datetime" CHECK ((deleted_datetime IS NULL) OR deleted_flag),
	CONSTRAINT "resource_description_not_empty" CHECK (NOT ((resource_description)::text = ''::text)),
	CONSTRAINT "resource_upload_not_future" CHECK (upload_datetime <= statement_timestamp())
);
--> statement-breakpoint
CREATE TABLE "role_assignment_history" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "role_assignment_history_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"valid_from" timestamp with time zone NOT NULL,
	"valid_to" timestamp with time zone,
	"user_id" bigint,
	"role_id" bigint,
	CONSTRAINT "unique_user_role_start" UNIQUE("valid_from","user_id","role_id"),
	CONSTRAINT "valid_to_after_valid_from" CHECK (valid_to >= valid_from)
);
--> statement-breakpoint
CREATE TABLE "roles" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "roles_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"role_name" varchar(255) NOT NULL,
	CONSTRAINT "roles_role_name_key" UNIQUE("role_name"),
	CONSTRAINT "role_name_not_empty" CHECK (NOT ((role_name)::text = ''::text))
);
--> statement-breakpoint
CREATE TABLE "sessions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sessions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"access_datetime" timestamp with time zone NOT NULL,
	"isLoggedin" boolean NOT NULL,
	"user_id" bigint NOT NULL,
	CONSTRAINT "unique_user_session" UNIQUE("access_datetime","user_id"),
	CONSTRAINT "access_not_in_future" CHECK (access_datetime <= statement_timestamp())
);
--> statement-breakpoint
CREATE TABLE "student_interest" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "student_interest_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"interest_id" bigint NOT NULL,
	"user_id" bigint NOT NULL,
	CONSTRAINT "pk_student_interest" UNIQUE("interest_id","user_id")
);
--> statement-breakpoint
CREATE TABLE "student_profile" (
	"user_id" bigint PRIMARY KEY NOT NULL,
	"pg_first_name" varchar(255) NOT NULL,
	"pg_last_name" varchar(255) NOT NULL,
	"parent_guardian_flag" boolean NOT NULL,
	"school_name" varchar(255) NOT NULL,
	"year_lvl" varchar(255) NOT NULL,
	"has_join_permission" boolean NOT NULL,
	"interest_id" bigint,
	"supervisor_id" bigint,
	"joinperm_responseID" varchar(255),
	CONSTRAINT "permission_requires_parent_guardian" CHECK ((NOT has_join_permission) OR parent_guardian_flag),
	CONSTRAINT "student_first_name_not_empty" CHECK (NOT ((pg_first_name)::text = ''::text)),
	CONSTRAINT "student_last_name_not_empty" CHECK (NOT ((pg_last_name)::text = ''::text)),
	CONSTRAINT "student_school_name_not_empty" CHECK (NOT ((school_name)::text = ''::text)),
	CONSTRAINT "student_year_lvl_valid" CHECK ((year_lvl)::text = ANY ((ARRAY['9'::character varying, '10'::character varying, '11'::character varying, '12'::character varying])::text[]))
);
--> statement-breakpoint
CREATE TABLE "student_supervisor" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "student_supervisor_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"relationship_type_id" bigint NOT NULL,
	"student_user_id" bigint NOT NULL,
	"supervisor_user_id" bigint,
	CONSTRAINT "pk_student_supervisor" UNIQUE("student_user_id","supervisor_user_id"),
	CONSTRAINT "no_self_supervision" CHECK ((supervisor_user_id IS NULL) OR (NOT ((student_user_id = supervisor_user_id) AND (supervisor_user_id IS NOT NULL)))),
	CONSTRAINT "relationship_type_not_null" CHECK (NOT (relationship_type_id IS NULL)),
	CONSTRAINT "student_user_not_null" CHECK (NOT (student_user_id IS NULL))
);
--> statement-breakpoint
CREATE TABLE "supervisor_profile" (
	"user_id" bigint PRIMARY KEY NOT NULL,
	"school_name" varchar(255) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "task_assignees" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "task_assignees_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"assigned_datetime" timestamp with time zone NOT NULL,
	"deleted_flag" boolean NOT NULL,
	"user_id" bigint NOT NULL,
	"task_id" bigint NOT NULL,
	CONSTRAINT "unique_task_user" UNIQUE("user_id","task_id")
);
--> statement-breakpoint
CREATE TABLE "tasks" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tasks_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"task_name" varchar(255) NOT NULL,
	"due_date" timestamp with time zone NOT NULL,
	"deleted_flag" boolean NOT NULL,
	"task_description" varchar(255),
	"milestone_id" bigint
);
--> statement-breakpoint
CREATE TABLE "tracks" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tracks_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"track_name" varchar(255) NOT NULL,
	"state_id" bigint NOT NULL,
	CONSTRAINT "tracks_track_name_key" UNIQUE("track_name")
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"password" varchar(128) NOT NULL,
	"last_login" timestamp with time zone,
	"is_superuser" boolean NOT NULL,
	"first_name" varchar(255) NOT NULL,
	"last_name" varchar(255) NOT NULL,
	"is_staff" boolean NOT NULL,
	"is_active" boolean NOT NULL,
	"date_joined" timestamp with time zone NOT NULL,
	"email" varchar(254) NOT NULL,
	"status" boolean NOT NULL,
	"state_id" bigint,
	"track_id" bigint,
	CONSTRAINT "users_email_key" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "users_groups" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_groups_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" bigint NOT NULL,
	"group_id" integer NOT NULL,
	CONSTRAINT "users_groups_user_id_group_id_fc7788e8_uniq" UNIQUE("user_id","group_id")
);
--> statement-breakpoint
CREATE TABLE "users_user_permissions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_user_permissions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" bigint NOT NULL,
	"permission_id" integer NOT NULL,
	CONSTRAINT "users_user_permissions_user_id_permission_id_3b86cbdf_uniq" UNIQUE("user_id","permission_id")
);
--> statement-breakpoint
CREATE TABLE "workshop_attendance" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "workshop_attendance_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"responded" boolean NOT NULL,
	"user_id" bigint NOT NULL,
	"workshop_id" bigint NOT NULL,
	CONSTRAINT "pk_workshop_attendance" UNIQUE("user_id","workshop_id")
);
--> statement-breakpoint
CREATE TABLE "workshops" (
	"workshop_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "workshops_workshop_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"workshop_name" varchar(255) NOT NULL,
	"start_datetime" timestamp with time zone NOT NULL,
	"duration" interval NOT NULL,
	"location" varchar(255) NOT NULL,
	"description" varchar(255),
	"zoom_link" varchar(255),
	"deleted_flag" boolean NOT NULL,
	"deleted_datetime" timestamp with time zone,
	"group_id" bigint NOT NULL,
	"host_user_id" bigint NOT NULL
);
--> statement-breakpoint
ALTER TABLE "admin"."account" ADD CONSTRAINT "account_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "admin"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "admin"."session" ADD CONSTRAINT "session_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "admin"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "admin"."user" ADD CONSTRAINT "user_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "admin"."match_run" ADD CONSTRAINT "match_run_initiated_by_user_id_fkey" FOREIGN KEY ("admin_user_id") REFERENCES "admin"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "admin_profile" ADD CONSTRAINT "admin_profile_admin_id_d55c5f00_fk_users_id" FOREIGN KEY ("admin_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "alerts" ADD CONSTRAINT "alerts_session_id_286fb9cc_fk_sessions_id" FOREIGN KEY ("session_id") REFERENCES "public"."sessions"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissio_permission_id_84c5c92e_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "public"."auth_permission"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissions_group_id_b120cbf9_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "public"."auth_group"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth_permission" ADD CONSTRAINT "auth_permission_content_type_id_2f476e4b_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "public"."django_content_type"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "country_states" ADD CONSTRAINT "country_states_country_id_c84f5fb5_fk_countries_id" FOREIGN KEY ("country_id") REFERENCES "public"."countries"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "django_admin_log" ADD CONSTRAINT "django_admin_log_content_type_id_c4bce8eb_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "public"."django_content_type"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "django_admin_log" ADD CONSTRAINT "django_admin_log_user_id_c564eba6_fk_users_id" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "event_invite" ADD CONSTRAINT "event_invite_event_id_d0229d7f_fk_events_id" FOREIGN KEY ("event_id") REFERENCES "public"."events"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "event_invite" ADD CONSTRAINT "event_invite_user_id_5c26a2a6_fk_users_id" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "event_target_group" ADD CONSTRAINT "event_target_group_event_id_3102faf9_fk_events_id" FOREIGN KEY ("event_id") REFERENCES "public"."events"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "event_target_group" ADD CONSTRAINT "event_target_group_group_id_9b0af69c_fk_groups_id" FOREIGN KEY ("group_id") REFERENCES "public"."groups"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "event_target_role" ADD CONSTRAINT "event_target_role_event_id_62145d19_fk_events_id" FOREIGN KEY ("event_id") REFERENCES "public"."events"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "event_target_role" ADD CONSTRAINT "event_target_role_role_id_f7baea72_fk_roles_id" FOREIGN KEY ("role_id") REFERENCES "public"."roles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "event_target_track" ADD CONSTRAINT "event_target_track_event_id_d4858886_fk_events_id" FOREIGN KEY ("event_id") REFERENCES "public"."events"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "event_target_track" ADD CONSTRAINT "event_target_track_track_id_1163cca1_fk_tracks_id" FOREIGN KEY ("track_id") REFERENCES "public"."tracks"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "events" ADD CONSTRAINT "events_host_user_id_f7fc239c_fk_users_id" FOREIGN KEY ("host_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "group_members" ADD CONSTRAINT "group_members_group_id_68d06a36_fk_groups_id" FOREIGN KEY ("group_id") REFERENCES "public"."groups"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "group_members" ADD CONSTRAINT "group_members_user_id_cffc0595_fk_users_id" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "groups" ADD CONSTRAINT "groups_track_id_f29fde9a_fk_tracks_id" FOREIGN KEY ("track_id") REFERENCES "public"."tracks"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "login_tokens" ADD CONSTRAINT "login_tokens_user_id_7f12777f_fk_users_id" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "mentor_certificate" ADD CONSTRAINT "mentor_certificate_certificate_type_id_090af26f_fk_certifica" FOREIGN KEY ("certificate_type_id") REFERENCES "public"."certificate_type"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "mentor_certificate" ADD CONSTRAINT "mentor_certificate_mentor_profile_id_61bbc118_fk_mentor_pr" FOREIGN KEY ("mentor_profile_id") REFERENCES "public"."mentor_profile"("user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "mentor_profile" ADD CONSTRAINT "mentor_profile_background_id_000edd98_fk_background_id" FOREIGN KEY ("background_id") REFERENCES "public"."background"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "mentor_profile" ADD CONSTRAINT "mentor_profile_user_id_a4034c13_fk_users_id" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "message_attachments" ADD CONSTRAINT "message_attachments_message_id_c7a3e22d_fk_messages_id" FOREIGN KEY ("message_id") REFERENCES "public"."messages"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "message_resources" ADD CONSTRAINT "message_resources_message_id_e0b74b54_fk_messages_id" FOREIGN KEY ("message_id") REFERENCES "public"."messages"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "message_resources" ADD CONSTRAINT "message_resources_resource_id_7bf8fbc9_fk_resources_id" FOREIGN KEY ("resource_id") REFERENCES "public"."resources"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "message_status" ADD CONSTRAINT "message_status_message_id_7d8e74e7_fk_messages_id" FOREIGN KEY ("message_id") REFERENCES "public"."messages"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "message_status" ADD CONSTRAINT "message_status_user_id_0673798e_fk_users_id" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "messages" ADD CONSTRAINT "messages_group_id_0fd96228_fk_groups_id" FOREIGN KEY ("group_id") REFERENCES "public"."groups"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "messages" ADD CONSTRAINT "messages_sender_user_id_b1b10099_fk_users_id" FOREIGN KEY ("sender_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "milestone" ADD CONSTRAINT "milestone_group_id_11a6a79d_fk_groups_id" FOREIGN KEY ("group_id") REFERENCES "public"."groups"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "resource_roles" ADD CONSTRAINT "resource_roles_resource_id_158c512b_fk_resources_id" FOREIGN KEY ("resource_id") REFERENCES "public"."resources"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "resource_roles" ADD CONSTRAINT "resource_roles_role_id_5ce2ab8a_fk_roles_id" FOREIGN KEY ("role_id") REFERENCES "public"."roles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "resources" ADD CONSTRAINT "resources_resource_type_id_8ca31a8a_fk_resource_types_id" FOREIGN KEY ("resource_type_id") REFERENCES "public"."resource_types"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "resources" ADD CONSTRAINT "resources_uploader_user_id_id_f9418bc1_fk_users_id" FOREIGN KEY ("uploader_user_id_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "role_assignment_history" ADD CONSTRAINT "role_assignment_history_role_id_807250dc_fk_roles_id" FOREIGN KEY ("role_id") REFERENCES "public"."roles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "role_assignment_history" ADD CONSTRAINT "role_assignment_history_user_id_1b78a336_fk_users_id" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_user_id_05e26f4a_fk_users_id" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "student_interest" ADD CONSTRAINT "student_interest_interest_id_7f538900_fk_areas_of_interest_id" FOREIGN KEY ("interest_id") REFERENCES "public"."areas_of_interest"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "student_interest" ADD CONSTRAINT "student_interest_user_id_a32699eb_fk_users_id" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "student_profile" ADD CONSTRAINT "student_profile_interest_id_fe594703_fk_areas_of_interest_id" FOREIGN KEY ("interest_id") REFERENCES "public"."areas_of_interest"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "student_profile" ADD CONSTRAINT "student_profile_supervisor_id_4bc6991c_fk_superviso" FOREIGN KEY ("supervisor_id") REFERENCES "public"."supervisor_profile"("user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "student_profile" ADD CONSTRAINT "student_profile_user_id_15556aa0_fk_users_id" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "student_supervisor" ADD CONSTRAINT "student_supervisor_relationship_type_id_18e3edd0_fk_relations" FOREIGN KEY ("relationship_type_id") REFERENCES "public"."relationship_type"("relationship_type_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "student_supervisor" ADD CONSTRAINT "student_supervisor_student_user_id_fb056317_fk_student_p" FOREIGN KEY ("student_user_id") REFERENCES "public"."student_profile"("user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "student_supervisor" ADD CONSTRAINT "student_supervisor_supervisor_user_id_8a5fb4d1_fk_superviso" FOREIGN KEY ("supervisor_user_id") REFERENCES "public"."supervisor_profile"("user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "supervisor_profile" ADD CONSTRAINT "supervisor_profile_user_id_40ae74c6_fk_users_id" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "task_assignees" ADD CONSTRAINT "task_assignees_task_id_dfd06a60_fk_tasks_id" FOREIGN KEY ("task_id") REFERENCES "public"."tasks"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "task_assignees" ADD CONSTRAINT "task_assignees_user_id_6b1c6501_fk_users_id" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tasks" ADD CONSTRAINT "tasks_milestone_id_bdae7b7f_fk_milestone_id" FOREIGN KEY ("milestone_id") REFERENCES "public"."milestone"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tracks" ADD CONSTRAINT "tracks_state_id_46f6a1ec_fk_country_states_id" FOREIGN KEY ("state_id") REFERENCES "public"."country_states"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "users" ADD CONSTRAINT "users_state_id_0521d641_fk_country_states_id" FOREIGN KEY ("state_id") REFERENCES "public"."country_states"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "users" ADD CONSTRAINT "users_track_id_e7963e8d_fk_tracks_id" FOREIGN KEY ("track_id") REFERENCES "public"."tracks"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "users_groups" ADD CONSTRAINT "users_groups_group_id_2f3517aa_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "public"."auth_group"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "users_groups" ADD CONSTRAINT "users_groups_user_id_f500bee5_fk_users_id" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "users_user_permissions" ADD CONSTRAINT "users_user_permissio_permission_id_6d08dcd2_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "public"."auth_permission"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "users_user_permissions" ADD CONSTRAINT "users_user_permissions_user_id_92473840_fk_users_id" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "workshop_attendance" ADD CONSTRAINT "workshop_attendance_user_id_c7587c90_fk_users_id" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "workshop_attendance" ADD CONSTRAINT "workshop_attendance_workshop_id_15b47095_fk_workshops" FOREIGN KEY ("workshop_id") REFERENCES "public"."workshops"("workshop_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "workshops" ADD CONSTRAINT "workshops_group_id_452b7f33_fk_groups_id" FOREIGN KEY ("group_id") REFERENCES "public"."groups"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "workshops" ADD CONSTRAINT "workshops_host_user_id_c0c274b0_fk_users_id" FOREIGN KEY ("host_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "account_userId_idx" ON "admin"."account" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "session_userId_idx" ON "admin"."session" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "verification_identifier_idx" ON "admin"."verification" USING btree ("identifier");--> statement-breakpoint
CREATE INDEX "alerts_alert_t_e3b260_idx" ON "alerts" USING btree ("alert_timestamp" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "alerts_resolve_915a53_idx" ON "alerts" USING btree ("resolved" bool_ops);--> statement-breakpoint
CREATE INDEX "alerts_session_6b4a0a_idx" ON "alerts" USING btree ("session_id" int8_ops);--> statement-breakpoint
CREATE INDEX "alerts_session_id_286fb9cc" ON "alerts" USING btree ("session_id" int8_ops);--> statement-breakpoint
CREATE INDEX "auth_group_name_a6ea08ec_like" ON "auth_group" USING btree ("name" varchar_pattern_ops);--> statement-breakpoint
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" USING btree ("group_id" int4_ops);--> statement-breakpoint
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" USING btree ("permission_id" int4_ops);--> statement-breakpoint
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" USING btree ("content_type_id" int4_ops);--> statement-breakpoint
CREATE INDEX "certificate_certifi_187256_idx" ON "certificate_type" USING btree ("certificate_type" text_ops);--> statement-breakpoint
CREATE INDEX "certificate_type_certificate_type_dc054d41_like" ON "certificate_type" USING btree ("certificate_type" varchar_pattern_ops);--> statement-breakpoint
CREATE INDEX "countries_country_6f41c3_idx" ON "countries" USING btree ("country_name" text_ops);--> statement-breakpoint
CREATE INDEX "country_states_country_id_c84f5fb5" ON "country_states" USING btree ("country_id" int8_ops);--> statement-breakpoint
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" USING btree ("content_type_id" int4_ops);--> statement-breakpoint
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" USING btree ("user_id" int8_ops);--> statement-breakpoint
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" USING btree ("expire_date" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "django_session_session_key_c0390e0f_like" ON "django_session" USING btree ("session_key" varchar_pattern_ops);--> statement-breakpoint
CREATE INDEX "event_invit_event_i_c093b3_idx" ON "event_invite" USING btree ("event_id" int8_ops);--> statement-breakpoint
CREATE INDEX "event_invit_user_id_db0358_idx" ON "event_invite" USING btree ("user_id" int8_ops);--> statement-breakpoint
CREATE INDEX "event_invite_event_id_d0229d7f" ON "event_invite" USING btree ("event_id" int8_ops);--> statement-breakpoint
CREATE INDEX "event_invite_user_id_5c26a2a6" ON "event_invite" USING btree ("user_id" int8_ops);--> statement-breakpoint
CREATE INDEX "event_targe_event_i_d53a84_idx" ON "event_target_group" USING btree ("event_id" int8_ops);--> statement-breakpoint
CREATE INDEX "event_targe_group_i_29198c_idx" ON "event_target_group" USING btree ("group_id" int8_ops);--> statement-breakpoint
CREATE INDEX "event_target_group_event_id_3102faf9" ON "event_target_group" USING btree ("event_id" int8_ops);--> statement-breakpoint
CREATE INDEX "event_target_group_group_id_9b0af69c" ON "event_target_group" USING btree ("group_id" int8_ops);--> statement-breakpoint
CREATE INDEX "event_target_role_event_id_62145d19" ON "event_target_role" USING btree ("event_id" int8_ops);--> statement-breakpoint
CREATE INDEX "event_target_role_role_id_f7baea72" ON "event_target_role" USING btree ("role_id" int8_ops);--> statement-breakpoint
CREATE INDEX "event_target_track_event_id_d4858886" ON "event_target_track" USING btree ("event_id" int8_ops);--> statement-breakpoint
CREATE INDEX "event_target_track_track_id_1163cca1" ON "event_target_track" USING btree ("track_id" int8_ops);--> statement-breakpoint
CREATE INDEX "events_host_us_34c951_idx" ON "events" USING btree ("host_user_id" int8_ops);--> statement-breakpoint
CREATE INDEX "events_host_user_id_f7fc239c" ON "events" USING btree ("host_user_id" int8_ops);--> statement-breakpoint
CREATE INDEX "events_start_d_2ddaa0_idx" ON "events" USING btree ("start_datetime" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "group_membe_group_i_d2cebc_idx" ON "group_members" USING btree ("group_id" int8_ops);--> statement-breakpoint
CREATE INDEX "group_membe_user_id_88c209_idx" ON "group_members" USING btree ("user_id" int8_ops);--> statement-breakpoint
CREATE INDEX "group_members_group_id_68d06a36" ON "group_members" USING btree ("group_id" int8_ops);--> statement-breakpoint
CREATE INDEX "group_members_user_id_cffc0595" ON "group_members" USING btree ("user_id" int8_ops);--> statement-breakpoint
CREATE INDEX "groups_creatio_f6499a_idx" ON "groups" USING btree ("creation_datetime" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "groups_deleted_f0201e_idx" ON "groups" USING btree ("deleted_flag" bool_ops);--> statement-breakpoint
CREATE INDEX "groups_track_i_093220_idx" ON "groups" USING btree ("track_id" int8_ops);--> statement-breakpoint
CREATE INDEX "groups_track_id_f29fde9a" ON "groups" USING btree ("track_id" int8_ops);--> statement-breakpoint
CREATE INDEX "login_token_created_7a566c_idx" ON "login_tokens" USING btree ("created_at" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "login_token_expires_133cb3_idx" ON "login_tokens" USING btree ("expires_at" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "login_token_user_id_e66ea4_idx" ON "login_tokens" USING btree ("user_id" text_ops,"token" text_ops);--> statement-breakpoint
CREATE INDEX "login_tokens_user_id_7f12777f" ON "login_tokens" USING btree ("user_id" int8_ops);--> statement-breakpoint
CREATE INDEX "mentor_cert_mentor__f7358b_idx" ON "mentor_certificate" USING btree ("mentor_profile_id" int8_ops,"certificate_type_id" int8_ops);--> statement-breakpoint
CREATE INDEX "mentor_certificate_certificate_type_id_090af26f" ON "mentor_certificate" USING btree ("certificate_type_id" int8_ops);--> statement-breakpoint
CREATE INDEX "mentor_certificate_mentor_profile_id_61bbc118" ON "mentor_certificate" USING btree ("mentor_profile_id" int8_ops);--> statement-breakpoint
CREATE INDEX "mentor_profile_background_id_000edd98" ON "mentor_profile" USING btree ("background_id" int8_ops);--> statement-breakpoint
CREATE INDEX "message_att_message_2a1fa5_idx" ON "message_attachments" USING btree ("message_id" int8_ops);--> statement-breakpoint
CREATE INDEX "message_attachments_attachment_id_29f38e70_like" ON "message_attachments" USING btree ("attachment_id" varchar_pattern_ops);--> statement-breakpoint
CREATE INDEX "message_attachments_message_id_c7a3e22d" ON "message_attachments" USING btree ("message_id" int8_ops);--> statement-breakpoint
CREATE INDEX "message_res_message_8048ce_idx" ON "message_resources" USING btree ("message_id" int8_ops);--> statement-breakpoint
CREATE INDEX "message_res_resourc_d3776f_idx" ON "message_resources" USING btree ("resource_id" int8_ops);--> statement-breakpoint
CREATE INDEX "message_resources_message_id_e0b74b54" ON "message_resources" USING btree ("message_id" int8_ops);--> statement-breakpoint
CREATE INDEX "message_resources_resource_id_7bf8fbc9" ON "message_resources" USING btree ("resource_id" int8_ops);--> statement-breakpoint
CREATE INDEX "message_status_message_id_7d8e74e7" ON "message_status" USING btree ("message_id" int8_ops);--> statement-breakpoint
CREATE INDEX "message_status_user_id_0673798e" ON "message_status" USING btree ("user_id" int8_ops);--> statement-breakpoint
CREATE INDEX "msg_status_message_idx" ON "message_status" USING btree ("message_id" int8_ops);--> statement-breakpoint
CREATE INDEX "msg_status_user_status_idx" ON "message_status" USING btree ("user_id" text_ops,"status" int8_ops);--> statement-breakpoint
CREATE INDEX "messages_deleted_at_idx" ON "messages" USING btree ("deleted_at" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "messages_group_i_a65c01_idx" ON "messages" USING btree ("group_id" int8_ops,"sent_at" int8_ops);--> statement-breakpoint
CREATE INDEX "messages_group_id_0fd96228" ON "messages" USING btree ("group_id" int8_ops);--> statement-breakpoint
CREATE INDEX "messages_group_sent_idx" ON "messages" USING btree ("group_id" timestamptz_ops,"sent_at" int8_ops);--> statement-breakpoint
CREATE INDEX "messages_sender__199d51_idx" ON "messages" USING btree ("sender_user_id" int8_ops);--> statement-breakpoint
CREATE INDEX "messages_sender_idx" ON "messages" USING btree ("sender_user_id" int8_ops);--> statement-breakpoint
CREATE INDEX "messages_sender_user_id_b1b10099" ON "messages" USING btree ("sender_user_id" int8_ops);--> statement-breakpoint
CREATE INDEX "milestone_complet_c0474d_idx" ON "milestone" USING btree ("completed" bool_ops);--> statement-breakpoint
CREATE INDEX "milestone_deleted_5a70fc_idx" ON "milestone" USING btree ("deleted_flag" bool_ops);--> statement-breakpoint
CREATE INDEX "milestone_group_i_aa2495_idx" ON "milestone" USING btree ("group_id" int8_ops);--> statement-breakpoint
CREATE INDEX "milestone_group_id_11a6a79d" ON "milestone" USING btree ("group_id" int8_ops);--> statement-breakpoint
CREATE INDEX "relationship_type_relationship_type_be3ed616_like" ON "relationship_type" USING btree ("relationship_type" varchar_pattern_ops);--> statement-breakpoint
CREATE INDEX "resource_ro_role_id_190238_idx" ON "resource_roles" USING btree ("role_id" int8_ops);--> statement-breakpoint
CREATE INDEX "resource_roles_resource_id_158c512b" ON "resource_roles" USING btree ("resource_id" int8_ops);--> statement-breakpoint
CREATE INDEX "resource_roles_role_id_5ce2ab8a" ON "resource_roles" USING btree ("role_id" int8_ops);--> statement-breakpoint
CREATE INDEX "resource_types_type_name_368352d8_like" ON "resource_types" USING btree ("type_name" varchar_pattern_ops);--> statement-breakpoint
CREATE INDEX "resources_resource_type_id_8ca31a8a" ON "resources" USING btree ("resource_type_id" int8_ops);--> statement-breakpoint
CREATE INDEX "resources_uploade_68f1ef_idx" ON "resources" USING btree ("uploader_user_id_id" int8_ops);--> statement-breakpoint
CREATE INDEX "resources_uploader_user_id_id_f9418bc1" ON "resources" USING btree ("uploader_user_id_id" int8_ops);--> statement-breakpoint
CREATE INDEX "role_assign_role_id_e11f96_idx" ON "role_assignment_history" USING btree ("role_id" int8_ops);--> statement-breakpoint
CREATE INDEX "role_assign_user_id_4edae0_idx" ON "role_assignment_history" USING btree ("user_id" int8_ops);--> statement-breakpoint
CREATE INDEX "role_assignment_history_role_id_807250dc" ON "role_assignment_history" USING btree ("role_id" int8_ops);--> statement-breakpoint
CREATE INDEX "role_assignment_history_user_id_1b78a336" ON "role_assignment_history" USING btree ("user_id" int8_ops);--> statement-breakpoint
CREATE INDEX "roles_role_name_2c8c2fcd_like" ON "roles" USING btree ("role_name" varchar_pattern_ops);--> statement-breakpoint
CREATE INDEX "sessions_access__0097e9_idx" ON "sessions" USING btree ("access_datetime" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "sessions_user_id_05e26f4a" ON "sessions" USING btree ("user_id" int8_ops);--> statement-breakpoint
CREATE INDEX "sessions_user_id_7acd24_idx" ON "sessions" USING btree ("user_id" int8_ops);--> statement-breakpoint
CREATE INDEX "student_int_interes_fc51c3_idx" ON "student_interest" USING btree ("interest_id" int8_ops);--> statement-breakpoint
CREATE INDEX "student_int_user_id_9467fc_idx" ON "student_interest" USING btree ("user_id" int8_ops);--> statement-breakpoint
CREATE INDEX "student_interest_interest_id_7f538900" ON "student_interest" USING btree ("interest_id" int8_ops);--> statement-breakpoint
CREATE INDEX "student_interest_user_id_a32699eb" ON "student_interest" USING btree ("user_id" int8_ops);--> statement-breakpoint
CREATE INDEX "student_pro_interes_58353d_idx" ON "student_profile" USING btree ("interest_id" int8_ops);--> statement-breakpoint
CREATE INDEX "student_pro_supervi_0372b3_idx" ON "student_profile" USING btree ("supervisor_id" int8_ops);--> statement-breakpoint
CREATE INDEX "student_profile_interest_id_fe594703" ON "student_profile" USING btree ("interest_id" int8_ops);--> statement-breakpoint
CREATE INDEX "student_profile_supervisor_id_4bc6991c" ON "student_profile" USING btree ("supervisor_id" int8_ops);--> statement-breakpoint
CREATE INDEX "student_sup_student_0afdc5_idx" ON "student_supervisor" USING btree ("student_user_id" int8_ops);--> statement-breakpoint
CREATE INDEX "student_sup_supervi_51462f_idx" ON "student_supervisor" USING btree ("supervisor_user_id" int8_ops);--> statement-breakpoint
CREATE INDEX "student_supervisor_relationship_type_id_18e3edd0" ON "student_supervisor" USING btree ("relationship_type_id" int8_ops);--> statement-breakpoint
CREATE INDEX "student_supervisor_student_user_id_fb056317" ON "student_supervisor" USING btree ("student_user_id" int8_ops);--> statement-breakpoint
CREATE INDEX "student_supervisor_supervisor_user_id_8a5fb4d1" ON "student_supervisor" USING btree ("supervisor_user_id" int8_ops);--> statement-breakpoint
CREATE INDEX "ta_active_by_task" ON "task_assignees" USING btree ("task_id" int8_ops) WHERE (NOT deleted_flag);--> statement-breakpoint
CREATE INDEX "ta_active_by_user" ON "task_assignees" USING btree ("user_id" int8_ops) WHERE (NOT deleted_flag);--> statement-breakpoint
CREATE INDEX "task_assign_assigne_94a93f_idx" ON "task_assignees" USING btree ("assigned_datetime" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "task_assign_task_id_39473c_idx" ON "task_assignees" USING btree ("task_id" int8_ops);--> statement-breakpoint
CREATE INDEX "task_assign_user_id_504562_idx" ON "task_assignees" USING btree ("user_id" int8_ops);--> statement-breakpoint
CREATE INDEX "task_assignees_task_id_dfd06a60" ON "task_assignees" USING btree ("task_id" int8_ops);--> statement-breakpoint
CREATE INDEX "task_assignees_user_id_6b1c6501" ON "task_assignees" USING btree ("user_id" int8_ops);--> statement-breakpoint
CREATE INDEX "tasks_due_dat_0359a9_idx" ON "tasks" USING btree ("due_date" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "tasks_milesto_5735eb_idx" ON "tasks" USING btree ("milestone_id" int8_ops);--> statement-breakpoint
CREATE INDEX "tasks_milestone_id_bdae7b7f" ON "tasks" USING btree ("milestone_id" int8_ops);--> statement-breakpoint
CREATE INDEX "tracks_state_i_8ee9cb_idx" ON "tracks" USING btree ("state_id" int8_ops);--> statement-breakpoint
CREATE INDEX "tracks_state_id_46f6a1ec" ON "tracks" USING btree ("state_id" int8_ops);--> statement-breakpoint
CREATE INDEX "tracks_track_n_60cf86_idx" ON "tracks" USING btree ("track_name" text_ops);--> statement-breakpoint
CREATE INDEX "tracks_track_name_cf9addea_like" ON "tracks" USING btree ("track_name" varchar_pattern_ops);--> statement-breakpoint
CREATE INDEX "users_email_0ea73cca_like" ON "users" USING btree ("email" varchar_pattern_ops);--> statement-breakpoint
CREATE INDEX "users_state_i_69ebd8_idx" ON "users" USING btree ("state_id" int8_ops);--> statement-breakpoint
CREATE INDEX "users_state_id_0521d641" ON "users" USING btree ("state_id" int8_ops);--> statement-breakpoint
CREATE INDEX "users_track_i_1a6677_idx" ON "users" USING btree ("track_id" int8_ops);--> statement-breakpoint
CREATE INDEX "users_track_id_e7963e8d" ON "users" USING btree ("track_id" int8_ops);--> statement-breakpoint
CREATE INDEX "users_groups_group_id_2f3517aa" ON "users_groups" USING btree ("group_id" int4_ops);--> statement-breakpoint
CREATE INDEX "users_groups_user_id_f500bee5" ON "users_groups" USING btree ("user_id" int8_ops);--> statement-breakpoint
CREATE INDEX "users_user_permissions_permission_id_6d08dcd2" ON "users_user_permissions" USING btree ("permission_id" int4_ops);--> statement-breakpoint
CREATE INDEX "users_user_permissions_user_id_92473840" ON "users_user_permissions" USING btree ("user_id" int8_ops);--> statement-breakpoint
CREATE INDEX "workshop_attendance_user_id_c7587c90" ON "workshop_attendance" USING btree ("user_id" int8_ops);--> statement-breakpoint
CREATE INDEX "workshop_attendance_workshop_id_15b47095" ON "workshop_attendance" USING btree ("workshop_id" int8_ops);--> statement-breakpoint
CREATE INDEX "workshops_group_i_f53249_idx" ON "workshops" USING btree ("group_id" int8_ops);--> statement-breakpoint
CREATE INDEX "workshops_group_id_452b7f33" ON "workshops" USING btree ("group_id" int8_ops);--> statement-breakpoint
CREATE INDEX "workshops_host_us_e187e4_idx" ON "workshops" USING btree ("host_user_id" int8_ops);--> statement-breakpoint
CREATE INDEX "workshops_host_user_id_c0c274b0" ON "workshops" USING btree ("host_user_id" int8_ops);--> statement-breakpoint
CREATE INDEX "workshops_start_d_ee3d73_idx" ON "workshops" USING btree ("start_datetime" timestamptz_ops);