CREATE TABLE "admin_scope" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "admin_scope_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854776000 START WITH 1 CACHE 1),
	"is_global" boolean NOT NULL,
	"track_id" bigint,
	"user_id" bigint NOT NULL,
	CONSTRAINT "admin_scope_global_or_track" CHECK ((is_global AND (track_id IS NULL)) OR ((NOT is_global) AND (track_id IS NOT NULL)))
);
--> statement-breakpoint
CREATE TABLE "alert" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "alert_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854776000 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone NOT NULL,
	"error_reason" varchar(255) NOT NULL,
	"resolved" boolean NOT NULL,
	"resolved_at" timestamp with time zone,
	"session_id" bigint NOT NULL,
	CONSTRAINT "alert_reason_not_empty" CHECK (NOT ((error_reason)::text = ''::text)),
	CONSTRAINT "alert_resolved_after_created" CHECK ((resolved_at >= created_at) OR (resolved_at IS NULL)),
	CONSTRAINT "alert_resolved_matches_timestamp" CHECK (((NOT resolved) AND (resolved_at IS NULL)) OR (resolved AND (resolved_at IS NOT NULL)))
);
--> statement-breakpoint
CREATE TABLE "announcement_audience" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "announcement_audience_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854776000 START WITH 1 CACHE 1),
	"announcement_id" bigint NOT NULL,
	"role_id" bigint,
	"track_id" bigint,
	CONSTRAINT "announcement_audience_requires_role_or_track" CHECK ((role_id IS NOT NULL) OR (track_id IS NOT NULL))
);
--> statement-breakpoint
CREATE TABLE "announcements" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "announcements_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854776000 START WITH 1 CACHE 1),
	"title" varchar(255) NOT NULL,
	"body" text NOT NULL,
	"visibility_scope" varchar(50) NOT NULL,
	"published_at" timestamp with time zone NOT NULL,
	"archived_at" timestamp with time zone,
	"author_user_id" bigint NOT NULL,
	"track_id" bigint,
	CONSTRAINT "announcement_archived_after_published" CHECK ((archived_at >= published_at) OR (archived_at IS NULL))
);
--> statement-breakpoint
CREATE TABLE "audit_log" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "audit_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854776000 START WITH 1 CACHE 1),
	"entity_type" varchar(100) NOT NULL,
	"entity_id" bigint NOT NULL,
	"action" varchar(100) NOT NULL,
	"before_state" jsonb,
	"after_state" jsonb,
	"created_at" timestamp with time zone NOT NULL,
	"actor_user_id" bigint
);
--> statement-breakpoint
CREATE TABLE "event_rsvp" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "event_rsvp_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854776000 START WITH 1 CACHE 1),
	"rsvp_status" varchar(50) NOT NULL,
	"responded_at" timestamp with time zone,
	"user_id" bigint NOT NULL,
	"event_id" bigint NOT NULL,
	CONSTRAINT "unique_event_rsvp_user" UNIQUE("user_id","event_id"),
	CONSTRAINT "event_rsvp_response_state_valid" CHECK ((responded_at IS NULL) OR ((rsvp_status)::text = ANY ((ARRAY['going'::character varying, 'maybe'::character varying, 'declined'::character varying])::text[])))
);
--> statement-breakpoint
CREATE TABLE "group_membership" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "group_membership_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854776000 START WITH 1 CACHE 1),
	"membership_role" varchar(50) NOT NULL,
	"joined_at" timestamp with time zone NOT NULL,
	"left_at" timestamp with time zone,
	"user_id" bigint NOT NULL,
	"group_id" bigint NOT NULL,
	CONSTRAINT "group_membership_left_after_joined" CHECK ((left_at >= joined_at) OR (left_at IS NULL))
);
--> statement-breakpoint
CREATE TABLE "matching_interest" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "matching_interest_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854776000 START WITH 1 CACHE 1),
	"name" varchar(80) NOT NULL,
	CONSTRAINT "matching_interest_name_key" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "matching_mentor" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "matching_mentor_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854776000 START WITH 1 CACHE 1),
	"first_name" varchar(80) NOT NULL,
	"last_name" varchar(80) NOT NULL,
	"email" varchar(254) NOT NULL,
	"is_active" boolean NOT NULL,
	"background" varchar(120) NOT NULL,
	"institution" varchar(200) NOT NULL,
	"country" varchar(80) NOT NULL,
	"region" varchar(80) NOT NULL,
	"track" varchar(16) NOT NULL,
	"max_groups" smallint NOT NULL,
	CONSTRAINT "matching_mentor_email_key" UNIQUE("email"),
	CONSTRAINT "matching_mentor_max_groups_check" CHECK (max_groups >= 0)
);
--> statement-breakpoint
CREATE TABLE "matching_mentor_interests" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "matching_mentor_interests_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854776000 START WITH 1 CACHE 1),
	"mentor_id" bigint NOT NULL,
	"interest_id" bigint NOT NULL,
	CONSTRAINT "matching_mentor_interests_mentor_id_interest_id_ad1fe674_uniq" UNIQUE("mentor_id","interest_id")
);
--> statement-breakpoint
CREATE TABLE "matching_mentoravailability" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "matching_mentoravailability_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854776000 START WITH 1 CACHE 1),
	"weekday" smallint NOT NULL,
	"start" time NOT NULL,
	"end" time NOT NULL,
	"mentor_id" bigint NOT NULL,
	CONSTRAINT "matching_mentoravailabil_mentor_id_weekday_start__9e83be24_uniq" UNIQUE("weekday","start","end","mentor_id"),
	CONSTRAINT "matching_mentoravailability_weekday_check" CHECK (weekday >= 0)
);
--> statement-breakpoint
CREATE TABLE "matching_student" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "matching_student_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854776000 START WITH 1 CACHE 1),
	"first_name" varchar(80) NOT NULL,
	"last_name" varchar(80) NOT NULL,
	"email" varchar(254) NOT NULL,
	"supervisor_email" varchar(254) NOT NULL,
	"school" varchar(200) NOT NULL,
	"year_level" smallint NOT NULL,
	"country" varchar(80) NOT NULL,
	"region" varchar(80) NOT NULL,
	"preassigned_group" varchar(64) NOT NULL,
	"track" varchar(16) NOT NULL,
	CONSTRAINT "matching_student_email_key" UNIQUE("email"),
	CONSTRAINT "matching_student_year_level_check" CHECK (year_level >= 0)
);
--> statement-breakpoint
CREATE TABLE "matching_student_interests" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "matching_student_interests_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854776000 START WITH 1 CACHE 1),
	"student_id" bigint NOT NULL,
	"interest_id" bigint NOT NULL,
	CONSTRAINT "matching_student_interests_student_id_interest_id_df98b935_uniq" UNIQUE("student_id","interest_id")
);
--> statement-breakpoint
CREATE TABLE "matching_studentgroup" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "matching_studentgroup_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854776000 START WITH 1 CACHE 1),
	"name" varchar(120) NOT NULL,
	"track" varchar(16) NOT NULL,
	"year_min" smallint,
	"year_max" smallint,
	"mentor_id" bigint,
	CONSTRAINT "matching_studentgroup_year_max_check" CHECK (year_max >= 0),
	CONSTRAINT "matching_studentgroup_year_min_check" CHECK (year_min >= 0)
);
--> statement-breakpoint
CREATE TABLE "matching_studentgroup_interests" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "matching_studentgroup_interests_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854776000 START WITH 1 CACHE 1),
	"studentgroup_id" bigint NOT NULL,
	"interest_id" bigint NOT NULL,
	CONSTRAINT "matching_studentgroup_in_studentgroup_id_interest_79199744_uniq" UNIQUE("studentgroup_id","interest_id")
);
--> statement-breakpoint
CREATE TABLE "matching_studentgroup_members" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "matching_studentgroup_members_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854776000 START WITH 1 CACHE 1),
	"studentgroup_id" bigint NOT NULL,
	"student_id" bigint NOT NULL,
	CONSTRAINT "matching_studentgroup_me_studentgroup_id_student__3bdd378f_uniq" UNIQUE("studentgroup_id","student_id")
);
--> statement-breakpoint
CREATE TABLE "mentor_availability" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "mentor_availability_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854776000 START WITH 1 CACHE 1),
	"weekday" smallint NOT NULL,
	"start_time" time NOT NULL,
	"end_time" time NOT NULL,
	"mentor_user_id" bigint NOT NULL,
	CONSTRAINT "unique_mentor_availability_slot" UNIQUE("weekday","start_time","end_time","mentor_user_id"),
	CONSTRAINT "mentor_availability_end_after_start" CHECK (end_time > start_time),
	CONSTRAINT "mentor_availability_weekday_check" CHECK (weekday >= 0),
	CONSTRAINT "mentor_availability_weekday_valid" CHECK ((weekday >= 0) AND (weekday <= 6))
);
--> statement-breakpoint
CREATE TABLE "resource_audience" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "resource_audience_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854776000 START WITH 1 CACHE 1),
	"track_id" bigint,
	"resource_id" bigint NOT NULL,
	"role_id" bigint,
	CONSTRAINT "resource_audience_requires_role_or_track" CHECK ((role_id IS NOT NULL) OR (track_id IS NOT NULL))
);
--> statement-breakpoint
CREATE TABLE "user_interest" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "user_interest_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854776000 START WITH 1 CACHE 1),
	"interest_id" bigint NOT NULL,
	"user_id" bigint NOT NULL,
	CONSTRAINT "pk_user_interest" UNIQUE("interest_id","user_id")
);
--> statement-breakpoint
CREATE TABLE "user_session" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "user_session_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854776000 START WITH 1 CACHE 1),
	"sid" varchar(64) NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"last_activity_at" timestamp with time zone NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"ended_at" timestamp with time zone,
	"revoked_at" timestamp with time zone,
	"user_id" bigint NOT NULL,
	CONSTRAINT "user_session_sid_key" UNIQUE("sid"),
	CONSTRAINT "user_session_activity_after_created" CHECK (last_activity_at >= created_at),
	CONSTRAINT "user_session_ended_after_created" CHECK ((ended_at >= created_at) OR (ended_at IS NULL)),
	CONSTRAINT "user_session_expires_after_created" CHECK (expires_at >= created_at),
	CONSTRAINT "user_session_revoked_after_created" CHECK ((revoked_at >= created_at) OR (revoked_at IS NULL))
);
--> statement-breakpoint
ALTER TABLE "alerts" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "background" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "event_invite" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "group_members" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "message_attachments" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "relationship_type" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "resource_roles" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "sessions" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "student_interest" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
DROP TABLE "alerts" CASCADE;--> statement-breakpoint
DROP TABLE "background" CASCADE;--> statement-breakpoint
DROP TABLE "event_invite" CASCADE;--> statement-breakpoint
DROP TABLE "group_members" CASCADE;--> statement-breakpoint
DROP TABLE "message_attachments" CASCADE;--> statement-breakpoint
DROP TABLE "relationship_type" CASCADE;--> statement-breakpoint
DROP TABLE "resource_roles" CASCADE;--> statement-breakpoint
DROP TABLE "sessions" CASCADE;--> statement-breakpoint
DROP TABLE "student_interest" CASCADE;--> statement-breakpoint
ALTER TABLE "groups" DROP CONSTRAINT "unique_group_name_per_track";--> statement-breakpoint
ALTER TABLE "message_resources" DROP CONSTRAINT "message_resources_message_id_resource_id_9a04fab7_uniq";--> statement-breakpoint
ALTER TABLE "events" DROP CONSTRAINT "check_deleted_flag_and_datetime";--> statement-breakpoint
ALTER TABLE "groups" DROP CONSTRAINT "deleted_after_creation";--> statement-breakpoint
ALTER TABLE "groups" DROP CONSTRAINT "group_creation_not_future";--> statement-breakpoint
ALTER TABLE "groups" DROP CONSTRAINT "group_deleted_flag_datetime_consistent";--> statement-breakpoint
ALTER TABLE "mentor_profile" DROP CONSTRAINT "mentor_max_grp_non_negative";--> statement-breakpoint
ALTER TABLE "resources" DROP CONSTRAINT "deleted_flag_true_if_deleted_datetime";--> statement-breakpoint
ALTER TABLE "resources" DROP CONSTRAINT "resource_upload_not_future";--> statement-breakpoint
ALTER TABLE "resources" DROP CONSTRAINT "deleted_after_upload";--> statement-breakpoint
ALTER TABLE "resources" DROP CONSTRAINT "resource_description_not_empty";--> statement-breakpoint
ALTER TABLE "student_supervisor" DROP CONSTRAINT "relationship_type_not_null";--> statement-breakpoint
ALTER TABLE "mentor_profile" DROP CONSTRAINT "mentor_profile_background_id_000edd98_fk_background_id";
--> statement-breakpoint
ALTER TABLE "resources" DROP CONSTRAINT "resources_resource_type_id_8ca31a8a_fk_resource_types_id";
--> statement-breakpoint
ALTER TABLE "resources" DROP CONSTRAINT "resources_uploader_user_id_id_f9418bc1_fk_users_id";
--> statement-breakpoint
ALTER TABLE "resources" DROP CONSTRAINT "resources_group_id_fk_groups_id";
--> statement-breakpoint
ALTER TABLE "student_profile" DROP CONSTRAINT "student_profile_interest_id_fe594703_fk_areas_of_interest_id";
--> statement-breakpoint
ALTER TABLE "student_supervisor" DROP CONSTRAINT "student_supervisor_relationship_type_id_18e3edd0_fk_relations";
--> statement-breakpoint
ALTER TABLE "users" DROP CONSTRAINT "users_state_id_0521d641_fk_country_states_id";
--> statement-breakpoint
DROP INDEX "countries_country_6f41c3_idx";--> statement-breakpoint
DROP INDEX "groups_creatio_f6499a_idx";--> statement-breakpoint
DROP INDEX "groups_deleted_f0201e_idx";--> statement-breakpoint
DROP INDEX "mentor_profile_background_id_000edd98";--> statement-breakpoint
DROP INDEX "msg_status_message_idx";--> statement-breakpoint
DROP INDEX "msg_status_user_status_idx";--> statement-breakpoint
DROP INDEX "messages_deleted_at_idx";--> statement-breakpoint
DROP INDEX "messages_group_i_a65c01_idx";--> statement-breakpoint
DROP INDEX "messages_group_sent_idx";--> statement-breakpoint
DROP INDEX "messages_sender_idx";--> statement-breakpoint
DROP INDEX "milestone_deleted_5a70fc_idx";--> statement-breakpoint
DROP INDEX "resources_uploade_68f1ef_idx";--> statement-breakpoint
DROP INDEX "resources_group_id_idx";--> statement-breakpoint
DROP INDEX "student_pro_interes_58353d_idx";--> statement-breakpoint
DROP INDEX "student_profile_interest_id_fe594703";--> statement-breakpoint
DROP INDEX "student_supervisor_relationship_type_id_18e3edd0";--> statement-breakpoint
DROP INDEX "tracks_track_n_60cf86_idx";--> statement-breakpoint
DROP INDEX "users_state_i_69ebd8_idx";--> statement-breakpoint
DROP INDEX "users_state_id_0521d641";--> statement-breakpoint
DROP INDEX "login_token_user_id_e66ea4_idx";--> statement-breakpoint
DROP INDEX "resources_resource_type_id_8ca31a8a";--> statement-breakpoint
DROP INDEX "resources_uploader_user_id_id_f9418bc1";--> statement-breakpoint
DROP INDEX "ta_active_by_task";--> statement-breakpoint
DROP INDEX "ta_active_by_user";--> statement-breakpoint
ALTER TABLE "areas_of_interest" ALTER COLUMN "id" SET MAXVALUE 9223372036854776000;--> statement-breakpoint
ALTER TABLE "auth_group_permissions" ALTER COLUMN "id" SET MAXVALUE 9223372036854776000;--> statement-breakpoint
ALTER TABLE "certificate_type" ALTER COLUMN "id" SET MAXVALUE 9223372036854776000;--> statement-breakpoint
ALTER TABLE "countries" ALTER COLUMN "id" SET MAXVALUE 9223372036854776000;--> statement-breakpoint
ALTER TABLE "country_states" ALTER COLUMN "id" SET MAXVALUE 9223372036854776000;--> statement-breakpoint
ALTER TABLE "django_migrations" ALTER COLUMN "id" SET MAXVALUE 9223372036854776000;--> statement-breakpoint
ALTER TABLE "event_target_group" ALTER COLUMN "id" SET MAXVALUE 9223372036854776000;--> statement-breakpoint
ALTER TABLE "event_target_role" ALTER COLUMN "id" SET MAXVALUE 9223372036854776000;--> statement-breakpoint
ALTER TABLE "event_target_track" ALTER COLUMN "id" SET MAXVALUE 9223372036854776000;--> statement-breakpoint
ALTER TABLE "events" ALTER COLUMN "id" SET MAXVALUE 9223372036854776000;--> statement-breakpoint
ALTER TABLE "events" ALTER COLUMN "description" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "events" ALTER COLUMN "humanitix_link" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "groups" ALTER COLUMN "id" SET MAXVALUE 9223372036854776000;--> statement-breakpoint
ALTER TABLE "login_tokens" ALTER COLUMN "id" SET MAXVALUE 9223372036854776000;--> statement-breakpoint
ALTER TABLE "mentor_certificate" ALTER COLUMN "id" SET MAXVALUE 9223372036854776000;--> statement-breakpoint
ALTER TABLE "message_resources" ALTER COLUMN "id" SET MAXVALUE 9223372036854776000;--> statement-breakpoint
ALTER TABLE "message_status" ALTER COLUMN "id" SET MAXVALUE 9223372036854776000;--> statement-breakpoint
ALTER TABLE "messages" ALTER COLUMN "id" SET MAXVALUE 9223372036854776000;--> statement-breakpoint
ALTER TABLE "milestone" ALTER COLUMN "id" SET MAXVALUE 9223372036854776000;--> statement-breakpoint
ALTER TABLE "resource_types" ALTER COLUMN "id" SET MAXVALUE 9223372036854776000;--> statement-breakpoint
ALTER TABLE "resources" ALTER COLUMN "id" SET MAXVALUE 9223372036854776000;--> statement-breakpoint
ALTER TABLE "resources" ALTER COLUMN "storage_key" SET DATA TYPE varchar(255);--> statement-breakpoint
ALTER TABLE "role_assignment_history" ALTER COLUMN "id" SET MAXVALUE 9223372036854776000;--> statement-breakpoint
ALTER TABLE "roles" ALTER COLUMN "id" SET MAXVALUE 9223372036854776000;--> statement-breakpoint
ALTER TABLE "student_supervisor" ALTER COLUMN "id" SET MAXVALUE 9223372036854776000;--> statement-breakpoint
ALTER TABLE "task_assignees" ALTER COLUMN "id" SET MAXVALUE 9223372036854776000;--> statement-breakpoint
ALTER TABLE "tasks" ALTER COLUMN "id" SET MAXVALUE 9223372036854776000;--> statement-breakpoint
ALTER TABLE "tracks" ALTER COLUMN "id" SET MAXVALUE 9223372036854776000;--> statement-breakpoint
ALTER TABLE "tracks" ALTER COLUMN "track_name" SET DATA TYPE varchar(100);--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "id" SET MAXVALUE 9223372036854776000;--> statement-breakpoint
ALTER TABLE "users_groups" ALTER COLUMN "id" SET MAXVALUE 9223372036854776000;--> statement-breakpoint
ALTER TABLE "users_user_permissions" ALTER COLUMN "id" SET MAXVALUE 9223372036854776000;--> statement-breakpoint
ALTER TABLE "workshop_attendance" ALTER COLUMN "id" SET MAXVALUE 9223372036854776000;--> statement-breakpoint
ALTER TABLE "workshops" ALTER COLUMN "workshop_id" SET MAXVALUE 9223372036854776000;--> statement-breakpoint
ALTER TABLE "admin"."user" ADD COLUMN "tracks" jsonb;--> statement-breakpoint
ALTER TABLE "events" ADD COLUMN "event_type" varchar(100);--> statement-breakpoint
ALTER TABLE "events" ADD COLUMN "deleted_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "events" ADD COLUMN "event_image" varchar(255);--> statement-breakpoint
ALTER TABLE "events" ADD COLUMN "track_id" bigint;--> statement-breakpoint
ALTER TABLE "groups" ADD COLUMN "created_at" timestamp with time zone NOT NULL;--> statement-breakpoint
ALTER TABLE "groups" ADD COLUMN "deleted_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "mentor_profile" ADD COLUMN "background" varchar(50);--> statement-breakpoint
ALTER TABLE "mentor_profile" ADD COLUMN "max_group_count" integer NOT NULL;--> statement-breakpoint
ALTER TABLE "milestone" ADD COLUMN "deleted_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "resources" ADD COLUMN "name" varchar(255) NOT NULL;--> statement-breakpoint
ALTER TABLE "resources" ADD COLUMN "description" varchar(255) NOT NULL;--> statement-breakpoint
ALTER TABLE "resources" ADD COLUMN "visibility_scope" varchar(50) NOT NULL;--> statement-breakpoint
ALTER TABLE "resources" ADD COLUMN "uploaded_at" timestamp with time zone NOT NULL;--> statement-breakpoint
ALTER TABLE "resources" ADD COLUMN "deleted_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "resources" ADD COLUMN "track_id" bigint;--> statement-breakpoint
ALTER TABLE "resources" ADD COLUMN "uploaded_by_id" bigint NOT NULL;--> statement-breakpoint
ALTER TABLE "resources" ADD COLUMN "type_id" bigint;--> statement-breakpoint
ALTER TABLE "resources" ADD COLUMN "kind" varchar(50) NOT NULL;--> statement-breakpoint
ALTER TABLE "student_profile" ADD COLUMN "pg_email" varchar(254);--> statement-breakpoint
ALTER TABLE "student_supervisor" ADD COLUMN "relationship_type" varchar(50) NOT NULL;--> statement-breakpoint
ALTER TABLE "task_assignees" ADD COLUMN "deleted_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "tasks" ADD COLUMN "deleted_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "account_status" varchar(50) NOT NULL;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "invited_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "activated_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "admin_scope" ADD CONSTRAINT "admin_scope_track_id_633443ef_fk_tracks_id" FOREIGN KEY ("track_id") REFERENCES "public"."tracks"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "admin_scope" ADD CONSTRAINT "admin_scope_user_id_c9b7737b_fk_users_id" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "alert" ADD CONSTRAINT "alert_session_id_5bdcb2f5_fk_user_session_id" FOREIGN KEY ("session_id") REFERENCES "public"."user_session"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "announcement_audience" ADD CONSTRAINT "announcement_audienc_announcement_id_25bd1712_fk_announcem" FOREIGN KEY ("announcement_id") REFERENCES "public"."announcements"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "announcement_audience" ADD CONSTRAINT "announcement_audience_role_id_571d0f03_fk_roles_id" FOREIGN KEY ("role_id") REFERENCES "public"."roles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "announcement_audience" ADD CONSTRAINT "announcement_audience_track_id_5b49af8c_fk_tracks_id" FOREIGN KEY ("track_id") REFERENCES "public"."tracks"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "announcements" ADD CONSTRAINT "announcements_author_user_id_54f6a903_fk_users_id" FOREIGN KEY ("author_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "announcements" ADD CONSTRAINT "announcements_track_id_ba24ce92_fk_tracks_id" FOREIGN KEY ("track_id") REFERENCES "public"."tracks"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "audit_log" ADD CONSTRAINT "audit_log_actor_user_id_147aa761_fk_users_id" FOREIGN KEY ("actor_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "event_rsvp" ADD CONSTRAINT "event_rsvp_event_id_8ccc26b8_fk_events_id" FOREIGN KEY ("event_id") REFERENCES "public"."events"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "event_rsvp" ADD CONSTRAINT "event_rsvp_user_id_c3df2ffd_fk_users_id" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "group_membership" ADD CONSTRAINT "group_membership_group_id_45c6964f_fk_groups_id" FOREIGN KEY ("group_id") REFERENCES "public"."groups"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "group_membership" ADD CONSTRAINT "group_membership_user_id_35a27eaa_fk_users_id" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "matching_mentor_interests" ADD CONSTRAINT "matching_mentor_inte_interest_id_9292dd16_fk_matching_" FOREIGN KEY ("interest_id") REFERENCES "public"."matching_interest"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "matching_mentor_interests" ADD CONSTRAINT "matching_mentor_inte_mentor_id_d5e11250_fk_matching_" FOREIGN KEY ("mentor_id") REFERENCES "public"."matching_mentor"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "matching_mentoravailability" ADD CONSTRAINT "matching_mentoravail_mentor_id_468a5bf9_fk_matching_" FOREIGN KEY ("mentor_id") REFERENCES "public"."matching_mentor"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "matching_student_interests" ADD CONSTRAINT "matching_student_int_interest_id_b50a0b8a_fk_matching_" FOREIGN KEY ("interest_id") REFERENCES "public"."matching_interest"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "matching_student_interests" ADD CONSTRAINT "matching_student_int_student_id_0d287558_fk_matching_" FOREIGN KEY ("student_id") REFERENCES "public"."matching_student"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "matching_studentgroup" ADD CONSTRAINT "matching_studentgroup_mentor_id_318e9d58_fk_matching_mentor_id" FOREIGN KEY ("mentor_id") REFERENCES "public"."matching_mentor"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "matching_studentgroup_interests" ADD CONSTRAINT "matching_studentgrou_interest_id_39fc584d_fk_matching_" FOREIGN KEY ("interest_id") REFERENCES "public"."matching_interest"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "matching_studentgroup_interests" ADD CONSTRAINT "matching_studentgrou_studentgroup_id_de9a8747_fk_matching_" FOREIGN KEY ("studentgroup_id") REFERENCES "public"."matching_studentgroup"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "matching_studentgroup_members" ADD CONSTRAINT "matching_studentgrou_student_id_f22f0640_fk_matching_" FOREIGN KEY ("student_id") REFERENCES "public"."matching_student"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "matching_studentgroup_members" ADD CONSTRAINT "matching_studentgrou_studentgroup_id_010376c8_fk_matching_" FOREIGN KEY ("studentgroup_id") REFERENCES "public"."matching_studentgroup"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "mentor_availability" ADD CONSTRAINT "mentor_availability_mentor_user_id_f756a8ac_fk_users_id" FOREIGN KEY ("mentor_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "resource_audience" ADD CONSTRAINT "resource_audience_resource_id_4a807083_fk_resources_id" FOREIGN KEY ("resource_id") REFERENCES "public"."resources"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "resource_audience" ADD CONSTRAINT "resource_audience_role_id_34580b4e_fk_roles_id" FOREIGN KEY ("role_id") REFERENCES "public"."roles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "resource_audience" ADD CONSTRAINT "resource_audience_track_id_8c2cfbea_fk_tracks_id" FOREIGN KEY ("track_id") REFERENCES "public"."tracks"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_interest" ADD CONSTRAINT "user_interest_interest_id_0953fed5_fk_areas_of_interest_id" FOREIGN KEY ("interest_id") REFERENCES "public"."areas_of_interest"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_interest" ADD CONSTRAINT "user_interest_user_id_5b53cab9_fk_users_id" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_session" ADD CONSTRAINT "user_session_user_id_babcef0a_fk_users_id" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "admin_scope_track_i_594c81_idx" ON "admin_scope" USING btree ("track_id" int8_ops);--> statement-breakpoint
CREATE INDEX "admin_scope_track_id_633443ef" ON "admin_scope" USING btree ("track_id" int8_ops);--> statement-breakpoint
CREATE INDEX "admin_scope_user_id_4ad1f0_idx" ON "admin_scope" USING btree ("user_id" int8_ops);--> statement-breakpoint
CREATE INDEX "admin_scope_user_id_c9b7737b" ON "admin_scope" USING btree ("user_id" int8_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "unique_admin_scope_per_track" ON "admin_scope" USING btree ("user_id" int8_ops,"track_id" int8_ops) WHERE (NOT is_global);--> statement-breakpoint
CREATE UNIQUE INDEX "unique_global_admin_scope" ON "admin_scope" USING btree ("user_id" int8_ops) WHERE is_global;--> statement-breakpoint
CREATE INDEX "alert_created_417cb1_idx" ON "alert" USING btree ("created_at" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "alert_resolve_79070e_idx" ON "alert" USING btree ("resolved" bool_ops);--> statement-breakpoint
CREATE INDEX "alert_session_0863a0_idx" ON "alert" USING btree ("session_id" int8_ops);--> statement-breakpoint
CREATE INDEX "alert_session_id_5bdcb2f5" ON "alert" USING btree ("session_id" int8_ops);--> statement-breakpoint
CREATE INDEX "announcemen_announc_d9cb5b_idx" ON "announcement_audience" USING btree ("announcement_id" int8_ops);--> statement-breakpoint
CREATE INDEX "announcemen_role_id_1076c4_idx" ON "announcement_audience" USING btree ("role_id" int8_ops);--> statement-breakpoint
CREATE INDEX "announcemen_track_i_391dbc_idx" ON "announcement_audience" USING btree ("track_id" int8_ops);--> statement-breakpoint
CREATE INDEX "announcement_audience_announcement_id_25bd1712" ON "announcement_audience" USING btree ("announcement_id" int8_ops);--> statement-breakpoint
CREATE INDEX "announcement_audience_role_id_571d0f03" ON "announcement_audience" USING btree ("role_id" int8_ops);--> statement-breakpoint
CREATE INDEX "announcement_audience_track_id_5b49af8c" ON "announcement_audience" USING btree ("track_id" int8_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "unique_announcement_role_audience" ON "announcement_audience" USING btree ("announcement_id" int8_ops,"role_id" int8_ops) WHERE ((track_id IS NULL) AND (role_id IS NOT NULL));--> statement-breakpoint
CREATE UNIQUE INDEX "unique_announcement_role_track_audience" ON "announcement_audience" USING btree ("announcement_id" int8_ops,"role_id" int8_ops,"track_id" int8_ops) WHERE ((role_id IS NOT NULL) AND (track_id IS NOT NULL));--> statement-breakpoint
CREATE UNIQUE INDEX "unique_announcement_track_audience" ON "announcement_audience" USING btree ("announcement_id" int8_ops,"track_id" int8_ops) WHERE ((role_id IS NULL) AND (track_id IS NOT NULL));--> statement-breakpoint
CREATE INDEX "announcemen_archive_36591b_idx" ON "announcements" USING btree ("archived_at" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "announcemen_author__403994_idx" ON "announcements" USING btree ("author_user_id" int8_ops);--> statement-breakpoint
CREATE INDEX "announcemen_publish_6b0e06_idx" ON "announcements" USING btree ("published_at" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "announcemen_track_i_c21806_idx" ON "announcements" USING btree ("track_id" int8_ops);--> statement-breakpoint
CREATE INDEX "announcemen_visibil_a80d79_idx" ON "announcements" USING btree ("visibility_scope" text_ops);--> statement-breakpoint
CREATE INDEX "announcements_author_user_id_54f6a903" ON "announcements" USING btree ("author_user_id" int8_ops);--> statement-breakpoint
CREATE INDEX "announcements_track_id_ba24ce92" ON "announcements" USING btree ("track_id" int8_ops);--> statement-breakpoint
CREATE INDEX "audit_log_action_b32d4d_idx" ON "audit_log" USING btree ("action" text_ops);--> statement-breakpoint
CREATE INDEX "audit_log_actor_u_ae2850_idx" ON "audit_log" USING btree ("actor_user_id" int8_ops);--> statement-breakpoint
CREATE INDEX "audit_log_actor_user_id_147aa761" ON "audit_log" USING btree ("actor_user_id" int8_ops);--> statement-breakpoint
CREATE INDEX "audit_log_created_5a7975_idx" ON "audit_log" USING btree ("created_at" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "audit_log_entity__c2633a_idx" ON "audit_log" USING btree ("entity_type" text_ops,"entity_id" text_ops);--> statement-breakpoint
CREATE INDEX "event_rsvp_event_i_393d63_idx" ON "event_rsvp" USING btree ("event_id" int8_ops);--> statement-breakpoint
CREATE INDEX "event_rsvp_event_id_8ccc26b8" ON "event_rsvp" USING btree ("event_id" int8_ops);--> statement-breakpoint
CREATE INDEX "event_rsvp_rsvp_st_80e8a8_idx" ON "event_rsvp" USING btree ("rsvp_status" text_ops);--> statement-breakpoint
CREATE INDEX "event_rsvp_user_id_59b81e_idx" ON "event_rsvp" USING btree ("user_id" int8_ops);--> statement-breakpoint
CREATE INDEX "event_rsvp_user_id_c3df2ffd" ON "event_rsvp" USING btree ("user_id" int8_ops);--> statement-breakpoint
CREATE INDEX "group_membe_group_i_e52645_idx" ON "group_membership" USING btree ("group_id" int8_ops);--> statement-breakpoint
CREATE INDEX "group_membe_left_at_e9e6a8_idx" ON "group_membership" USING btree ("left_at" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "group_membe_user_id_9eabd2_idx" ON "group_membership" USING btree ("user_id" int8_ops);--> statement-breakpoint
CREATE INDEX "group_membership_group_id_45c6964f" ON "group_membership" USING btree ("group_id" int8_ops);--> statement-breakpoint
CREATE INDEX "group_membership_user_id_35a27eaa" ON "group_membership" USING btree ("user_id" int8_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "unique_active_group_membership" ON "group_membership" USING btree ("group_id" int8_ops,"user_id" int8_ops) WHERE (left_at IS NULL);--> statement-breakpoint
CREATE INDEX "matching_interest_name_860b2179_like" ON "matching_interest" USING btree ("name" varchar_pattern_ops);--> statement-breakpoint
CREATE INDEX "matching_mentor_email_a48af002_like" ON "matching_mentor" USING btree ("email" varchar_pattern_ops);--> statement-breakpoint
CREATE INDEX "matching_mentor_interests_interest_id_9292dd16" ON "matching_mentor_interests" USING btree ("interest_id" int8_ops);--> statement-breakpoint
CREATE INDEX "matching_mentor_interests_mentor_id_d5e11250" ON "matching_mentor_interests" USING btree ("mentor_id" int8_ops);--> statement-breakpoint
CREATE INDEX "matching_mentoravailability_mentor_id_468a5bf9" ON "matching_mentoravailability" USING btree ("mentor_id" int8_ops);--> statement-breakpoint
CREATE INDEX "matching_student_email_aa9b61cf_like" ON "matching_student" USING btree ("email" varchar_pattern_ops);--> statement-breakpoint
CREATE INDEX "matching_student_interests_interest_id_b50a0b8a" ON "matching_student_interests" USING btree ("interest_id" int8_ops);--> statement-breakpoint
CREATE INDEX "matching_student_interests_student_id_0d287558" ON "matching_student_interests" USING btree ("student_id" int8_ops);--> statement-breakpoint
CREATE INDEX "matching_studentgroup_mentor_id_318e9d58" ON "matching_studentgroup" USING btree ("mentor_id" int8_ops);--> statement-breakpoint
CREATE INDEX "matching_studentgroup_interests_interest_id_39fc584d" ON "matching_studentgroup_interests" USING btree ("interest_id" int8_ops);--> statement-breakpoint
CREATE INDEX "matching_studentgroup_interests_studentgroup_id_de9a8747" ON "matching_studentgroup_interests" USING btree ("studentgroup_id" int8_ops);--> statement-breakpoint
CREATE INDEX "matching_studentgroup_members_student_id_f22f0640" ON "matching_studentgroup_members" USING btree ("student_id" int8_ops);--> statement-breakpoint
CREATE INDEX "matching_studentgroup_members_studentgroup_id_010376c8" ON "matching_studentgroup_members" USING btree ("studentgroup_id" int8_ops);--> statement-breakpoint
CREATE INDEX "mentor_avai_mentor__83178e_idx" ON "mentor_availability" USING btree ("mentor_user_id" int8_ops);--> statement-breakpoint
CREATE INDEX "mentor_avai_weekday_25332b_idx" ON "mentor_availability" USING btree ("weekday" int2_ops);--> statement-breakpoint
CREATE INDEX "mentor_availability_mentor_user_id_f756a8ac" ON "mentor_availability" USING btree ("mentor_user_id" int8_ops);--> statement-breakpoint
CREATE INDEX "resource_au_resourc_cef2c2_idx" ON "resource_audience" USING btree ("resource_id" int8_ops);--> statement-breakpoint
CREATE INDEX "resource_au_role_id_9287b0_idx" ON "resource_audience" USING btree ("role_id" int8_ops);--> statement-breakpoint
CREATE INDEX "resource_au_track_i_8569c2_idx" ON "resource_audience" USING btree ("track_id" int8_ops);--> statement-breakpoint
CREATE INDEX "resource_audience_resource_id_4a807083" ON "resource_audience" USING btree ("resource_id" int8_ops);--> statement-breakpoint
CREATE INDEX "resource_audience_role_id_34580b4e" ON "resource_audience" USING btree ("role_id" int8_ops);--> statement-breakpoint
CREATE INDEX "resource_audience_track_id_8c2cfbea" ON "resource_audience" USING btree ("track_id" int8_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "unique_resource_role_audience" ON "resource_audience" USING btree ("resource_id" int8_ops,"role_id" int8_ops) WHERE ((track_id IS NULL) AND (role_id IS NOT NULL));--> statement-breakpoint
CREATE UNIQUE INDEX "unique_resource_role_track_audience" ON "resource_audience" USING btree ("resource_id" int8_ops,"role_id" int8_ops,"track_id" int8_ops) WHERE ((role_id IS NOT NULL) AND (track_id IS NOT NULL));--> statement-breakpoint
CREATE UNIQUE INDEX "unique_resource_track_audience" ON "resource_audience" USING btree ("resource_id" int8_ops,"track_id" int8_ops) WHERE ((role_id IS NULL) AND (track_id IS NOT NULL));--> statement-breakpoint
CREATE INDEX "user_intere_interes_4522f5_idx" ON "user_interest" USING btree ("interest_id" int8_ops);--> statement-breakpoint
CREATE INDEX "user_intere_user_id_169ea4_idx" ON "user_interest" USING btree ("user_id" int8_ops);--> statement-breakpoint
CREATE INDEX "user_interest_interest_id_0953fed5" ON "user_interest" USING btree ("interest_id" int8_ops);--> statement-breakpoint
CREATE INDEX "user_interest_user_id_5b53cab9" ON "user_interest" USING btree ("user_id" int8_ops);--> statement-breakpoint
CREATE INDEX "user_sessio_expires_85bda6_idx" ON "user_session" USING btree ("expires_at" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "user_sessio_last_ac_a7b43b_idx" ON "user_session" USING btree ("last_activity_at" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "user_sessio_sid_1a73c0_idx" ON "user_session" USING btree ("sid" text_ops);--> statement-breakpoint
CREATE INDEX "user_sessio_user_id_c6fc39_idx" ON "user_session" USING btree ("user_id" int8_ops);--> statement-breakpoint
CREATE INDEX "user_session_sid_17ee7496_like" ON "user_session" USING btree ("sid" varchar_pattern_ops);--> statement-breakpoint
CREATE INDEX "user_session_user_id_babcef0a" ON "user_session" USING btree ("user_id" int8_ops);--> statement-breakpoint
ALTER TABLE "events" ADD CONSTRAINT "events_track_id_a0bf15c2_fk_tracks_id" FOREIGN KEY ("track_id") REFERENCES "public"."tracks"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "resources" ADD CONSTRAINT "resources_group_id_5680e4d8_fk_groups_id" FOREIGN KEY ("group_id") REFERENCES "public"."groups"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "resources" ADD CONSTRAINT "resources_track_id_c4079c5a_fk_tracks_id" FOREIGN KEY ("track_id") REFERENCES "public"."tracks"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "resources" ADD CONSTRAINT "resources_type_id_93682dd6_fk_resource_types_id" FOREIGN KEY ("type_id") REFERENCES "public"."resource_types"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "resources" ADD CONSTRAINT "resources_uploaded_by_id_918d19f2_fk_users_id" FOREIGN KEY ("uploaded_by_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "countries_country_name_3eac3d42_like" ON "countries" USING btree ("country_name" varchar_pattern_ops);--> statement-breakpoint
CREATE INDEX "event_targe_event_i_bcd600_idx" ON "event_target_role" USING btree ("event_id" int8_ops);--> statement-breakpoint
CREATE INDEX "event_targe_role_id_6f7b73_idx" ON "event_target_role" USING btree ("role_id" int8_ops);--> statement-breakpoint
CREATE INDEX "event_targe_event_i_2f7445_idx" ON "event_target_track" USING btree ("event_id" int8_ops);--> statement-breakpoint
CREATE INDEX "event_targe_track_i_96c57e_idx" ON "event_target_track" USING btree ("track_id" int8_ops);--> statement-breakpoint
CREATE INDEX "events_track_i_d7b306_idx" ON "events" USING btree ("track_id" int8_ops);--> statement-breakpoint
CREATE INDEX "events_track_id_a0bf15c2" ON "events" USING btree ("track_id" int8_ops);--> statement-breakpoint
CREATE INDEX "groups_created_d34ebd_idx" ON "groups" USING btree ("created_at" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "groups_deleted_8ee2fc_idx" ON "groups" USING btree ("deleted_at" timestamptz_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "unique_active_group_name_per_track" ON "groups" USING btree ("track_id" text_ops,"group_name" int8_ops) WHERE (deleted_at IS NULL);--> statement-breakpoint
CREATE INDEX "message_sta_message_5f9800_idx" ON "message_status" USING btree ("message_id" int8_ops);--> statement-breakpoint
CREATE INDEX "message_sta_user_id_2503ad_idx" ON "message_status" USING btree ("user_id" int8_ops,"status" text_ops);--> statement-breakpoint
CREATE INDEX "messages_deleted_555c2c_idx" ON "messages" USING btree ("deleted_at" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "messages_group_i_18591d_idx" ON "messages" USING btree ("group_id" int8_ops,"sent_at" int8_ops);--> statement-breakpoint
CREATE INDEX "milestone_deleted_737b8a_idx" ON "milestone" USING btree ("deleted_at" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "resources_deleted_77ce14_idx" ON "resources" USING btree ("deleted_at" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "resources_group_id_5680e4d8" ON "resources" USING btree ("group_id" int8_ops);--> statement-breakpoint
CREATE INDEX "resources_track_i_c53699_idx" ON "resources" USING btree ("track_id" int8_ops);--> statement-breakpoint
CREATE INDEX "resources_track_id_c4079c5a" ON "resources" USING btree ("track_id" int8_ops);--> statement-breakpoint
CREATE INDEX "resources_uploade_d26da4_idx" ON "resources" USING btree ("uploaded_by_id" int8_ops);--> statement-breakpoint
CREATE INDEX "resources_visibil_2b2301_idx" ON "resources" USING btree ("visibility_scope" text_ops);--> statement-breakpoint
CREATE INDEX "tasks_deleted_1d9a30_idx" ON "tasks" USING btree ("deleted_at" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "users_account_33da0c_idx" ON "users" USING btree ("account_status" text_ops);--> statement-breakpoint
CREATE INDEX "login_token_user_id_e66ea4_idx" ON "login_tokens" USING btree ("user_id" int8_ops,"token" int8_ops);--> statement-breakpoint
CREATE INDEX "resources_resource_type_id_8ca31a8a" ON "resources" USING btree ("type_id" int8_ops);--> statement-breakpoint
CREATE INDEX "resources_uploader_user_id_id_f9418bc1" ON "resources" USING btree ("uploaded_by_id" int8_ops);--> statement-breakpoint
CREATE INDEX "ta_active_by_task" ON "task_assignees" USING btree ("task_id" int8_ops) WHERE (deleted_at IS NULL);--> statement-breakpoint
CREATE INDEX "ta_active_by_user" ON "task_assignees" USING btree ("user_id" int8_ops) WHERE (deleted_at IS NULL);--> statement-breakpoint
ALTER TABLE "events" DROP COLUMN "deleted_flag";--> statement-breakpoint
ALTER TABLE "events" DROP COLUMN "deleted_datetime";--> statement-breakpoint
ALTER TABLE "events" DROP COLUMN "event_image(IMG)";--> statement-breakpoint
ALTER TABLE "groups" DROP COLUMN "creation_datetime";--> statement-breakpoint
ALTER TABLE "groups" DROP COLUMN "deleted_flag";--> statement-breakpoint
ALTER TABLE "groups" DROP COLUMN "deleted_datetime";--> statement-breakpoint
ALTER TABLE "mentor_profile" DROP COLUMN "max_grp_cnt";--> statement-breakpoint
ALTER TABLE "mentor_profile" DROP COLUMN "background_id";--> statement-breakpoint
ALTER TABLE "milestone" DROP COLUMN "deleted_flag";--> statement-breakpoint
ALTER TABLE "resources" DROP COLUMN "resource_name";--> statement-breakpoint
ALTER TABLE "resources" DROP COLUMN "resource_description";--> statement-breakpoint
ALTER TABLE "resources" DROP COLUMN "upload_datetime";--> statement-breakpoint
ALTER TABLE "resources" DROP COLUMN "deleted_flag";--> statement-breakpoint
ALTER TABLE "resources" DROP COLUMN "deleted_datetime";--> statement-breakpoint
ALTER TABLE "resources" DROP COLUMN "uploader_user_id_id";--> statement-breakpoint
ALTER TABLE "resources" DROP COLUMN "resource_type_id";--> statement-breakpoint
ALTER TABLE "resources" DROP COLUMN "file_name";--> statement-breakpoint
ALTER TABLE "resources" DROP COLUMN "resource_kind";--> statement-breakpoint
ALTER TABLE "student_profile" DROP COLUMN "interest_id";--> statement-breakpoint
ALTER TABLE "student_supervisor" DROP COLUMN "relationship_type_id";--> statement-breakpoint
ALTER TABLE "task_assignees" DROP COLUMN "deleted_flag";--> statement-breakpoint
ALTER TABLE "tasks" DROP COLUMN "deleted_flag";--> statement-breakpoint
ALTER TABLE "users" DROP COLUMN "status";--> statement-breakpoint
ALTER TABLE "users" DROP COLUMN "state_id";--> statement-breakpoint
ALTER TABLE "countries" ADD CONSTRAINT "countries_country_name_key" UNIQUE("country_name");--> statement-breakpoint
ALTER TABLE "message_resources" ADD CONSTRAINT "message_resources_message_id_resource_id_9a04fab7_uniq" UNIQUE("resource_id","message_id");--> statement-breakpoint
ALTER TABLE "groups" ADD CONSTRAINT "group_deleted_after_created" CHECK ((deleted_at >= created_at) OR (deleted_at IS NULL));--> statement-breakpoint
ALTER TABLE "mentor_profile" ADD CONSTRAINT "mentor_max_group_count_non_negative" CHECK (max_group_count >= 0);--> statement-breakpoint
ALTER TABLE "mentor_profile" ADD CONSTRAINT "mentor_profile_max_group_count_check" CHECK (max_group_count >= 0);--> statement-breakpoint
ALTER TABLE "resources" ADD CONSTRAINT "deleted_after_upload" CHECK ((deleted_at >= uploaded_at) OR (deleted_at IS NULL));--> statement-breakpoint
ALTER TABLE "resources" ADD CONSTRAINT "resource_description_not_empty" CHECK (NOT ((description)::text = ''::text));