# Generated by Django 5.2.5 on 2026-10-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_email_send_queue'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times_shown', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'presentation_settings',
            },
        ),
    ]
