# Generated by Django 5.2.5 on 2026-04-16 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('background', models.CharField(blank=True, max_length=120)),
                ('institution', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(max_length=80)),
                ('region', models.CharField(blank=True, max_length=80)),
                ('track', models.CharField(choices=[('AUS-NSW', 'AUS-NSW'), ('AUS-QLD', 'AUS-QLD'), ('AUS-VIC', 'AUS-VIC'), ('AUS-WA', 'AUS-WA'), ('BRA', 'BRA'), ('GLOBAL', 'GLOBAL')], default='GLOBAL', max_length=16)),
                ('max_groups', models.PositiveSmallIntegerField(default=1)),
                ('interests', models.ManyToManyField(blank=True, related_name='mentors', to='matching.interest')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('supervisor_email', models.EmailField(blank=True, default='', max_length=254)),
                ('school', models.CharField(blank=True, max_length=200)),
                ('year_level', models.PositiveSmallIntegerField()),
                ('country', models.CharField(max_length=80)),
                ('region', models.CharField(blank=True, max_length=80)),
                ('preassigned_group', models.CharField(blank=True, default='', help_text='Group Number from spreadsheet (already grouped students)', max_length=64)),
                ('track', models.CharField(choices=[('AUS-NSW', 'AUS-NSW'), ('AUS-QLD', 'AUS-QLD'), ('AUS-VIC', 'AUS-VIC'), ('AUS-WA', 'AUS-WA'), ('BRA', 'BRA'), ('GLOBAL', 'GLOBAL')], default='GLOBAL', max_length=16)),
                ('interests', models.ManyToManyField(blank=True, related_name='students', to='matching.interest')),
            ],
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('track', models.CharField(choices=[('AUS-NSW', 'AUS-NSW'), ('AUS-QLD', 'AUS-QLD'), ('AUS-VIC', 'AUS-VIC'), ('AUS-WA', 'AUS-WA'), ('BRA', 'BRA'), ('GLOBAL', 'GLOBAL')], default='GLOBAL', max_length=16)),
                ('year_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('year_max', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('interests', models.ManyToManyField(blank=True, related_name='groups', to='matching.interest')),
                ('members', models.ManyToManyField(blank=True, related_name='groups', to='matching.student')),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='matching.mentor')),
            ],
        ),
        migrations.CreateModel(
            name='MentorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField()),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='matching.mentor')),
            ],
            options={
                'unique_together': {('mentor', 'weekday', 'start', 'end')},
            },
        ),
    ]
