/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthUserRouteImport } from './routes/_auth/user'
import { Route as AuthResourceRouteImport } from './routes/_auth/resource'
import { Route as AuthMentorMatchingRouteImport } from './routes/_auth/mentor-matching'
import { Route as AuthMatchingRouteImport } from './routes/_auth/matching'
import { Route as AuthGroupRouteImport } from './routes/_auth/group'
import { Route as AuthEventRouteImport } from './routes/_auth/event'
import { Route as AuthEmailRouteImport } from './routes/_auth/email'
import { Route as AuthDemoRouteImport } from './routes/_auth/demo'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthUserRoute = AuthUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResourceRoute = AuthResourceRouteImport.update({
  id: '/resource',
  path: '/resource',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthMentorMatchingRoute = AuthMentorMatchingRouteImport.update({
  id: '/mentor-matching',
  path: '/mentor-matching',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthMatchingRoute = AuthMatchingRouteImport.update({
  id: '/matching',
  path: '/matching',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthGroupRoute = AuthGroupRouteImport.update({
  id: '/group',
  path: '/group',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthEventRoute = AuthEventRouteImport.update({
  id: '/event',
  path: '/event',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthEmailRoute = AuthEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthDemoRoute = AuthDemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/signin': typeof SigninRoute
  '/demo': typeof AuthDemoRoute
  '/email': typeof AuthEmailRoute
  '/event': typeof AuthEventRoute
  '/group': typeof AuthGroupRoute
  '/matching': typeof AuthMatchingRoute
  '/mentor-matching': typeof AuthMentorMatchingRoute
  '/resource': typeof AuthResourceRoute
  '/user': typeof AuthUserRoute
}
export interface FileRoutesByTo {
  '/signin': typeof SigninRoute
  '/demo': typeof AuthDemoRoute
  '/email': typeof AuthEmailRoute
  '/event': typeof AuthEventRoute
  '/group': typeof AuthGroupRoute
  '/matching': typeof AuthMatchingRoute
  '/mentor-matching': typeof AuthMentorMatchingRoute
  '/resource': typeof AuthResourceRoute
  '/user': typeof AuthUserRoute
  '/': typeof AuthIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/signin': typeof SigninRoute
  '/_auth/demo': typeof AuthDemoRoute
  '/_auth/email': typeof AuthEmailRoute
  '/_auth/event': typeof AuthEventRoute
  '/_auth/group': typeof AuthGroupRoute
  '/_auth/matching': typeof AuthMatchingRoute
  '/_auth/mentor-matching': typeof AuthMentorMatchingRoute
  '/_auth/resource': typeof AuthResourceRoute
  '/_auth/user': typeof AuthUserRoute
  '/_auth/': typeof AuthIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/demo'
    | '/email'
    | '/event'
    | '/group'
    | '/matching'
    | '/mentor-matching'
    | '/resource'
    | '/user'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/signin'
    | '/demo'
    | '/email'
    | '/event'
    | '/group'
    | '/matching'
    | '/mentor-matching'
    | '/resource'
    | '/user'
    | '/'
  id:
    | '__root__'
    | '/_auth'
    | '/signin'
    | '/_auth/demo'
    | '/_auth/email'
    | '/_auth/event'
    | '/_auth/group'
    | '/_auth/matching'
    | '/_auth/mentor-matching'
    | '/_auth/resource'
    | '/_auth/user'
    | '/_auth/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  SigninRoute: typeof SigninRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/user': {
      id: '/_auth/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof AuthUserRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/resource': {
      id: '/_auth/resource'
      path: '/resource'
      fullPath: '/resource'
      preLoaderRoute: typeof AuthResourceRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/mentor-matching': {
      id: '/_auth/mentor-matching'
      path: '/mentor-matching'
      fullPath: '/mentor-matching'
      preLoaderRoute: typeof AuthMentorMatchingRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/matching': {
      id: '/_auth/matching'
      path: '/matching'
      fullPath: '/matching'
      preLoaderRoute: typeof AuthMatchingRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/group': {
      id: '/_auth/group'
      path: '/group'
      fullPath: '/group'
      preLoaderRoute: typeof AuthGroupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/event': {
      id: '/_auth/event'
      path: '/event'
      fullPath: '/event'
      preLoaderRoute: typeof AuthEventRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/email': {
      id: '/_auth/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof AuthEmailRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/demo': {
      id: '/_auth/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof AuthDemoRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthDemoRoute: typeof AuthDemoRoute
  AuthEmailRoute: typeof AuthEmailRoute
  AuthEventRoute: typeof AuthEventRoute
  AuthGroupRoute: typeof AuthGroupRoute
  AuthMatchingRoute: typeof AuthMatchingRoute
  AuthMentorMatchingRoute: typeof AuthMentorMatchingRoute
  AuthResourceRoute: typeof AuthResourceRoute
  AuthUserRoute: typeof AuthUserRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthDemoRoute: AuthDemoRoute,
  AuthEmailRoute: AuthEmailRoute,
  AuthEventRoute: AuthEventRoute,
  AuthGroupRoute: AuthGroupRoute,
  AuthMatchingRoute: AuthMatchingRoute,
  AuthMentorMatchingRoute: AuthMentorMatchingRoute,
  AuthResourceRoute: AuthResourceRoute,
  AuthUserRoute: AuthUserRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  SigninRoute: SigninRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
