# Generated by Django 5.2.5 on 2026-04-18 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificates', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorcertificate',
            name='mentor_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='users.mentorprofile'),
        ),
        migrations.AddField(
            model_name='mentorcertificate',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='mentorcertificate',
            index=models.Index(fields=['mentor_profile', 'certificate_type'], name='mentor_cert_mentor__f7358b_idx'),
        ),
        migrations.AddConstraint(
            model_name='mentorcertificate',
            constraint=models.UniqueConstraint(fields=('mentor_profile', 'certificate_type', 'certificate_number'), name='unique_certificate_per_mentor'),
        ),
    ]
