# Generated by Django 5.2.5 on 2026-05-07 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentorcertificate',
            options={'ordering': ['id'], 'verbose_name': 'Mentor Certificate', 'verbose_name_plural': 'Mentor Certificates'},
        ),
    ]
