# Generated by Django 5.2.5 on 2026-04-18 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_target_ddl_schema'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='certificatetype',
            new_name='certificate_name_d0665e_idx',
            old_name='certificate_type_name_idx',
        ),
        migrations.RemoveField(
            model_name='certificatetype',
            name='requires_expiry',
        ),
        migrations.RemoveField(
            model_name='certificatetype',
            name='requires_number',
        ),
    ]
