# Generated by Django 5.2.5 on 2026-04-17 04:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_name', models.CharField(max_length=255)),
                ('completed', models.BooleanField(default=False)),
                ('deleted_flag', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.groups')),
            ],
            options={
                'verbose_name': 'Milestone',
                'db_table': 'milestone',
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('due_date', models.DateTimeField()),
                ('deleted_flag', models.BooleanField(default=False)),
                ('task_description', models.CharField(blank=True, max_length=255, null=True)),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.milestone')),
            ],
            options={
                'verbose_name': 'Tasks',
                'db_table': 'tasks',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='TaskAssignees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_flag', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignees', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tasks.tasks')),
            ],
            options={
                'verbose_name': 'Task Assignees',
                'db_table': 'task_assignees',
            },
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['group'], name='milestone_group_i_aa2495_idx'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['completed'], name='milestone_complet_c0474d_idx'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['deleted_flag'], name='milestone_deleted_5a70fc_idx'),
        ),
        migrations.AddIndex(
            model_name='tasks',
            index=models.Index(fields=['due_date'], name='tasks_due_dat_0359a9_idx'),
        ),
        migrations.AddIndex(
            model_name='tasks',
            index=models.Index(fields=['milestone'], name='tasks_milesto_5735eb_idx'),
        ),
        migrations.AddIndex(
            model_name='taskassignees',
            index=models.Index(fields=['task'], name='task_assign_task_id_39473c_idx'),
        ),
        migrations.AddIndex(
            model_name='taskassignees',
            index=models.Index(fields=['user'], name='task_assign_user_id_504562_idx'),
        ),
        migrations.AddIndex(
            model_name='taskassignees',
            index=models.Index(fields=['assigned_datetime'], name='task_assign_assigne_94a93f_idx'),
        ),
        migrations.AddIndex(
            model_name='taskassignees',
            index=models.Index(condition=models.Q(('deleted_flag', False)), fields=['task'], name='ta_active_by_task'),
        ),
        migrations.AddIndex(
            model_name='taskassignees',
            index=models.Index(condition=models.Q(('deleted_flag', False)), fields=['user'], name='ta_active_by_user'),
        ),
        migrations.AddConstraint(
            model_name='taskassignees',
            constraint=models.UniqueConstraint(fields=('task', 'user'), name='unique_task_user'),
        ),
    ]
