# Generated by Django 5.2.5 on 2026-04-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='milestone',
            name='milestone_deleted_5a70fc_idx',
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='deleted_flag',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='deleted_flag',
        ),
        migrations.AddField(
            model_name='milestone',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['deleted_at'], name='milestone_deleted_737b8a_idx'),
        ),
        migrations.AddIndex(
            model_name='tasks',
            index=models.Index(fields=['deleted_at'], name='tasks_deleted_1d9a30_idx'),
        ),
    ]
