# Generated by Django 5.2.5 on 2026-04-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='milestone',
            name='milestone_deleted_5a70fc_idx',
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='deleted_flag',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='deleted_flag',
        ),
        migrations.AddField(
            model_name='milestone',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='milestone',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('blocked', 'Blocked'), ('done', 'Done')], default='todo', max_length=20),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['deleted_at'], name='milestone_deleted_737b8a_idx'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['sort_order'], name='milestone_sort_or_9a884a_idx'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['due_date'], name='milestone_due_dat_0e096e_idx'),
        ),
        migrations.AddIndex(
            model_name='tasks',
            index=models.Index(fields=['status'], name='tasks_status_031d4c_idx'),
        ),
        migrations.AddIndex(
            model_name='tasks',
            index=models.Index(fields=['deleted_at'], name='tasks_deleted_1d9a30_idx'),
        ),
    ]
