# Generated by Django 5.2.5 on 2026-04-23 13:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_milestone_milestone_deleted_5a70fc_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='taskassignees',
            name='ta_active_by_task',
        ),
        migrations.RemoveIndex(
            model_name='taskassignees',
            name='ta_active_by_user',
        ),
        migrations.RemoveField(
            model_name='taskassignees',
            name='deleted_flag',
        ),
        migrations.AddField(
            model_name='taskassignees',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='taskassignees',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['task'], name='ta_active_by_task'),
        ),
        migrations.AddIndex(
            model_name='taskassignees',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['user'], name='ta_active_by_user'),
        ),
    ]
