# Generated by Django 5.2.5 on 2026-05-07 00:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
        ('tasks', '0005_tasks_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Constraints/indexes referencing the fields below must go first: on
        # SQLite, RemoveField rebuilds the table and re-renders them, crashing
        # on the missing field (Postgres DROP COLUMN cascades them silently,
        # which is why this originally applied). The models are deleted a few
        # ops later, so end state is unchanged for already-migrated databases.
        migrations.RemoveConstraint(
            model_name='taskassignees',
            name='unique_task_user',
        ),
        migrations.RemoveIndex(
            model_name='taskassignees',
            name='task_assign_task_id_39473c_idx',
        ),
        migrations.RemoveIndex(
            model_name='taskassignees',
            name='task_assign_user_id_504562_idx',
        ),
        migrations.RemoveIndex(
            model_name='taskassignees',
            name='ta_active_by_task',
        ),
        migrations.RemoveIndex(
            model_name='taskassignees',
            name='ta_active_by_user',
        ),
        migrations.RemoveIndex(
            model_name='tasks',
            name='tasks_milesto_5735eb_idx',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='milestone',
        ),
        migrations.RemoveField(
            model_name='taskassignees',
            name='task',
        ),
        migrations.RemoveField(
            model_name='taskassignees',
            name='user',
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done'), ('blocked', 'Blocked')], default='todo', max_length=50)),
                ('completed', models.BooleanField(default=False)),
                ('task_type', models.CharField(choices=[('group', 'Group'), ('individual', 'Individual')], max_length=20)),
                ('creator_role', models.CharField(choices=[('global_admin', 'Global Administrator'), ('track_admin', 'Track Administrator'), ('mentor', 'Mentor'), ('supervisor', 'Supervisor'), ('student', 'Student')], max_length=20)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_tasks', to='groups.groups')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tasks.task')),
            ],
            options={
                'verbose_name': 'Task',
                'db_table': 'task',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='Milestone',
        ),
        migrations.DeleteModel(
            name='Tasks',
        ),
        migrations.DeleteModel(
            name='TaskAssignees',
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['group', 'deleted_at'], name='task_group_i_48c5f4_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_student', 'deleted_at'], name='task_assigne_30b340_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['parent'], name='task_parent__9efbaa_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created_by'], name='task_created_c32358_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['creator_role'], name='task_creator_098607_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['task_type', 'deleted_at'], name='task_task_ty_887d59_idx'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('task_type', 'group'), ('group__isnull', False), ('assigned_student__isnull', True)), models.Q(('task_type', 'individual'), ('assigned_student__isnull', False), ('group__isnull', True)), _connector='OR'), name='task_type_target_consistency'),
        ),
    ]
