# Generated by Django 5.2.5 on 2026-05-07 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
        ('tasks', '0006_task_rewrite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='task',
            name='task_type_target_consistency',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='task_assigne_30b340_idx',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned_student',
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_user', 'deleted_at'], name='task_assigne_6f1f24_idx'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('task_type', 'group'), ('group__isnull', False), ('assigned_user__isnull', True)), models.Q(('task_type', 'individual'), ('assigned_user__isnull', False), ('group__isnull', True)), _connector='OR'), name='task_type_target_consistency'),
        ),
    ]
