# Generated by Django 5.2.5 on 2026-09-19 13:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0010_remove_resourceaudience_resource_audience_requires_role_or_track_and_more'),
        ('tasks', '0011_remove_task_track'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('creator_role', models.CharField(choices=[('global_admin', 'Administrator'), ('mentor', 'Mentor'), ('supervisor', 'Supervisor'), ('student', 'Student')], max_length=20)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_role_tasks', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_tasks', to='resources.roles')),
            ],
            options={
                'verbose_name': 'Role Task',
                'db_table': 'role_task',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RoleTaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done'), ('blocked', 'Blocked')], default='todo', max_length=50)),
                ('completed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='tasks.roletask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_task_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Role Task Completion',
                'db_table': 'role_task_completion',
            },
        ),
        migrations.AddIndex(
            model_name='roletask',
            index=models.Index(fields=['role', 'deleted_at'], name='role_task_role_id_da2b7f_idx'),
        ),
        migrations.AddIndex(
            model_name='roletask',
            index=models.Index(fields=['created_by'], name='role_task_created_23a84e_idx'),
        ),
        migrations.AddIndex(
            model_name='roletaskcompletion',
            index=models.Index(fields=['role_task'], name='role_task_c_role_ta_d9befc_idx'),
        ),
        migrations.AddIndex(
            model_name='roletaskcompletion',
            index=models.Index(fields=['user'], name='role_task_c_user_id_4afafc_idx'),
        ),
        migrations.AddConstraint(
            model_name='roletaskcompletion',
            constraint=models.UniqueConstraint(fields=('role_task', 'user'), name='unique_role_task_completion'),
        ),
    ]
