# Generated by Django 5.2.5 on 2026-08-17 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0006_delete_tracks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_optional', models.BooleanField(default=False)),
                ('accepts_file', models.BooleanField(default=True)),
                ('accepts_text', models.BooleanField(default=False)),
                ('accepts_link', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'submission_component',
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['code'], name='submission__code_55c126_idx')],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='submissions/')),
                ('text', models.TextField(blank=True)),
                ('link', models.URLField(blank=True, max_length=1024)),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('is_late', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='groups.groups')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to=settings.AUTH_USER_MODEL)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='submissions.submissioncomponent')),
            ],
            options={
                'db_table': 'submission',
                'indexes': [models.Index(fields=['group', 'component'], name='submission_group_i_73dd3e_idx'), models.Index(fields=['submitted_at'], name='submission_submitt_dca630_idx')],
                'constraints': [models.UniqueConstraint(fields=('group', 'component'), name='unique_submission_per_group_component')],
            },
        ),
    ]
