# Generated by Django 5.2.5 on 2026-08-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_placeholder_answer_limits'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('questions', 'Questions'), ('poster', 'Poster'), ('extras', 'Additional materials')], max_length=32, unique=True)),
                ('body', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Submission instruction',
                'db_table': 'submission_instruction',
                'ordering': ['section'],
            },
        ),
    ]
