# Generated by Django 5.2.5 on 2026-08-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0006_seed_submission_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadline',
            name='grace_hours',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
