# Generated by Django 5.2.5 on 2026-08-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0007_deadline_grace_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='reopened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='submitted_answers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='submitted_poster',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='submitted_prototype',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='submitted_prototype_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='submitted_report',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
