# Generated by Django 5.2.5 on 2026-08-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0010_real_question_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissioninstruction',
            name='heading',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
