# Generated by Django 5.2.5 on 2026-08-24 05:29

import apps.submissions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0012_section_headings'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='cohort',
            field=models.PositiveIntegerField(db_index=True, default=apps.submissions.models._default_cohort),
        ),
    ]
