# Generated by Django 5.2.5 on 2026-08-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0013_submission_cohort'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='poster_checks',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='submitted_poster_checks',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
