# Generated by Django 5.2.5 on 2026-08-29 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_delete_tracks'),
        ('submissions', '0014_submission_poster_checks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_sent_on', models.DateField()),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission_reminder', to='groups.groups')),
            ],
            options={
                'verbose_name': 'Submission reminder',
                'db_table': 'submission_reminder',
            },
        ),
    ]
