# Generated by Django 5.2.5 on 2026-09-04 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0016_deadline_set_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupextension',
            name='grace_hours',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
