# Generated by Django 5.2.5 on 2026-09-28 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0019_group_extension_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='project_title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='submission',
            name='submitted_project_title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
