# Generated by Django 5.2.5 on 2026-09-29 02:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0010_unique_active_group_name_per_year'),
        ('submissions', '0020_submission_project_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalistDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closes_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalist_deadlines_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Finalist deadline',
                'db_table': 'submission_finalist_deadline',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinalistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentation', models.JSONField(blank=True, null=True)),
                ('submitted_presentation', models.JSONField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finalist_entry', to='groups.groups')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalist_entries_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Finalist entry',
                'verbose_name_plural': 'Finalist entries',
                'db_table': 'submission_finalist_entry',
            },
        ),
    ]
