# Generated by Django 5.2.5 on 2026-09-30 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0021_finalist_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='prototype_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_prototype_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
