# Generated by Django 5.2.5 on 2026-04-17 23:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_flag', models.BooleanField(default=False)),
                ('deleted_datetime', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.groups')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'db_table': 'announcements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['group'], name='announcemen_group_i_9e8d94_idx'), models.Index(fields=['created_by'], name='announcemen_created_07f545_idx'), models.Index(fields=['start_date', 'end_date'], name='announcemen_start_d_46de7e_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='announcement_end_after_start'), models.CheckConstraint(condition=models.Q(('deleted_flag', False), models.Q(('deleted_flag', True), ('deleted_datetime__isnull', False)), _connector='OR'), name='announcement_deleted_flag_and_datetime')],
            },
        ),
    ]
