# Generated by Django 5.2.5 on 2026-04-18 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('announcements', '0001_initial'),
        ('groups', '0001_initial'),
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcement',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.groups'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='target_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.roles'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['group'], name='announcemen_group_i_9e8d94_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['target_role'], name='announcemen_target__6b8103_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['created_by'], name='announcemen_created_07f545_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['start_date', 'end_date'], name='announcemen_start_d_46de7e_idx'),
        ),
        migrations.AddConstraint(
            model_name='announcement',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='announcement_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='announcement',
            constraint=models.CheckConstraint(condition=models.Q(('deleted_flag', False), models.Q(('deleted_flag', True), ('deleted_datetime__isnull', False)), _connector='OR'), name='announcement_deleted_flag_and_datetime'),
        ),
        migrations.AddConstraint(
            model_name='announcement',
            constraint=models.CheckConstraint(condition=models.Q(('group__isnull', True), ('target_role__isnull', True), _connector='OR'), name='announcement_not_both_group_and_role'),
        ),
    ]
