# Generated by Django 5.2.5 on 2026-04-20 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('announcements', '0001_initial'),
        ('groups', '0001_initial'),
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='author_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcement',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.tracks'),
        ),
        migrations.AddField(
            model_name='announcementaudience',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audiences', to='announcements.announcement'),
        ),
        migrations.AddField(
            model_name='announcementaudience',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.roles'),
        ),
        migrations.AddField(
            model_name='announcementaudience',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.tracks'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['author_user'], name='announcemen_author__403994_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['track'], name='announcemen_track_i_c21806_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['visibility_scope'], name='announcemen_visibil_a80d79_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['published_at'], name='announcemen_publish_6b0e06_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['archived_at'], name='announcemen_archive_36591b_idx'),
        ),
        migrations.AddConstraint(
            model_name='announcement',
            constraint=models.CheckConstraint(condition=models.Q(('archived_at__gte', models.F('published_at')), ('archived_at__isnull', True), _connector='OR'), name='announcement_archived_after_published'),
        ),
        migrations.AddIndex(
            model_name='announcementaudience',
            index=models.Index(fields=['announcement'], name='announcemen_announc_d9cb5b_idx'),
        ),
        migrations.AddIndex(
            model_name='announcementaudience',
            index=models.Index(fields=['role'], name='announcemen_role_id_1076c4_idx'),
        ),
        migrations.AddIndex(
            model_name='announcementaudience',
            index=models.Index(fields=['track'], name='announcemen_track_i_391dbc_idx'),
        ),
        migrations.AddConstraint(
            model_name='announcementaudience',
            constraint=models.CheckConstraint(condition=models.Q(('role__isnull', False), ('track__isnull', False), _connector='OR'), name='announcement_audience_requires_role_or_track'),
        ),
        migrations.AddConstraint(
            model_name='announcementaudience',
            constraint=models.UniqueConstraint(condition=models.Q(('track__isnull', True), ('role__isnull', False)), fields=('announcement', 'role'), name='unique_announcement_role_audience'),
        ),
        migrations.AddConstraint(
            model_name='announcementaudience',
            constraint=models.UniqueConstraint(condition=models.Q(('role__isnull', True), ('track__isnull', False)), fields=('announcement', 'track'), name='unique_announcement_track_audience'),
        ),
        migrations.AddConstraint(
            model_name='announcementaudience',
            constraint=models.UniqueConstraint(condition=models.Q(('role__isnull', False), ('track__isnull', False)), fields=('announcement', 'role', 'track'), name='unique_announcement_role_track_audience'),
        ),
    ]
