# Generated by Django 5.2.5 on 2026-04-18 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
        ('groups', '0004_remove_groupmembership_unique_active_group_membership_and_more'),
        ('resources', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='target_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.roles'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.groups'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['target_role'], name='announcemen_target__6b8103_idx'),
        ),
        migrations.AddConstraint(
            model_name='announcement',
            constraint=models.CheckConstraint(condition=models.Q(('group__isnull', True), ('target_role__isnull', True), _connector='OR'), name='announcement_not_both_group_and_role'),
        ),
    ]
