# Generated by Django 5.2.5 on 2026-05-12 14:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], max_length=16)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('failed_recipients', models.JSONField(blank=True, default=list)),
                ('error_summary', models.TextField(blank=True, default='')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='announcements.announcement')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcement_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'announcement_delivery',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['announcement'], name='announcemen_announc_94176a_idx'), models.Index(fields=['initiated_by'], name='announcemen_initiat_168132_idx'), models.Index(fields=['status'], name='announcemen_status_4521bc_idx'), models.Index(fields=['started_at'], name='announcemen_started_539154_idx')],
            },
        ),
    ]
