# Generated by Django 5.2.5 on 2026-05-14 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_announcement_delivery'),
        ('groups', '0003_alter_groupmembership_membership_role'),
        ('resources', '0004_remove_resources_deleted_flag_true_if_deleted_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='announcementaudience',
            name='announcement_audience_requires_role_or_track',
        ),
        migrations.RemoveConstraint(
            model_name='announcementaudience',
            name='unique_announcement_role_audience',
        ),
        migrations.RemoveConstraint(
            model_name='announcementaudience',
            name='unique_announcement_track_audience',
        ),
        migrations.RemoveConstraint(
            model_name='announcementaudience',
            name='unique_announcement_role_track_audience',
        ),
        migrations.AddField(
            model_name='announcementaudience',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.groups'),
        ),
        migrations.AddIndex(
            model_name='announcementaudience',
            index=models.Index(fields=['group'], name='announcemen_group_i_326f36_idx'),
        ),
        migrations.AddConstraint(
            model_name='announcementaudience',
            constraint=models.CheckConstraint(condition=models.Q(('role__isnull', False), ('track__isnull', False), ('group__isnull', False), _connector='OR'), name='announcement_audience_requires_role_track_or_group'),
        ),
        migrations.AddConstraint(
            model_name='announcementaudience',
            constraint=models.UniqueConstraint(condition=models.Q(('track__isnull', True), ('group__isnull', True), ('role__isnull', False)), fields=('announcement', 'role'), name='unique_announcement_role_audience'),
        ),
        migrations.AddConstraint(
            model_name='announcementaudience',
            constraint=models.UniqueConstraint(condition=models.Q(('role__isnull', True), ('group__isnull', True), ('track__isnull', False)), fields=('announcement', 'track'), name='unique_announcement_track_audience'),
        ),
        migrations.AddConstraint(
            model_name='announcementaudience',
            constraint=models.UniqueConstraint(condition=models.Q(('role__isnull', True), ('track__isnull', True), ('group__isnull', False)), fields=('announcement', 'group'), name='unique_announcement_group_audience'),
        ),
        migrations.AddConstraint(
            model_name='announcementaudience',
            constraint=models.UniqueConstraint(condition=models.Q(('role__isnull', False), ('track__isnull', False), ('group__isnull', True)), fields=('announcement', 'role', 'track'), name='unique_announcement_role_track_audience'),
        ),
    ]
