# Generated by Django 5.2.5 on 2026-07-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_remove_announcementaudience_announcement_audience_requires_role_or_track_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='visibility_scope',
            field=models.CharField(choices=[('public', 'Public'), ('role', 'Role'), ('track', 'Track'), ('scoped', 'Scoped'), ('global', 'Global'), ('track_based', 'Track based'), ('role_based', 'Role based'), ('track_role_based', 'Track and role based')], default='public', max_length=50),
        ),
    ]
