# Generated by Django 5.2.5 on 2026-07-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0006_de_track_data'),
        ('groups', '0004_tracks_is_archived'),
        ('resources', '0008_add_attachment_resource_kind'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='announcementaudience',
            name='announcement_audience_requires_role_track_or_group',
        ),
        migrations.RemoveConstraint(
            model_name='announcementaudience',
            name='unique_announcement_role_audience',
        ),
        migrations.RemoveConstraint(
            model_name='announcementaudience',
            name='unique_announcement_track_audience',
        ),
        migrations.RemoveConstraint(
            model_name='announcementaudience',
            name='unique_announcement_group_audience',
        ),
        migrations.RemoveConstraint(
            model_name='announcementaudience',
            name='unique_announcement_role_track_audience',
        ),
        migrations.RemoveIndex(
            model_name='announcement',
            name='announcemen_track_i_c21806_idx',
        ),
        migrations.RemoveIndex(
            model_name='announcementaudience',
            name='announcemen_track_i_391dbc_idx',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='track',
        ),
        migrations.RemoveField(
            model_name='announcementaudience',
            name='track',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='visibility_scope',
            field=models.CharField(choices=[('public', 'Public'), ('role', 'Role'), ('scoped', 'Scoped'), ('global', 'Global'), ('role_based', 'Role based')], default='public', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='announcementaudience',
            constraint=models.CheckConstraint(condition=models.Q(('role__isnull', False), ('group__isnull', False), _connector='OR'), name='announcement_audience_requires_role_or_group'),
        ),
        migrations.AddConstraint(
            model_name='announcementaudience',
            constraint=models.UniqueConstraint(condition=models.Q(('group__isnull', True), ('role__isnull', False)), fields=('announcement', 'role'), name='unique_announcement_role_audience'),
        ),
        migrations.AddConstraint(
            model_name='announcementaudience',
            constraint=models.UniqueConstraint(condition=models.Q(('role__isnull', True), ('group__isnull', False)), fields=('announcement', 'group'), name='unique_announcement_group_audience'),
        ),
    ]
