# Generated by Django 5.2.5 on 2026-10-04 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0007_remove_announcementaudience_announcement_audience_requires_role_track_or_group_and_more'),
        ('groups', '0011_presentation_availability'),
        ('resources', '0010_remove_resourceaudience_resource_audience_requires_role_or_track_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='announcementaudience',
            name='announcement_audience_requires_role_or_group',
        ),
        migrations.AddField(
            model_name='announcementaudience',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='announcementaudience',
            index=models.Index(fields=['user'], name='announcemen_user_id_942d36_idx'),
        ),
        migrations.AddConstraint(
            model_name='announcementaudience',
            constraint=models.CheckConstraint(condition=models.Q(('role__isnull', False), ('group__isnull', False), ('user__isnull', False), _connector='OR'), name='announcement_audience_requires_role_group_or_user'),
        ),
        migrations.AddConstraint(
            model_name='announcementaudience',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('announcement', 'user'), name='unique_announcement_user_audience'),
        ),
    ]
