# Generated by Django 5.2.5 on 2026-04-18 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='adminmatchrun',
            new_name='admin_match_admin_u_d3f9c3_idx',
            old_name='admin_match_admin_u_idx',
        ),
        migrations.RenameIndex(
            model_name='adminmatchrun',
            new_name='admin_match_created_e26c04_idx',
            old_name='admin_match_created_idx',
        ),
    ]
