# Generated by Django 5.2.5 on 2026-05-04 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.JSONField()),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admin_match_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_match_run',
            },
        ),
    ]
