# Generated by Django 5.2.5 on 2026-04-17 04:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0002_initial'),
        ('resources', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('attachment', 'Attachment'), ('resource', 'Resource Link'), ('system', 'System Message')], default='text', max_length=20)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.groups')),
                ('sender_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'messages',
                'ordering': ['sent_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_links', to='resources.resources')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='chat.messages')),
            ],
            options={
                'verbose_name': 'Message Resource Link',
                'verbose_name_plural': 'Message Resource Links',
                'db_table': 'message_resources',
            },
        ),
        migrations.CreateModel(
            name='MessageAttachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_id', models.CharField(max_length=255, unique=True)),
                ('attachment_filename', models.CharField(max_length=255)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chat.messages')),
            ],
            options={
                'verbose_name': 'Message Attachment',
                'verbose_name_plural': 'Message Attachments',
                'db_table': 'message_attachments',
            },
        ),
        migrations.CreateModel(
            name='MessageStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read')], default='sent', max_length=20)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='chat.messages')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message Status',
                'verbose_name_plural': 'Message Statuses',
                'db_table': 'message_status',
            },
        ),
        migrations.AddIndex(
            model_name='messages',
            index=models.Index(fields=['group', 'sent_at'], name='messages_group_i_18591d_idx'),
        ),
        migrations.AddIndex(
            model_name='messages',
            index=models.Index(fields=['sender_user'], name='messages_sender__199d51_idx'),
        ),
        migrations.AddIndex(
            model_name='messages',
            index=models.Index(fields=['deleted_at'], name='messages_deleted_555c2c_idx'),
        ),
        migrations.AddConstraint(
            model_name='messages',
            constraint=models.CheckConstraint(condition=models.Q(('deleted_at__isnull', True), ('deleted_at__gte', models.F('sent_at')), _connector='OR'), name='message_deleted_after_sent'),
        ),
        migrations.AddConstraint(
            model_name='messages',
            constraint=models.CheckConstraint(condition=models.Q(('edited_at__isnull', True), ('edited_at__gte', models.F('sent_at')), _connector='OR'), name='message_edited_after_sent'),
        ),
        migrations.AddIndex(
            model_name='messageresource',
            index=models.Index(fields=['message'], name='message_res_message_8048ce_idx'),
        ),
        migrations.AddIndex(
            model_name='messageresource',
            index=models.Index(fields=['resource'], name='message_res_resourc_d3776f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messageresource',
            unique_together={('message', 'resource')},
        ),
        migrations.AddIndex(
            model_name='messageattachments',
            index=models.Index(fields=['message'], name='message_att_message_2a1fa5_idx'),
        ),
        migrations.AddConstraint(
            model_name='messageattachments',
            constraint=models.UniqueConstraint(fields=('message', 'attachment_filename'), name='unique_filename_per_message'),
        ),
        migrations.AddIndex(
            model_name='messagestatus',
            index=models.Index(fields=['message'], name='message_sta_message_5f9800_idx'),
        ),
        migrations.AddIndex(
            model_name='messagestatus',
            index=models.Index(fields=['user', 'status'], name='message_sta_user_id_2503ad_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messagestatus',
            unique_together={('message', 'user')},
        ),
    ]
