# Generated by Django 5.2.5 on 2026-04-18 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='sender_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messageresource',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='chat.messages'),
        ),
        migrations.AddField(
            model_name='messageattachments',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chat.messages'),
        ),
        migrations.AddField(
            model_name='messagestatus',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='chat.messages'),
        ),
        migrations.AddField(
            model_name='messagestatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_statuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='messages',
            index=models.Index(fields=['group', 'sent_at'], name='messages_group_i_18591d_idx'),
        ),
        migrations.AddIndex(
            model_name='messages',
            index=models.Index(fields=['sender_user'], name='messages_sender__199d51_idx'),
        ),
        migrations.AddIndex(
            model_name='messages',
            index=models.Index(fields=['deleted_at'], name='messages_deleted_555c2c_idx'),
        ),
        migrations.AddConstraint(
            model_name='messages',
            constraint=models.CheckConstraint(condition=models.Q(('deleted_at__isnull', True), ('deleted_at__gte', models.F('sent_at')), _connector='OR'), name='message_deleted_after_sent'),
        ),
        migrations.AddConstraint(
            model_name='messages',
            constraint=models.CheckConstraint(condition=models.Q(('edited_at__isnull', True), ('edited_at__gte', models.F('sent_at')), _connector='OR'), name='message_edited_after_sent'),
        ),
        migrations.AddIndex(
            model_name='messageresource',
            index=models.Index(fields=['message'], name='message_res_message_8048ce_idx'),
        ),
        migrations.AddIndex(
            model_name='messageresource',
            index=models.Index(fields=['resource'], name='message_res_resourc_d3776f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messageresource',
            unique_together={('message', 'resource')},
        ),
        migrations.AddIndex(
            model_name='messageattachments',
            index=models.Index(fields=['message'], name='message_att_message_2a1fa5_idx'),
        ),
        migrations.AddConstraint(
            model_name='messageattachments',
            constraint=models.UniqueConstraint(fields=('message', 'attachment_filename'), name='unique_filename_per_message'),
        ),
        migrations.AddIndex(
            model_name='messagestatus',
            index=models.Index(fields=['message'], name='message_sta_message_5f9800_idx'),
        ),
        migrations.AddIndex(
            model_name='messagestatus',
            index=models.Index(fields=['user', 'status'], name='message_sta_user_id_2503ad_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messagestatus',
            unique_together={('message', 'user')},
        ),
    ]
