# Generated by Django 5.2.5 on 2026-04-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('resource', 'Resource Link'), ('system', 'System Message')], default='text', max_length=20),
        ),
        migrations.DeleteModel(
            name='MessageAttachments',
        ),
    ]
