# Generated by Django 5.2.5 on 2025-10-17 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_messageresource_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messageresource',
            options={'verbose_name': 'Message Resource', 'verbose_name_plural': 'Message Resource'},
        ),
        migrations.AddField(
            model_name='messageattachments',
            name='attachment_url',
            field=models.URLField(null=True),
        ),
        migrations.AddConstraint(
            model_name='messageattachments',
            constraint=models.UniqueConstraint(fields=('message', 'attachment_url'), name='unique_url_per_message'),
        ),
    ]
