# Generated by Django 5.2.5 on 2026-05-06 00:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_alter_messages_message_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("storage_key", models.CharField(max_length=255)),
                ("attachment_filename", models.CharField(max_length=255)),
                ("attachment_mime_type", models.CharField(blank=True, max_length=100, null=True)),
                ("attachment_size", models.BigIntegerField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="chat.messages",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message Attachment",
                "verbose_name_plural": "Message Attachments",
                "db_table": "message_attachments",
            },
        ),
        migrations.AlterField(
            model_name="messages",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("attachment", "Attachment"),
                    ("resource", "Resource Link"),
                    ("system", "System Message"),
                ],
                default="text",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="messageattachment",
            index=models.Index(fields=["message"], name="message_att_message_406e0a_idx"),
        ),
        migrations.AddIndex(
            model_name="messageattachment",
            index=models.Index(fields=["uploaded_at"], name="message_att_uploade_0b6508_idx"),
        ),
    ]
