# Generated by Django 5.2.5 on 2026-04-11 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_phase2_messaging_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'ordering': ['sent_at'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.RemoveIndex(
            model_name='messages',
            name='messages_group_i_a65c01_idx',
        ),
        migrations.RemoveIndex(
            model_name='messages',
            name='messages_sender_idx',
        ),
        migrations.RenameIndex(
            model_name='messages',
            new_name='messages_group_i_18591d_idx',
            old_name='messages_group_sent_idx',
        ),
        migrations.RenameIndex(
            model_name='messages',
            new_name='messages_deleted_555c2c_idx',
            old_name='messages_deleted_at_idx',
        ),
        migrations.RenameIndex(
            model_name='messagestatus',
            new_name='message_sta_message_5f9800_idx',
            old_name='msg_status_message_idx',
        ),
        migrations.RenameIndex(
            model_name='messagestatus',
            new_name='message_sta_user_id_2503ad_idx',
            old_name='msg_status_user_status_idx',
        ),
    ]
