# Generated by Django 5.2.5 on 2025-10-17 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_messageresource_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageattachments',
            name='attachment_id',
        ),
        migrations.AlterField(
            model_name='messageattachments',
            name='attachment_url',
            field=models.URLField(),
        ),
    ]
