# Generated by Django 5.2.5 on 2026-05-09 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_messagepreview'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='messagepreview',
            new_name='message_pre_message_e479d0_idx',
            old_name='message_pre_message_idx',
        ),
    ]
