# Generated by Django 5.2.5 on 2026-05-11 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_messages_reply_to'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='messageattachment',
            new_name='message_att_message_2a1fa5_idx',
            old_name='message_att_message_406e0a_idx',
        ),
        migrations.RenameIndex(
            model_name='messageattachment',
            new_name='message_att_uploade_690065_idx',
            old_name='message_att_uploade_0b6508_idx',
        ),
    ]
