# Generated by Django 5.2.5 on 2026-05-12 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_rename_message_pre_message_idx_message_pre_message_e479d0_idx'),
        ('chat', '0008_messagemention'),
    ]

    operations = [
    ]
