# Generated by Django 5.2.5 on 2026-05-13 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_merge_20260512_1016'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='messageattachment',
            new_name='message_att_message_2a1fa5_idx',
            old_name='message_att_message_406e0a_idx',
        ),
        migrations.RenameIndex(
            model_name='messageattachment',
            new_name='message_att_uploade_690065_idx',
            old_name='message_att_uploade_0b6508_idx',
        ),
        migrations.RenameIndex(
            model_name='messagereaction',
            new_name='message_rea_message_7f9ef3_idx',
            old_name='message_rea_message_e_a4f1d6_idx',
        ),
        migrations.RenameIndex(
            model_name='messagereaction',
            new_name='message_rea_user_id_565363_idx',
            old_name='message_rea_user_id_b9c021_idx',
        ),
    ]
