# Generated by Django 5.2.5 on 2026-05-14 03:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_rename_message_att_message_406e0a_idx_message_att_message_2a1fa5_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('attachment', 'Attachment'), ('resource', 'Resource Link'), ('system', 'System Message'), ('gif', 'GIF')], default='text', max_length=20),
        ),
        migrations.CreateModel(
            name='MessageGif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='tenor', max_length=32)),
                ('provider_id', models.CharField(max_length=128)),
                ('gif_url', models.URLField(max_length=500)),
                ('preview_url', models.URLField(blank=True, default='', max_length=500)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gif', to='chat.messages')),
            ],
            options={
                'verbose_name': 'Message GIF',
                'verbose_name_plural': 'Message GIFs',
                'db_table': 'message_gifs',
                'indexes': [models.Index(fields=['provider', 'provider_id'], name='message_gif_provide_e0948c_idx')],
            },
        ),
    ]
