# Generated by Django 5.2.5 on 2026-05-19 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_messages_deleted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('attachment', 'Attachment'), ('resource', 'Resource Link'), ('system', 'System Message')], default='text', max_length=20),
        ),
        migrations.DeleteModel(
            name='MessageGif',
        ),
    ]
