# Generated by Django 5.2.5 on 2026-07-19 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_remove_messagegif_and_gif_message_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatDigestState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_notified_at', models.DateTimeField(blank=True, null=True)),
                ('last_notified_message_id', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_digest_state', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Digest State',
                'verbose_name_plural': 'Chat Digest States',
                'db_table': 'chat_digest_state',
            },
        ),
    ]
