# Generated by Django 5.2.5 on 2026-09-01 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='requester_role',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
