# Generated by Django 5.2.5 on 2026-09-02 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_requester_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('account_access', 'Account & Access'), ('programs_groups', 'Programs & Groups'), ('certificates_records', 'Certificates & Records'), ('flagged_content', 'Flagged content')], db_index=True, max_length=32),
        ),
    ]
