# Generated by Django 5.2.5 on 2026-09-04 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticket_category_client_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='awaiting_support_since',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
