# Generated by Django 5.2.5 on 2026-09-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_backfill_awaiting_support_since'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='awaiting_support_paused',
            field=models.BooleanField(default=False),
        ),
    ]
