# Generated by Django 5.2.5 on 2026-04-12 14:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Countries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country_name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "db_table": "countries",
            },
        ),
        migrations.CreateModel(
            name="CountryStates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state_name", models.CharField(max_length=255)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="groups.countries",
                    ),
                ),
            ],
            options={
                "db_table": "country_states",
            },
        ),
        migrations.CreateModel(
            name="Tracks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("track_name", models.CharField(max_length=100, unique=True)),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="groups.countrystates",
                    ),
                ),
            ],
            options={
                "db_table": "tracks",
            },
        ),
        migrations.CreateModel(
            name="Groups",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="groups.tracks",
                    ),
                ),
            ],
            options={
                "db_table": "groups",
            },
        ),
        migrations.AddConstraint(
            model_name="countrystates",
            constraint=models.UniqueConstraint(
                fields=("country", "state_name"),
                name="unique_state_per_country",
            ),
        ),
        migrations.AddIndex(
            model_name="tracks",
            index=models.Index(fields=["state"], name="tracks_state_i_8ee9cb_idx"),
        ),
        migrations.AddIndex(
            model_name="groups",
            index=models.Index(fields=["track"], name="groups_track_i_093220_idx"),
        ),
        migrations.AddIndex(
            model_name="groups",
            index=models.Index(fields=["deleted_at"], name="groups_deleted_8ee2fc_idx"),
        ),
        migrations.AddIndex(
            model_name="groups",
            index=models.Index(fields=["created_at"], name="groups_created_d34ebd_idx"),
        ),
        migrations.AddConstraint(
            model_name="groups",
            constraint=models.UniqueConstraint(
                fields=("track", "group_name"),
                condition=models.Q(("deleted_at__isnull", True)),
                name="unique_active_group_name_per_track",
            ),
        ),
        migrations.AddConstraint(
            model_name="groups",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("deleted_at__gte", models.F("created_at")),
                    ("deleted_at__isnull", True),
                    _connector="OR",
                ),
                name="group_deleted_after_created",
            ),
        ),
        migrations.AddConstraint(
            model_name="groups",
            constraint=models.CheckConstraint(
                condition=models.Q(("group_name__regex", "^\\s*$"), _negated=True),
                name="group_name_not_empty",
            ),
        ),
    ]
