# Generated by Django 5.2.5 on 2026-04-18 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='groupinterest',
            name='interest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.areasofinterest'),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groups',
            name='lead_mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.groups'),
        ),
        migrations.AddField(
            model_name='groupinterest',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='groups.groups'),
        ),
        migrations.AddField(
            model_name='tracks',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='groups.countrystates'),
        ),
        migrations.AddField(
            model_name='groups',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='groups.tracks'),
        ),
        migrations.AddConstraint(
            model_name='countrystates',
            constraint=models.UniqueConstraint(fields=('country', 'state_name'), name='unique_state_per_country'),
        ),
        migrations.AddIndex(
            model_name='groupmembership',
            index=models.Index(fields=['group'], name='group_membe_group_i_e52645_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmembership',
            index=models.Index(fields=['user'], name='group_membe_user_id_9eabd2_idx'),
        ),
        migrations.AddIndex(
            model_name='groupinterest',
            index=models.Index(fields=['group'], name='group_inter_group_i_e7b774_idx'),
        ),
        migrations.AddIndex(
            model_name='groupinterest',
            index=models.Index(fields=['interest'], name='group_inter_interes_2fdf32_idx'),
        ),
        migrations.AddConstraint(
            model_name='groupinterest',
            constraint=models.UniqueConstraint(fields=('group', 'interest'), name='unique_group_interest'),
        ),
        migrations.AddIndex(
            model_name='tracks',
            index=models.Index(fields=['state'], name='tracks_state_i_8ee9cb_idx'),
        ),
        migrations.AddIndex(
            model_name='groups',
            index=models.Index(fields=['track'], name='groups_track_i_093220_idx'),
        ),
        migrations.AddIndex(
            model_name='groups',
            index=models.Index(fields=['created_at'], name='groups_created_d34ebd_idx'),
        ),
        migrations.AddIndex(
            model_name='groups',
            index=models.Index(fields=['deleted_at'], name='groups_deleted_8ee2fc_idx'),
        ),
        migrations.AddConstraint(
            model_name='groups',
            constraint=models.CheckConstraint(condition=models.Q(('group_name__regex', '^\\s*$'), _negated=True), name='group_name_not_empty'),
        ),
    ]
