# Generated by Django 5.2.5 on 2026-04-16 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.groups'),
        ),
        migrations.AddField(
            model_name='tracks',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='groups.countrystates'),
        ),
        migrations.AddField(
            model_name='groups',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='groups.tracks'),
        ),
        migrations.AddConstraint(
            model_name='countrystates',
            constraint=models.UniqueConstraint(fields=('country', 'state_name'), name='unique_state_per_country'),
        ),
        migrations.AddIndex(
            model_name='groupmembership',
            index=models.Index(fields=['group'], name='group_membe_group_i_e52645_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmembership',
            index=models.Index(fields=['user'], name='group_membe_user_id_9eabd2_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmembership',
            index=models.Index(fields=['left_at'], name='group_membe_left_at_e9e6a8_idx'),
        ),
        migrations.AddConstraint(
            model_name='groupmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('left_at__isnull', True)), fields=('group', 'user'), name='unique_active_group_membership'),
        ),
        migrations.AddConstraint(
            model_name='groupmembership',
            constraint=models.CheckConstraint(condition=models.Q(('left_at__gte', models.F('joined_at')), ('left_at__isnull', True), _connector='OR'), name='group_membership_left_after_joined'),
        ),
        migrations.AddIndex(
            model_name='tracks',
            index=models.Index(fields=['state'], name='tracks_state_i_8ee9cb_idx'),
        ),
        migrations.AddIndex(
            model_name='groups',
            index=models.Index(fields=['track'], name='groups_track_i_093220_idx'),
        ),
        migrations.AddIndex(
            model_name='groups',
            index=models.Index(fields=['deleted_at'], name='groups_deleted_8ee2fc_idx'),
        ),
        migrations.AddIndex(
            model_name='groups',
            index=models.Index(fields=['created_at'], name='groups_created_d34ebd_idx'),
        ),
        migrations.AddConstraint(
            model_name='groups',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('track', 'group_name'), name='unique_active_group_name_per_track'),
        ),
        migrations.AddConstraint(
            model_name='groups',
            constraint=models.CheckConstraint(condition=models.Q(('deleted_at__gte', models.F('created_at')), ('deleted_at__isnull', True), _connector='OR'), name='group_deleted_after_created'),
        ),
        migrations.AddConstraint(
            model_name='groups',
            constraint=models.CheckConstraint(condition=models.Q(('group_name__regex', '^\\s*$'), _negated=True), name='group_name_not_empty'),
        ),
    ]
