# Generated by Django 5.2.5 on 2026-05-14 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmembership',
            name='membership_role',
            field=models.CharField(blank=True, choices=[('mentor', 'Mentor'), ('student', 'Student'), ('supervisor', 'Supervisor')], max_length=50),
        ),
    ]
