# Generated by Django 5.2.5 on 2026-04-11 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
        ('users', '0007_remove_studentsupervisor_relationship_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'group_interest',
            },
        ),
        migrations.AddField(
            model_name='groups',
            name='lead_mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groups',
            name='max_members',
            field=models.PositiveSmallIntegerField(blank=True, default=8, null=True),
        ),
        migrations.AddField(
            model_name='groups',
            name='year_max',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groups',
            name='year_min',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='groups',
            index=models.Index(fields=['lead_mentor'], name='groups_lead_me_311a8f_idx'),
        ),
        migrations.AddConstraint(
            model_name='groups',
            constraint=models.CheckConstraint(condition=models.Q(('year_min__isnull', True), ('year_max__isnull', True), ('year_min__lte', models.F('year_max')), _connector='OR'), name='groups_year_range_valid'),
        ),
        migrations.AddField(
            model_name='groupinterest',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_interests', to='groups.groups'),
        ),
        migrations.AddField(
            model_name='groupinterest',
            name='interest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_links', to='users.areasofinterest'),
        ),
        migrations.AddIndex(
            model_name='groupinterest',
            index=models.Index(fields=['group'], name='group_inter_group_i_e7b774_idx'),
        ),
        migrations.AddIndex(
            model_name='groupinterest',
            index=models.Index(fields=['interest'], name='group_inter_interes_2fdf32_idx'),
        ),
        migrations.AddConstraint(
            model_name='groupinterest',
            constraint=models.UniqueConstraint(fields=('group', 'interest'), name='unique_group_interest'),
        ),
    ]
