# Generated by Django 5.2.5 on 2026-04-18 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='groups',
            name='unique_active_group_name_per_track',
        ),
        migrations.RemoveConstraint(
            model_name='groups',
            name='group_deleted_after_created',
        ),
        migrations.RemoveIndex(
            model_name='groups',
            name='groups_deleted_8ee2fc_idx',
        ),
        migrations.RemoveIndex(
            model_name='groups',
            name='groups_created_d34ebd_idx',
        ),
        migrations.RenameField(
            model_name='groups',
            old_name='created_at',
            new_name='creation_datetime',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='deleted_at',
        ),
        migrations.AddField(
            model_name='groups',
            name='deleted_datetime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='groups',
            name='deleted_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='groups',
            index=models.Index(fields=['deleted_flag'], name='groups_deleted_f0201e_idx'),
        ),
        migrations.AddIndex(
            model_name='groups',
            index=models.Index(fields=['creation_datetime'], name='groups_creatio_f6499a_idx'),
        ),
        migrations.AddConstraint(
            model_name='groups',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_flag', False)), fields=('track', 'group_name'), name='unique_active_group_name_per_track'),
        ),
        migrations.AddConstraint(
            model_name='groups',
            constraint=models.CheckConstraint(condition=models.Q(('deleted_flag', False), models.Q(('deleted_flag', True), ('deleted_datetime__isnull', False)), _connector='OR'), name='group_deleted_after_created'),
        ),
    ]
