# Generated by Django 5.2.5 on 2026-04-18 03:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_remove_groups_unique_active_group_name_per_track_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='groupmembership',
            name='unique_active_group_membership',
        ),
        migrations.RemoveConstraint(
            model_name='groupmembership',
            name='group_membership_left_after_joined',
        ),
        migrations.RemoveIndex(
            model_name='groupmembership',
            name='group_membe_left_at_e9e6a8_idx',
        ),
        migrations.RenameIndex(
            model_name='groupmembership',
            new_name='group_membe_group_i_d2cebc_idx',
            old_name='group_membe_group_i_e52645_idx',
        ),
        migrations.RenameIndex(
            model_name='groupmembership',
            new_name='group_membe_user_id_88c209_idx',
            old_name='group_membe_user_id_9eabd2_idx',
        ),
        migrations.RemoveField(
            model_name='groupmembership',
            name='joined_at',
        ),
        migrations.RemoveField(
            model_name='groupmembership',
            name='left_at',
        ),
        migrations.RemoveField(
            model_name='groupmembership',
            name='membership_role',
        ),
        migrations.AddConstraint(
            model_name='groupmembership',
            constraint=models.UniqueConstraint(fields=('group', 'user'), name='unique_group_membership'),
        ),
        migrations.AlterModelTable(
            name='groupmembership',
            table='group_members',
        ),
    ]
