# Generated by Django 5.2.5 on 2026-04-18 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_target_ddl_schema'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='groupinterest',
            new_name='group_inter_group_i_e7b774_idx',
            old_name='group_inter_group_id_idx',
        ),
        migrations.RenameIndex(
            model_name='groupinterest',
            new_name='group_inter_interes_2fdf32_idx',
            old_name='group_inter_interest_id_idx',
        ),
        migrations.RenameIndex(
            model_name='groupmembership',
            new_name='group_membe_group_i_e52645_idx',
            old_name='group_membe_group_i_d2cebc_idx',
        ),
        migrations.RenameIndex(
            model_name='groupmembership',
            new_name='group_membe_user_id_9eabd2_idx',
            old_name='group_membe_user_id_88c209_idx',
        ),
        migrations.RenameIndex(
            model_name='groupmembership',
            new_name='group_membe_left_at_e9e6a8_idx',
            old_name='group_membe_left_at_idx',
        ),
        migrations.RenameIndex(
            model_name='groups',
            new_name='groups_deleted_8ee2fc_idx',
            old_name='groups_deleted_at_idx',
        ),
        migrations.RenameIndex(
            model_name='groups',
            new_name='groups_created_d34ebd_idx',
            old_name='groups_created_at_idx',
        ),
    ]
