# Generated by Django 5.2.5 on 2026-09-27 08:20

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    """Two active groups in the same year can't share a name (ignoring case
    and outer spaces), from 2026 on. Earlier years keep their duplicates."""

    dependencies = [
        ('groups', '0009_merge_groups_year_auto_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='groups',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('group_name')), models.F('year'), condition=models.Q(('deleted_at__isnull', True), ('year__gte', 2026)), name='unique_active_group_name_per_year'),
        ),
    ]
