# Generated by Django 5.2.5 on 2026-09-29 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0010_unique_active_group_name_per_year'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='groupinterest',
            new_name='group_inter_group_i_e7b774_idx',
            old_name='group_inter_group_i_idx',
        ),
        migrations.RenameIndex(
            model_name='groupinterest',
            new_name='group_inter_interes_2fdf32_idx',
            old_name='group_inter_interes_idx',
        ),
    ]
