# Generated by Django 5.2.5 on 2025-09-12 06:19

import django.db.models.deletion
import django.db.models.functions.datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(blank=True, max_length=255, null=True)),
                ('resource_description', models.CharField(max_length=255)),
                ('upload_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_flag', models.BooleanField(default=False)),
                ('deleted_datetime', models.DateTimeField(blank=True, null=True)),
                ('uploader_user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.users')),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
                'db_table': 'resources',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
                'constraints': [models.CheckConstraint(condition=models.Q(('role_name', ''), _negated=True), name='role_name_not_empty')],
            },
        ),
        migrations.CreateModel(
            name='RoleAssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.users')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.roles')),
            ],
            options={
                'verbose_name': 'Role Assignment History',
                'verbose_name_plural': 'Role Assignment Histories',
                'db_table': 'role_assignment_history',
            },
        ),
        migrations.CreateModel(
            name='ResourceRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.resources')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.roles')),
            ],
            options={
                'verbose_name': 'Resource Role',
                'verbose_name_plural': 'Resource Roles',
                'db_table': 'resource_roles',
            },
        ),
        migrations.AddIndex(
            model_name='resources',
            index=models.Index(fields=['uploader_user_id'], name='resources_uploade_68f1ef_idx'),
        ),
        migrations.AddConstraint(
            model_name='resources',
            constraint=models.CheckConstraint(condition=models.Q(('deleted_datetime__isnull', True), ('deleted_flag', True), _connector='OR'), name='deleted_flag_true_if_deleted_datetime'),
        ),
        migrations.AddConstraint(
            model_name='resources',
            constraint=models.CheckConstraint(condition=models.Q(('deleted_datetime__gte', models.F('upload_datetime')), ('deleted_datetime__isnull', True), _connector='OR'), name='deleted_after_upload'),
        ),
        migrations.AddConstraint(
            model_name='resources',
            constraint=models.CheckConstraint(condition=models.Q(('resource_description', ''), _negated=True), name='resource_description_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='resources',
            constraint=models.CheckConstraint(condition=models.Q(('upload_datetime__lte', django.db.models.functions.datetime.Now())), name='resource_upload_not_future'),
        ),
        migrations.AddIndex(
            model_name='roleassignmenthistory',
            index=models.Index(fields=['user'], name='role_assign_user_id_4edae0_idx'),
        ),
        migrations.AddIndex(
            model_name='roleassignmenthistory',
            index=models.Index(fields=['role'], name='role_assign_role_id_e11f96_idx'),
        ),
        migrations.AddConstraint(
            model_name='roleassignmenthistory',
            constraint=models.UniqueConstraint(fields=('user', 'role', 'valid_from'), name='unique_user_role_start'),
        ),
        migrations.AddConstraint(
            model_name='roleassignmenthistory',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__gte', models.F('valid_from'))), name='valid_to_after_valid_from'),
        ),
        migrations.AddIndex(
            model_name='resourceroles',
            index=models.Index(fields=['role'], name='resource_ro_role_id_190238_idx'),
        ),
        migrations.AddConstraint(
            model_name='resourceroles',
            constraint=models.UniqueConstraint(fields=('resource', 'role'), name='pk_resource_role'),
        ),
    ]
