# Generated by Django 5.2.5 on 2026-04-18 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='uploader_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourceaudience',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audiences', to='resources.resources'),
        ),
        migrations.AddField(
            model_name='resources',
            name='resource_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='resources.resourcetype'),
        ),
        migrations.AddField(
            model_name='roleassignmenthistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='roles',
            constraint=models.CheckConstraint(condition=models.Q(('slug', ''), _negated=True), name='role_slug_not_empty'),
        ),
        migrations.AddField(
            model_name='roleassignmenthistory',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resources.roles'),
        ),
        migrations.AddField(
            model_name='resourceaudience',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.roles'),
        ),
        migrations.AddIndex(
            model_name='resources',
            index=models.Index(fields=['uploader_user_id'], name='resources_uploade_68f1ef_idx'),
        ),
        migrations.AddIndex(
            model_name='resources',
            index=models.Index(fields=['track'], name='resources_track_i_c53699_idx'),
        ),
        migrations.AddIndex(
            model_name='resources',
            index=models.Index(fields=['visibility_scope'], name='resources_visibil_2b2301_idx'),
        ),
        migrations.AddConstraint(
            model_name='resources',
            constraint=models.CheckConstraint(condition=models.Q(('deleted_datetime__isnull', True), ('deleted_flag', True), _connector='OR'), name='deleted_flag_true_if_deleted_datetime'),
        ),
        migrations.AddConstraint(
            model_name='resources',
            constraint=models.CheckConstraint(condition=models.Q(('deleted_datetime__gte', models.F('upload_datetime')), ('deleted_datetime__isnull', True), _connector='OR'), name='deleted_after_upload'),
        ),
        migrations.AddConstraint(
            model_name='resources',
            constraint=models.CheckConstraint(condition=models.Q(('resource_description', ''), _negated=True), name='resource_description_not_empty'),
        ),
        migrations.AddIndex(
            model_name='roleassignmenthistory',
            index=models.Index(fields=['user'], name='user_role_a_user_id_79a805_idx'),
        ),
        migrations.AddIndex(
            model_name='roleassignmenthistory',
            index=models.Index(fields=['role'], name='user_role_a_role_id_d38a0f_idx'),
        ),
        migrations.AddConstraint(
            model_name='roleassignmenthistory',
            constraint=models.UniqueConstraint(fields=('user', 'role', 'valid_from'), name='unique_user_role_start'),
        ),
        migrations.AddConstraint(
            model_name='roleassignmenthistory',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gte', models.F('valid_from')), _connector='OR'), name='valid_to_after_valid_from'),
        ),
        migrations.AddIndex(
            model_name='resourceaudience',
            index=models.Index(fields=['resource'], name='resource_au_resourc_cef2c2_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceaudience',
            index=models.Index(fields=['role'], name='resource_au_role_id_9287b0_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceaudience',
            index=models.Index(fields=['track'], name='resource_au_track_i_8569c2_idx'),
        ),
        migrations.AddConstraint(
            model_name='resourceaudience',
            constraint=models.CheckConstraint(condition=models.Q(('role__isnull', False), ('track__isnull', False), _connector='OR'), name='resource_audience_requires_role_or_track'),
        ),
        migrations.AddConstraint(
            model_name='resourceaudience',
            constraint=models.UniqueConstraint(condition=models.Q(('track__isnull', True), ('role__isnull', False)), fields=('resource', 'role'), name='unique_resource_role_audience'),
        ),
        migrations.AddConstraint(
            model_name='resourceaudience',
            constraint=models.UniqueConstraint(condition=models.Q(('role__isnull', True), ('track__isnull', False)), fields=('resource', 'track'), name='unique_resource_track_audience'),
        ),
        migrations.AddConstraint(
            model_name='resourceaudience',
            constraint=models.UniqueConstraint(condition=models.Q(('role__isnull', False), ('track__isnull', False)), fields=('resource', 'role', 'track'), name='unique_resource_role_track_audience'),
        ),
    ]
