# Generated by Django 5.2.5 on 2026-04-26 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
        ('resources', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='file_mime_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resources',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resources',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resources',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='groups.groups'),
        ),
        migrations.AddField(
            model_name='resources',
            name='resource_kind',
            field=models.CharField(choices=[('file', 'File'), ('page', 'Page')], default='file', max_length=50),
        ),
        migrations.AddField(
            model_name='resources',
            name='storage_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resources',
            name='visibility_scope',
            field=models.CharField(choices=[('public', 'Public'), ('role', 'Role'), ('track', 'Track'), ('group', 'Group'), ('scoped', 'Scoped')], default='role', max_length=50),
        ),
    ]
