# Generated by Django 5.2.5 on 2026-04-18 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_target_ddl_schema'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roleassignmenthistory',
            options={'verbose_name': 'User Role Assignment', 'verbose_name_plural': 'User Role Assignments'},
        ),
        migrations.RenameIndex(
            model_name='roleassignmenthistory',
            new_name='user_role_a_user_id_79a805_idx',
            old_name='role_assign_user_id_4edae0_idx',
        ),
        migrations.RenameIndex(
            model_name='roleassignmenthistory',
            new_name='user_role_a_role_id_d38a0f_idx',
            old_name='role_assign_role_id_e11f96_idx',
        ),
    ]
