# Generated by Django 6.0.4 on 2026-04-28 07:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
        ('resources', '0003_resources_file_mime_type_resources_file_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='resources',
            name='deleted_flag_true_if_deleted_datetime',
        ),
        migrations.RemoveConstraint(
            model_name='resources',
            name='deleted_after_upload',
        ),
        migrations.RemoveConstraint(
            model_name='resources',
            name='resource_description_not_empty',
        ),
        migrations.RemoveIndex(
            model_name='resources',
            name='resources_uploade_68f1ef_idx',
        ),
        migrations.RenameField(
            model_name='resources',
            old_name='deleted_datetime',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='resources',
            old_name='resource_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='resources',
            old_name='resource_kind',
            new_name='kind',
        ),
        migrations.RenameField(
            model_name='resources',
            old_name='resource_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='resources',
            old_name='resource_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='resources',
            old_name='upload_datetime',
            new_name='uploaded_at',
        ),
        migrations.RenameField(
            model_name='resources',
            old_name='uploader_user_id',
            new_name='uploaded_by',
        ),
        migrations.AddIndex(
            model_name='resources',
            index=models.Index(fields=['uploaded_by'], name='resources_uploade_d26da4_idx'),
        ),
        migrations.AddIndex(
            model_name='resources',
            index=models.Index(fields=['deleted_at'], name='resources_deleted_77ce14_idx'),
        ),
        migrations.AddConstraint(
            model_name='resources',
            constraint=models.CheckConstraint(condition=models.Q(('deleted_at__gte', models.F('uploaded_at')), ('deleted_at__isnull', True), _connector='OR'), name='deleted_after_upload'),
        ),
        migrations.AddConstraint(
            model_name='resources',
            constraint=models.CheckConstraint(condition=models.Q(('description', ''), _negated=True), name='resource_description_not_empty'),
        ),
        migrations.RemoveField(
            model_name='resources',
            name='deleted_flag',
        ),
        migrations.RemoveField(
            model_name='resources',
            name='file_name',
        ),
    ]
