# Generated by Django 5.2.5 on 2026-05-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_remove_resources_deleted_flag_true_if_deleted_datetime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('color', models.CharField(blank=True, default='', max_length=7)),
            ],
            options={
                'verbose_name': 'Resource Label',
                'verbose_name_plural': 'Resource Labels',
                'db_table': 'resource_labels',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='resources',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='resources', to='resources.resourcelabel'),
        ),
    ]
