# Generated by Django 5.2.5 on 2026-05-15 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_resourcelabel_resources_labels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcelabel',
            name='slug',
        ),
    ]
