# Generated by Django 5.2.5 on 2026-05-15 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_remove_resourcelabel_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcelabel',
            name='color',
        ),
    ]
