# Generated by Codex on 2026-05-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0007_remove_resourcelabel_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resources",
            name="kind",
            field=models.CharField(
                choices=[
                    ("attachment", "Attachment"),
                    ("file", "File"),
                    ("page", "Page"),
                ],
                default="file",
                max_length=50,
            ),
        ),
    ]
