# Generated by Django 5.2.5 on 2026-07-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_de_track_data'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='resourceaudience',
            name='resource_audience_requires_role_or_track',
        ),
        migrations.RemoveConstraint(
            model_name='resourceaudience',
            name='unique_resource_role_audience',
        ),
        migrations.RemoveConstraint(
            model_name='resourceaudience',
            name='unique_resource_track_audience',
        ),
        migrations.RemoveConstraint(
            model_name='resourceaudience',
            name='unique_resource_role_track_audience',
        ),
        migrations.RemoveIndex(
            model_name='resourceaudience',
            name='resource_au_track_i_8569c2_idx',
        ),
        migrations.RemoveIndex(
            model_name='resources',
            name='resources_track_i_c53699_idx',
        ),
        migrations.RemoveField(
            model_name='resourceaudience',
            name='track',
        ),
        migrations.RemoveField(
            model_name='resources',
            name='track',
        ),
        migrations.AlterField(
            model_name='resources',
            name='visibility_scope',
            field=models.CharField(choices=[('public', 'Public'), ('role', 'Role'), ('group', 'Group'), ('scoped', 'Scoped')], default='role', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='resourceaudience',
            constraint=models.CheckConstraint(condition=models.Q(('role__isnull', False)), name='resource_audience_requires_role'),
        ),
        migrations.AddConstraint(
            model_name='resourceaudience',
            constraint=models.UniqueConstraint(condition=models.Q(('role__isnull', False)), fields=('resource', 'role'), name='unique_resource_role_audience'),
        ),
    ]
