# Generated by Django 5.2.5 on 2026-08-30 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0017_alter_events_event_type'),
        ('groups', '0006_delete_tracks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agenda', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group_meeting', to='events.events')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='groups.groups')),
                ('organiser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organised_meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Group Meeting',
                'verbose_name_plural': 'Group Meetings',
                'db_table': 'group_meeting',
                'ordering': ['-event__start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='MeetingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, default='')),
                ('revision', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='note', to='meetings.groupmeeting')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meeting Note',
                'verbose_name_plural': 'Meeting Notes',
                'db_table': 'meeting_note',
            },
        ),
        migrations.CreateModel(
            name='MeetingSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, default='')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='meetings.groupmeeting')),
            ],
            options={
                'verbose_name': 'Meeting Summary',
                'verbose_name_plural': 'Meeting Summaries',
                'db_table': 'meeting_summary',
            },
        ),
        migrations.AddIndex(
            model_name='groupmeeting',
            index=models.Index(fields=['group'], name='group_meeti_group_i_91cdec_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmeeting',
            index=models.Index(fields=['organiser'], name='group_meeti_organis_90d482_idx'),
        ),
    ]
